<script type="text/javascript">
$(document).ready(function() {
    
    var oTable = $("#advertisment_table").dataTable( {

         "bFilter": true,
         "bSearchable": true,
        "bProcessing": true,
       
        "bServerSide": true,
       
        "bLengthChange": true,
        "sAjaxSource": "<?php echo $this->adminUrl('list-advertisment-data', 'advertisment') ?>",
        "iDisplayLength": 50,
        "aaSorting": [[ 0, "desc" ]],
        "aoColumns": [
            { sWidth: '50px' },
            null,
            { sWidth: '100px' },
            { sWidth: '120px' },
            { sWidth: '120px' },
            { sWidth: '120px' },
            { sWidth: '120px' },
            { "bSortable": true, sWidth: '80px' },
            { "bSortable": true, sWidth: '80px' },
            { "bSortable": true, sWidth: '80px' },
            { "bSortable": false, sWidth: '50px' }
        ]
               
    }).yadcf([
        {
          column_number: 0,
          filter_type: "text"
        },
        {
          column_number: 1,
          filter_type: "text"
        },
        {
          column_number: 2,
        },
        {
          column_number: 3,
        },
        {
          column_number: 4,
          filter_type: "range_date",
          date_format: "dd/mm/yy"
        },
        {
          column_number: 5,
          filter_type: "range_date",
          date_format: "dd/mm/yy"
        },
        {
          column_number: 6,
          filter_type: "range_date",
          date_format: "dd/mm/yy"
        },
       {
           
          column_number: 7,
           data: [{
                value: '1',
                label: 'Tak'
            }, {
                value: 'empty_value',
                label: 'Nie'
            }],
        
        },
       {
          column_number: 8,
          data: [{
                value: '1',
                label: 'Tak'
            }, {
                value: 'empty_value',
                label: 'Nie'
            }],
        },
       {
          column_number: 9,
          data: [{
                value: '1',
                label: 'Tak'
            }, {
                value: 'empty_value',
                label: 'Nie'
            }],
        }
        ]);
});


</script>
<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil-2"></span>
                    <span><?php echo $this->translate('Advertisment') ?></span>
                    <div class="box-form right">
                        <a href="<?php echo $this->adminUrl('add-advertisment', 'advertisment') ?>" class="btn btn-success btn-mini"><?php echo $this->translate('Add new') ?></a>
                    </div>
                </h4>
                
            </div>
            <div class="content clearfix">
                <table id="advertisment_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate('Id') ?></th>
                            <th><?php echo $this->translate('Title') ?></th>
                            <th><?php echo $this->translate('Category') ?></th>
                            <th><?php echo $this->translate('Group') ?></th>
                            <th><?php echo $this->translate('Created') ?></th>
                            <th><?php echo $this->translate('Updated') ?></th>
                            <th><?php echo $this->translate('Publish date') ?></th>
                            <th><?php echo $this->translate('Student') ?></th>
                            <th><?php echo $this->translate('Student accept') ?></th>
                            <th><?php echo $this->translate('Breaking advertisment') ?></th>
                            <th><?php echo $this->translate('Options') ?></th>
                        </tr>
                        <tr>
                            <th><?php echo $this->translate('Id') ?></th>
                            <th><?php echo $this->translate('Title') ?></th>
                            <th><?php echo $this->translate('Category') ?></th>
                            <th><?php echo $this->translate('Group') ?></th>
                            <th><?php echo $this->translate('Created') ?></th>
                            <th><?php echo $this->translate('Updated') ?></th>
                            <th><?php echo $this->translate('Publish date') ?></th>
                            <th><?php echo $this->translate('Student') ?></th>
                            <th><?php echo $this->translate('Student accept') ?></th>
                            <th><?php echo $this->translate('Breaking advertisment') ?></th>
                            <th><?php echo $this->translate('Options') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                         <?php echo $this->result; ?>
                    </tbody>
                </table>
                
            </div>

        </div><!-- End .box -->

    </div>
</div>