<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#article_table").dataTable( {

         "bFilter": true,
         "bSearchable": true,
        "bProcessing": true,
       
        "bServerSide": true,
       
        "bLengthChange": true,
        "sAjaxSource": "<?php echo $this->adminUrl('list-advertisment-data', 'advertisment') ?>",
        "iDisplayLength": 50,
        "aaSorting": [[ 0, "desc" ]],
        "aoColumns": [
            { sWidth: '50px' },
            null,
            { sWidth: '200px' },
            { sWidth: '200px' },
            { sWidth: '100px' },
            { sWidth: '100px' },
            { sWidth: '100px' },
            { sWidth: '50px' },
            { sWidth: '50px' },
            { "bSortable": false, sWidth: '100px' }
        ]
               
    }).yadcf([
        {
          column_number: 0,
          filter_type: "text"
        },
        {
          column_number: 1,
          filter_type: "text"
        },
        {
          column_number: 2,
        },
        {
          column_number: 3,
        },
        {
          column_number: 4,
          filter_type: "range_date",
          date_format: "yyyy-mm-dd"
        },
        {
          column_number: 5,
          filter_type: "range_date",
          date_format: "yyyy-mm-dd"
        },
        {
          column_number: 6,
          filter_type: "range_date",
          date_format: "yyyy-mm-dd"
        },
        
        ]);
});
</script> 
<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-advertismentpaper"></span>
                    <span><?php echo $this->translate('Ogłoszenia') ?></span>
                    
                </h4>
                
            </div>
            <div class="content clearfix">
                <table id="article_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Id') ?></th>
                        <th><?php echo $this->translate('Title') ?></th>
                        <th><?php echo $this->translate('Kategoria') ?></th>
                        <th><?php echo $this->translate('Grupa') ?></th>
                        <th><?php echo $this->translate('Created') ?></th>
                        <th><?php echo $this->translate('Updated') ?></th>
                        <th><?php echo $this->translate('Data zakończenia') ?></th>
                        <th><?php echo $this->translate('Wyświetlenia') ?></th>
                        <th><?php echo $this->translate('Aktywny') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                
            </div>

        </div><!-- End .box -->

    </div>
</div>