<?php

/**
 * Job_Model_Doctrine_BaseApplication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $job_id
 * @property string $email
 * @property integer $status
 * @property string $cv
 * @property string $cover
 * @property clob $letter
 * @property string $firstname
 * @property string $lastname
 * @property string $address
 * @property string $tel
 * @property string $mob
 * @property string $availability
 * @property string $expectation
 * @property string $distance
 * @property Job_Model_Doctrine_Job $Job
 * 
 * @package    Admi
 * @subpackage Job
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Job_Model_Doctrine_BaseApplication extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('job_application');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('job_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('cv', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('cover', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('letter', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('firstname', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('lastname', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('tel', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('mob', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('availability', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('expectation', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('distance', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Job_Model_Doctrine_Job as Job', array(
             'local' => 'job_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}