<?php

/**
 * Job_Model_Doctrine_Unverified
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Job
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Job_Model_Doctrine_Unverified extends Job_Model_Doctrine_BaseUnverified
{

}