<?php

/**
 * Job_Model_Doctrine_UnverifiedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Job_Model_Doctrine_UnverifiedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Job_Model_Doctrine_UnverifiedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Job_Model_Doctrine_Unverified');
    }
}