<?php

/**
 * User_Model_Doctrine_Update
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage User
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User_Model_Doctrine_Update extends User_Model_Doctrine_BaseUpdate
{
    public function getToken(){
        return $this->token;
    }
    
    public function getType(){
        return $this->type;
    }
    public function getUserId(){
        return $this->user_id;
    }
    
    public function setValue($value){
        $this->value = $value;
    }
    
    public function getValue(){
        return $this->value;
    }
}