<?php

/**
 * Default_Model_Doctrine_BasePostcode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $postcode
 * @property string $district
 * @property string $town
 * @property string $county
 * @property integer $x
 * @property integer $y
 * @property string $lat
 * @property string $lng
 * @property clob $area1
 * @property clob $area5
 * @property clob $area10
 * @property clob $area20
 * 
 * @package    Admi
 * @subpackage Default
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Default_Model_Doctrine_BasePostcode extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('default_postcode');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('postcode', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('district', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('town', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('county', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('x', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('y', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('lat', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('lng', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('area1', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('area5', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('area10', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('area20', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}