<?php

/**
 * Advertisment_Model_Doctrine_Advertisment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Advertisment
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Advertisment_Model_Doctrine_Advertisment extends Advertisment_Model_Doctrine_BaseAdvertisment
{
    
    
    public static function getAdvertismentPhotoDimensions() {
        return self::$advertismentPhotoDimensions;
    }
 public static $advertismentPhotoDimensions = array(
        '126x126' => 'Admin thumbnail',                  // admin
        '160x160' => 'Thumbnail photo',
        '400x400' => 'Main photo'
    );
 
    public function getId(){
        return $this->_get('id');
    }
    
    
     public function increaseView() {
        $this->views++;
        $this->save();
    }
    
    
    public function setUp() {
        parent::setUp();
        $this->hasOne('Media_Model_Doctrine_Photo as PhotoRoot', array(
            'local' => 'photo_root_id',
            'foreign' => 'id'
        ));
        $this->hasMany('Media_Model_Doctrine_Photo as Photos', array(
            'local' => 'photo_root_id',
            'foreign' => 'root_id'
        ));
        
        
        $this->hasOne('Default_Model_Doctrine_Metatag as Metatags', array(
            'local' => 'metatag_id',
            'foregin' => 'id'
        ));
        
        
         $this->hasOne('User_Model_Doctrine_User as UserCreated', array(
             'local' => 'user_id',
             'foreign' => 'id'));
         
          $this->hasOne('User_Model_Doctrine_User as UserUpdated', array(
             'local' => 'last_user_id',
             'foreign' => 'id'));
    }
}