<?php

/**
 * Advertisment_Model_Doctrine_CatTransTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Advertisment_Model_Doctrine_CatTransTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Advertisment_Model_Doctrine_CatTransTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Advertisment_Model_Doctrine_CatTrans');
    }
}