<?php

/**
 * Advertisment_Model_Doctrine_GroupTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Advertisment
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Advertisment_Model_Doctrine_GroupTranslation extends Advertisment_Model_Doctrine_BaseGroupTranslation
{

}