<section id="bc-t">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="/">Strona główna</a></li>
            <li><span class="sep">   →   </span></li>
            <li><a href="#">Aktualności</a></li>
        </ul>

        <h1 class="blog-title">Aktualności</h1>
    </div>
</section>
<section id="blog-grid">
            <div class="container">
                    <div class="b-menu">
                            <nav id="blog-menu">
                                            <ul class="clearfix">
                                                <?php foreach($this->listNews as $news): ?>
                                                    <li>
                                                        <a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>"><?php echo substr($news['Translation'][$this->language]['title'],0,15); ?></a>
                                                    </li>
                                                <?php endforeach; ?>

                                            </ul>
                                            <a href="#" id="pull-blog">Menu</a>
                                    </nav>
                    </div>
                    <!-- blog menu end -->
                    <!-- BLOG POST #1 -->
                    
                    <?php 
                    $key = 0;
                    foreach($this->newsList as $category => $news): 
                        if($key%2==0):
                        ?>
                    <article class="blog-item">
                            <div class="col-6">
                                    <div class="b-img-s">
                                        <a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>">
                                            <?php
                                                if(strlen($news['PhotoRoot']['filename'])){
                                                    $photoPath = MF_Text::getPhotoPath($news['PhotoRoot'],'470x269'); 
                                                    $photoExists = true;
                                                }
                                                else{
                                                    $photoPath = "/assets/images/swit.png";
                                                    $photoExists = false;
                                                }
                                            ?>
                                            <img 
                                                <?php if(!$photoExists): ?>style="width: auto;
  margin: 0 auto;
  display: block;
  margin-top: 20px;"<?php endif; ?>
                                                src="<?php echo $photoPath; ?>" alt="<?php echo $news['Translation'][$this->language]['title']; ?>" title="<?php echo $news['Translation'][$this->language]['title']; ?>">
				    
                                        </a>
                                    </div>
                            </div>
                            <div class="col-6">
                                    <div class="b-desc arr-l">
                                            <h3>
                                                <a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>"><?php echo $news['Translation'][$this->language]['title']; ?></a>
                                                    
                                            </h3>
                                            <p><?php echo MF_Text::truncate($news['Translation'][$this->language]['content'],150); ?></p>
                                            <div class="date-i">
                                                    <a href="#"><i class="fa fa-calendar"></i> <?php echo MF_Text::timeFormat($news['publish_date'],'d'); ?> <?php echo MF_Text::polishShortMonth($news['publish_date']); ?></a>
                                                    <a href="#" class="btn-small-grey"><?php echo $news['Category']['title']; ?></a>
                                            </div>
                                    </div>
                            </div>
                    </article>
                    <?php else: ?>
                    <!-- BLOG POST #2 -->
                    <article class="blog-item">
                            <div class="col-6">
                                    <div class="b-desc arr-r">
                                            <h3>
                                                <a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>"><?php echo $news['Translation'][$this->language]['title']; ?></a>
                                                    
                                            </h3>
                                           
                                            <p><?php echo MF_Text::truncate($news['Translation'][$this->language]['content'],150); ?></p>
                                            <div class="date-i">
                                                    <a href="#"><i class="fa fa-calendar"></i> <?php echo MF_Text::timeFormat($news['publish_date'],'d'); ?> <?php echo MF_Text::polishShortMonth($news['publish_date']); ?></a>
                                                    <a href="#" class="btn-small-grey"><?php echo $news['Category']['title']; ?></a>
                                            </div>
                                    </div>
                            </div>
                            <div class="col-6">
                                    <div class="b-img-s">
                                        <a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>">
                                            <?php
                                                if(strlen($news['PhotoRoot']['filename'])){
                                                    $photoPath = MF_Text::getPhotoPath($news['PhotoRoot'],'470x269'); 
                                                    $photoExists = true;
                                                }
                                                else{
                                                    $photoPath = "/assets/images/swit.png";
                                                    $photoExists = false;
                                                }
                                            ?>
                                            <img 
                                                <?php if(!$photoExists): ?>style="width: auto;
  margin: 0 auto;
  display: block;
  margin-top: 20px;"<?php endif; ?>
                                                src="<?php echo $photoPath; ?>" alt="<?php echo $news['Translation'][$this->language]['title']; ?>" title="<?php echo $news['Translation'][$this->language]['title']; ?>">
				    
                                        </a>
                                    </div>
                            </div>
                    </article>
                    <?php endif; ?>
                    <?php
                    $key++;
                    endforeach; ?>

                    <!-- PAGINATION -->
                    <div class="pagination">
                            <ul>
                                    <li class="nav-arr prev"><a href="#"><i class="fa fa-angle-left"></i></a></li>
                                    <li><a href="#">1</a></li>
                                    <li class="nav-arr next"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                            </ul>
                    </div>
            </div>
</section>
