<?php
    MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $this->translate('About reviews'));
    echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>
<div class="container">
    <div class="container mt25 offset-0">
        <div class="col-md-12 pagecontainer2 offset-0">
            <div class="hpadding50c">
                <h1 class="lato size30 slim"><?= $this->translate('About reviews')?></h1>
                <p class="aboutarrow"></p>
            </div>
            <div class="line3"></div>

            <div class="hpadding50c">



                <!-- LEFT IMG -->
                <div class="col-md-8 cpdd01 grey2">
                    <div class="pl30 pr30 pb50">
                        <strong>Consumer</strong>
                        <p>Before you add a review for a company, please make sure that you have read our <a href="<?= $this->url(array(),'domain-terms-conditions'); ?>">Terms and Conditions</a>. It is also highly recommended to read Top Tips section of this page.</p>
                        <ul>
                            <li>Select from the menu at the top the ‘Add Review' button </li>
                            
                            <li> Type in company name, which you want to review and click 'Add review' button below.
                                <ul>
                                    <li>If the company that you would like to review, does not appear, please select the 'I cannot find the company' button. Then add basic details of the company and follow the steps below.</li>
                                </ul>
                            </li>
                            <li>Please note that you can add a review for selected company also from this company's profile page by clicking 'Add review' button.</li>
                            <li>Select the star rating that you would like to assign to your review (ascending scale from 1 – 5, with 1 star being the poorest service level and 5 stars being the best service level)</li>
                            <li>Select the company's branch which you want to review</li>
                            <li>If you want to attach certain staff members to the review, you can select staff members from dropdown list.
                                <ul>
                                    <li>If the staff member does not exist on the list, just type in their full name.</li>
                                </ul>
                            </li>
                            <li>Enter the text of your review</li>
                            <li>Select if you would recommend the company to other customers</li>
                            <li>Chose a ‘Display Name’ for yourself. It will be published along with your review.</li>
                            <li>Select the most recent date when did you use this company(this information won't be displayed anywhere on the site)</li>
                            <li>Enter your details (this information won't be displayed anywhere on the site)</li>
                            <li>Accept terms and conditions of the website.</li>
                            <li>Click on the "Submit Review" button.</li>
                            <li>
                                Please go to your email account and find the account activation email from Rate Pole (remember to check junk/spam folder).
                                <ul>
                                    <li>If you cannot find the email, please send us a message to <a href="mailto:activate@rate-pole.com">activate@rate-pole.com</a> from the email address which you used to add a review and we will activate it for you.</li>
                                </ul>
                            </li>
                            <li>Click on the link contained in this email to activate your review.</li>
                            <li>Now your review still has to go through moderation process. We will notify you whether your review has been accepted or rejected.</li>
                        </ul>
                        <br />
                        <strong>Top Tips</strong>
                        <ul>
                            <li>We welcome all constructive reviews.</li>
                            <li>Be honest and fair - when you provide your opinion, this view must be genuinely held.</li>
                            <li>Your content must be accurate, where you state facts, as well as genuine and compliant in all views/opinions stated.</li>
                            <li>Review only companies you have direct experience with.</li>
                            <li>Use of any offensive language is not acceptable.</li>
                            <li>Usage of temporary email addresses are forbidden.</li>
                            <li>We do not accept any reviews added within company network. Such reviews will be automatically rejected.</li>
                            <li>You are allowed to add only 1 review of certain company every 6 months.</li>
                            <li>You can request your review to be taken off the site. Please note that an administration fee may be charged</li>
                        </ul>
                        <br />
                        <strong>Company</strong>
                        <ul>
                            <li>We strongly recommend that you should respond to all reviews with a professional comment, whether the review is positive or negative.</li>
                            <li>If you feel that the review is offensive and abuse your rights, you should click 'Report Abuse' button.
                                <ul>
                                    <li>
                                        Add as much information as possible and submit the message
                                    </li>
                                    <li>
                                        Our moderation team would take a look onto your report
                                    </li>
                                    <li>
                                        Please remember that the review will not be taken off just because it is negative.
                                    </li>
                                </ul>
                            </li>
                            <li>
                                Companies can request for reviews to be archived, after a period of 5 years has lapsed. This does not allow companies to select which
                                reviews they would like to have archived, this applies to all reviews which exceed 5 years from publication, should an company wish
                                to request review archiving. In archiving reviews, this will affect and potentially change the overall ranking position in our rankings.</li>
                            <li>Company should not offer inducements – money or gifts – to customers to write positive reviews about your business </li>
                            <li>Companies must not pretend to be a customer and write reviews about your products or other businesses’ products – or pay others to do so</li>
                        </ul>
                            Rate Pole do not warrant the accuracy or completeness of the materials or content of reviews.
                    </div>
                      

                </div>
                <!-- END OF LEFT IMG -->

                <!-- IMG RIGHT TEXT -->
                <div class="col-md-4 cpdd02">
                    <div class="opensans grey">
                        <?php if(count($this->popularArticles)>0){ ?>
                            <h2 class="lato size18 dark bold"><?= $this->translate('Popular articles'); ?></h2><br>

                            <ul class="blogcat">
                                <?php foreach($this->popularArticles as $popularArticle): ?>
                                    <li>
                                        <a href="<?php echo $this->url(array('slug' => $popularArticle['Translation'][$this->language]['slug']), 'domain-news-article'); ?>">
                                            <?= MF_Text::truncate($popularArticle['Translation'][$this->language]['title'],40); ?>
                                        </a> 
                                        <span class="badge2 pull-right indent0"><i class="fa fa-comment"></i> <?= count($popularArticle['Comments']); ?></span></li>
                                <?php endforeach; ?>
                            </ul>
                            <br>
                        <?php } ?>
                        <?php echo $this->action('banner-sidebar2','index','banner'); ?>
                        <br /><br />


                        <!-- Nav tabs -->
                        <ul class="nav navigation-tabs3">
                            <li class="active"><a href="#tab-newtopic" data-toggle="tab"><span class="glyphicon glyphicon-star"></span> <?= $this->translate('Featured'); ?></a></li>
                            <li><a href="#tab-comments" data-toggle="tab"><span class="glyphicon glyphicon-stats"></span> <?= $this->translate('Popular'); ?> </a></li>

                        </ul>

                        <div class="tab-content4">
                            <!-- Tab 1 -->
                            <div class="tab-pane active" id="tab-newtopic">
                                <?php foreach($this->premiumAgents as $premiumAgent): ?>
                                    <div class="col-md-4">
                                        <a href="<?= $this->url(array('slug' => $premiumAgent['link']),'domain-agent-details'); ?>"><img alt="<?= $premiumAgent['name']; ?>" class="left mr20" src="<?= $premiumAgent->getLogoUrl('85x50'); ?>"></a>
                                    </div>
                                    <div class="col-md-8">
                                        <a class="dark" href="<?= $this->url(array('slug' => $premiumAgent['link']),'domain-agent-details'); ?>">
                                            <b><?= $premiumAgent['name']; ?></b></a>
                                        <br>
                                        <?= str_repeat('<img src="/images/star.png" alt="Star" />',round($premiumAgent['rating'])); ?>
                                    </div>
                                
                                    <div class="line4 clearfix mt10"></div>
                                <?php endforeach; ?>
                            </div>
                            <!-- End of Tab 1 -->

                            <!-- Tab 2 -->
                            <div class="tab-pane" id="tab-comments">
                                <?php foreach($this->popularAgents as $popularAgent): ?>
                                    <div class="col-md-4">
                                        <a href="<?= $this->url(array('slug' => $popularAgent['link']),'domain-agent-details'); ?>"><img alt="<?= $popularAgent['name']; ?>" class="left mr20" src="<?= $popularAgent->getLogoUrl('85x50'); ?>"></a>
                                    </div>
                                    <div class="col-md-8">
                                        <a class="dark" href="<?= $this->url(array('slug' => $popularAgent['link']),'domain-agent-details'); ?>">
                                            <b><?= $popularAgent['name']; ?></b></a>
                                        <br>
                                        <?= str_repeat('<img src="/images/star.png" alt="Star" />',round($popularAgent['rating'])); ?>
                                    </div>
                                
                                    <div class="line4 clearfix mt10"></div>
                                <?php endforeach; ?>
                            </div>
                            <!-- End of Tab 2 -->

                        </div>
                        
                        





                    </div>
                </div>
                <!-- END OF IMG RIGHT TEXT -->
                <div class="clearfix"></div>
                <br><br>





            </div>



            <div class="clearfix"></div><br><br>
        </div>
        <!-- END CONTENT -->			



    </div>


</div>