<?php
MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $this->translate('Advertising'), true);
echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>
<div class="container">
    <div class="container mt25 offset-0">
        <div class="col-md-12 pagecontainer2 offset-0">
            <div class="hpadding50c">
                <h1 class="lato size30 slim"><?= $this->translate('Advertising'); ?></h1>
                <p class="aboutarrow"></p>
            </div>
            <div class="line3"></div>
            <div class="hpadding50c">
                <div class="col-md-6">
                    We offer several advertising opportunities for your company.
                    <br /><br />
                    <strong>1. Advertising on other companies profile pages.</strong> Our offer contains profile pages of every company, or companies by area (eg.companies in London, companies in Yorkshire etc.).
                </div>
                </div>
                    
                <div class="col-md-6">
                    <img src="/images/reklama2.png" class="img-responsive" alt="reklama2" />
                </div>
            
                <div class="clearfix"></div>
                <br /><hr />
                <div class="clearfix"></div>
                <div class="col-md-6">
                    <strong>2. Advertising in search results.</strong> Our offer contains search results of every company or search results by area.
                </div>
                <div class="col-md-6">
                    
                    <img src="/images/reklama1.png" class="img-responsive" alt="reklama1" />
                </div>
                
                <div class="clearfix"></div>
                <br /><hr />
                <div class="clearfix"></div>
                <div class="col-md-6">
                    <strong>3. Advertising on homepage.</strong>
                </div>
                <div class="col-md-6">
                    
                    <img src="/images/reklama3.png" class="img-responsive" alt="reklama3" />
                </div>
                
                <div class="clearfix"></div>
                <br /><hr />
                <div class="clearfix"></div>
                <div class="col-md-6">
                    <strong>4. Advertising on our emails.</strong>
                </div>
                <div class="col-md-6">
                    <img src="/images/reklama4.png" class="img-responsive" alt="reklama2" />
                </div>
                
                <div class="clearfix"></div>
                <br /><hr />
                <div class="clearfix"></div>
                <div class="col-md-6">
                    <strong>5. Advertising on subpages.</strong>
                </div>
                <div class="col-md-6">
                    <img src="/images/reklama5.png" class="img-responsive" alt="reklama5" />
                </div>
                
                <div class="clearfix"></div>
                <br /><hr />
                <div class="clearfix"></div>
                <div class="col-md-12">
                   Every advertising package is available in english and polish language. Minimal advertisement duration is 2 weeks. More details available at <a href="mailto:reklama@rate-pole.com">reklama@rate-pole.com</a>
                     
                </div>
                <!-- END OF IMG RIGHT TEXT -->
                <div class="clearfix"></div>
                <br><br>
            </div>
            <div class="clearfix"></div><br><br>
        </div>
        <!-- END CONTENT -->	
    </div>
</div>
