<?php
MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $this->translate('Advertising'), true);
echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>
<div class="container">
    <div class="container mt25 offset-0">
        <div class="col-md-12 pagecontainer2 offset-0">
            <div class="hpadding50c">
                <h1 class="lato size30 slim"><?= $this->translate('Advertising'); ?></h1>
                <p class="aboutarrow"></p>
            </div>
            <div class="line3"></div>
            <div class="hpadding50c">
                Oferujemy liczne możliwości reklamowe dla Twojej firmy. Lista pakietów reklamowych znajduje się poniżej. <br /><br />
                    
                <div class="col-md-6">
                    <strong>1. Reklama na stronach innych firm.</strong><br /> W ofercie posiadamy reklamy na stronach każdej z firm, bądź na stronach firm według regionu (np. firmy w Małopolsce, firmy w Warszawie itp).
                </div>
                    
                <div class="col-md-6">
                    <img src="/images/reklama2.png" class="img-responsive" alt="reklama2" />
                </div>
                <div class="clearfix"></div>
                <br /><hr />
                <div class="clearfix"></div>
                <div class="col-md-6">
                    <strong>2. Reklama w wynikach wyszukiwania.</strong> Oferta zawiera wszystkie wyniki wyszukiwania lub wyniki wyszukiwania wg regionu.
                </div>
                <div class="col-md-6">
                    
                    <img src="/images/reklama1.png" class="img-responsive" alt="reklama1" />
                </div>
                
                <div class="clearfix"></div>
                <br /><hr />
                <div class="clearfix"></div>
                <div class="col-md-6">
                    <strong>3. Reklama na stronie główej.</strong>
                </div>
                <div class="col-md-6">
                    
                    <img src="/images/reklama3.png" class="img-responsive" alt="reklama3" />
                </div>
                
                <div class="clearfix"></div>
                <br /><hr />
                <div class="clearfix"></div>
                <div class="col-md-6">
                    <strong>4. Reklama w wysyłanych przez nas mailach.</strong>
                </div>
                <div class="col-md-6">
                    <img src="/images/reklama4.png" class="img-responsive" alt="reklama2" />
                </div>
                
                <div class="clearfix"></div>
                <br /><hr />
                <div class="clearfix"></div>
                <div class="col-md-6">
                    <strong>5. Reklama na podstronach.</strong>
                </div>
                <div class="col-md-6">
                    <img src="/images/reklama5.png" class="img-responsive" alt="reklama5" />
                </div>
                
                <div class="clearfix"></div>
                <br /><hr />
                <div class="clearfix"></div>
                <div class="col-md-12">
                    Każdy pakiet reklamowy jest dostępny w języku polskim lub angielskim. Minimalny okres reklamy to 2 tygodnie. Więcej szczegółów można uzyskać pod adresem <a href="mailto:reklama@ocen-fachowca.pl">reklama@ocen-fachowca.pl</a> lub poprzez nasz <a href="<?= $this->url(array(),'domain-contact'); ?>">formularz kontaktowy</a>
                    
                </div>
                <!-- END OF IMG RIGHT TEXT -->
                <div class="clearfix"></div>
                <br><br>
            </div>
            <div class="clearfix"></div><br><br>
        </div>
        <!-- END CONTENT -->	
    </div>
</div>
