<?php
MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $this->translate('Cookie policy'));
echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>
<div class="container">
    <div class="container mt25 offset-0">
        <div class="col-md-12 pagecontainer2 offset-0">
            <div class="hpadding50c">
                <h1 class="lato size30 slim"><?= $this->translate('Cookie policy') ?></h1>
                <p class="aboutarrow"></p>
            </div>
            <div class="line3"></div>

            <div class="hpadding50c">



                <!-- LEFT IMG -->
                <div class="col-md-8 cpdd01 grey2">
                    <div class="pl30 pr30 pb50">
                Like most websites, this one uses cookies. <br>
                Cookies are small text files stored on your computer by your browser. They're used for many things, such as remembering whether you've visited the site before, so that you remain logged in - or to help us work out how many new website visitors we get each month. They contain information about the use of your computer but don't include personal information about you (they don't store your name, for instance). <br>
                <strong>This policy explains how cookies are used on Rate-Pole.com - and, below, how you can control the cookies that may be used on this site (not all of them are used on every site). <br>
                About this Cookie policy</strong><br>
                This Cookie Policy applies to our website ("the Website"). <br>
                This Cookie Policy forms part of and is incorporated into our <a href="<?= $this->url(array(),'domain-terms-conditions'); ?>">Website Terms and Conditions</a> <br>
                By accessing the Website, you agree that this Cookie Policy will apply whenever you access the Website on any device. <br>
                Any changes to this policy will be posted here. We reserve the right to vary this Cookie Policy from time to time and such changes shall become effective as soon as they are posted. Your continued use of the Website constitutes your agreement to all such changes. <br>
                <br><strong>Our use of cookies</strong>
                We may collect information automatically when you visit the Website, using cookies. <br>
                The cookies allow us to identify your computer and find out details about your last visit. <br>
                You can choose, below, not to allow cookies. If you do, we can't guarantee that your experience with the Website will be as good as if you do allow cookies. <br>
                The information collected by cookies does not personally identify you; it includes general information about your computer settings, your connection to the Internet e.g. operating system and platform, IP address, your browsing patterns and timings of browsing on the Website and your location. <br>
                Most internet browsers accept cookies automatically, but you can change the settings of your browser to erase cookies or prevent automatic acceptance if you prefer. <br>
                Remember that if you turn off cookies in your browser then these settings apply to all websites not just this one <br>
                <ul>
                    <li>Internet Explorer <a href="http://support.microsoft.com/kb/278835">http://support.microsoft.com/kb/278835</a> (this page links to further information for different versions of IE - the mobile version is at <a href="http://www.microsoft.com/windowsphone/en-us/howto/wp7/web/changing-privacy-and-other-browser-settings.aspx)">http://www.microsoft.com/windowsphone/en-us/howto/wp7/web/changing-privacy-and-other-browser-settings.aspx)</a>.
                    </li>
                    <li>Chrome: <a target="_blank" href="http://support.google.com/chrome/bin/answer.py?hl=en-GB&amp;answer=95647">http://support.google.com/chrome/bin/answer.py?hl=en-GB&amp;answer=95647</a></li>
                    <li>Safari: <a target="_blank" href="http://docs.info.apple.com/article.html?path=Safari/5.0/en/9277.html">http://docs.info.apple.com/article.html?path=Safari/5.0/en/9277.html</a> (or
                        <a target="_blank" href="http://support.apple.com/kb/HT1677">http://support.apple.com/kb/HT1677</a>for mobile versions)</li>
                    <li>Firefox: <a target="_blank" href="http://support.mozilla.org/en-US/kb/Enabling%20and%20disabling%20cookies">http://support.mozilla.org/en-US/kb/Enabling%20and%20disabling%20cookies</a></li>
                    <li>Blackberries: <a target="_blank" href="http://docs.blackberry.com/en/smartphone_users/deliverables/32004/ Turn_off_cookies_in_the_browser_60_1072866_11.jsp">http://docs.blackberry.com/en/smartphone_users/deliverables/32004/ Turn_off_cookies_in_the_browser_60_1072866_11.jsp</a></li>
                    <li>Android: <a target="_blank" href="http://support.google.com/mobile/bin/answer.py?hl=en&amp;answer=169022">http://support.google.com/mobile/bin/answer.py?hl=en&amp;answer=169022</a></li>
                    <li>Opera: <a target="_blank" href="http://www.opera.com/browser/tutorials/security/privacy/">http://www.opera.com/browser/tutorials/security/privacy/</a></li>
                </ul>
<br>

                <strong>Types of cookie that may be used during your visit to the Website:</strong><br><br>
                The following types of cookie are used on this site. We don't list every single cookie used by name - but for each type of cookie we tell you how you can control its use.
                <ol>
                    <li>Personalisation cookies <br>These cookies are used to recognise repeat visitors to the Website and in conjunction with other information we hold to attempt to record specific browsing information (that is, about the way you arrive at the Website, pages you view, options you select, information you enter and the path you take through the Website).
                    </li>
                    <li>Analytics cookies <br>
                        These monitor how visitors move around the Website and how they reached it. This is used so that we can see total (not individual) figures on which types of content users enjoy most, for instance.<br><br>
                        You can opt out of these if you want:
                        <ul>
                        <li>Omniture: <a href="http://www.omniture.com/en/privacy/2o7#optout">http://www.omniture.com/en/privacy/2o7#optout</a></li>
                        <li>Google: <a href="https://tools.google.com/dlpage/gaoptout">https://tools.google.com/dlpage/gaoptout</a></li>
                        <li>Optimisely: <a href="https://www.optimizely.com/opt_out/">https://www.optimizely.com/opt_out/</a></li>
                        </ul>
<br>
                    </li>
                    <li>Third-party service cookies <br>
                        Social sharing, video and other services we offer are run by other companies. These companies may drop cookies on your computer when you use them on our site or if you are already logged in to them.
                        Here is a list of places where you can find out more about specific services that we may use and their use of cookies:
                        <ul>
                            <li>Facebook's data use policy: <a target="_blank" href="http://www.facebook.com/about/privacy/your-info-on-other">http://www.facebook.com/about/privacy/your-info-on-other</a></li>
                            <li>Twitter's privacy policy: <a target="_blank" href="https://twitter.com/privacy">https://twitter.com/privacy</a></li>
                            <li>YouTube video player cookie policy: <a target="_blank" href="http://www.google.com/intl/en/policies/privacy/faq/#toc-cookiesU (Google's standard terms).">http://www.google.com/intl/en/policies/privacy/faq/#toc-cookiesU</a>(Google's standard terms).</li>
                        </ul>
                    </li>
                    <li>Our own ad serving and management cookies <br>
                        We sell space on some of our websites to advertisers - they pay for the content you enjoy for free.
                        As part of this, we use several services to help us and advertisers understand what adverts you might be interested in. These cookies hold information about the computer - they don't hold personal information about you (ie it's not linked to you as an individual). But they might hold a record of what other websites you've looked at - so we could show you a car advert if you've previously visited a motoring website.
                        Please note that turning off advertising cookies won't mean that you are not served any advertising merely that it will not be tailored to your interests.
                    </li>
                    <li>Other ad management cookies <br>
                        Advertisements on the Website are provided by other organisations. Our advertising partners will serve advertisements that they believe are most likely to be of interest to you, based on information about your visit to the Website and other websites. In order to do this, our advertising partner may need to place a cookie on your computer. These cookies hold information about the computer - they don't hold personal information about you (ie it's not linked to you as an individual).
                        Please note that turning off advertising cookies won't mean that you are not served any advertising merely that it will not be tailored to your interests.
                    </li>
                    <li>Site management cookies <br>
                        These are used to maintain your identity or session on the Website. For instance, where our websites run on more than one server, we use a cookie to ensure that you are sent information by one specific server (otherwise you may log in or out unexpectedly). We may use similar cookies when you vote in opinion polls to ensure that you can only vote once, and to ensure that you can use our commenting functionality when not logged in.
                        These cookies cannot be turned off individually but you could change your browser setting to refuse all cookies (see above) if you do not wish to accept them.
                    </li>
                </ol>
                    </div>
                </div>
                <!-- END OF LEFT IMG -->

                <!-- IMG RIGHT TEXT -->
                <div class="col-md-4 cpdd02">
                    <div class="opensans grey">
                        <?php if (count($this->popularArticles) > 0) { ?>
                            <h2 class="lato size18 dark bold"><?= $this->translate('Popular articles'); ?></h2><br>

                            <ul class="blogcat">
                                <?php foreach ($this->popularArticles as $popularArticle): ?>
                                    <li>
                                        <a href="<?php echo $this->url(array('slug' => $popularArticle['Translation'][$this->language]['slug']), 'domain-news-article'); ?>">
                                            <?= MF_Text::truncate($popularArticle['Translation'][$this->language]['title'], 40); ?>
                                        </a> 
                                        <span class="badge2 pull-right indent0"><i class="fa fa-comment"></i> <?= count($popularArticle['Comments']); ?></span></li>
                                <?php endforeach; ?>
                            </ul>
                            <br>
                        <?php } ?>
                        <?php echo $this->action('banner-sidebar2', 'index', 'banner'); ?>
                        <br /><br />


                        <!-- Nav tabs -->
                        <ul class="nav navigation-tabs3">
                            <li class="active"><a href="#tab-newtopic" data-toggle="tab"><span class="glyphicon glyphicon-star"></span> <?= $this->translate('Featured'); ?></a></li>
                            <li><a href="#tab-comments" data-toggle="tab"><span class="glyphicon glyphicon-stats"></span> <?= $this->translate('Popular'); ?> </a></li>

                        </ul>

                        <div class="tab-content4">
                            <!-- Tab 1 -->
                            <div class="tab-pane active" id="tab-newtopic">
                                <?php foreach ($this->premiumAgents as $premiumAgent): ?>
                                    <div class="col-md-4">
                                        <a href="<?= $this->url(array('slug' => $premiumAgent['link']), 'domain-agent-details'); ?>"><img alt="<?= $premiumAgent['name']; ?>" class="left mr20" src="<?= $premiumAgent->getLogoUrl('85x50'); ?>"></a>
                                    </div>
                                    <div class="col-md-8">
                                        <a class="dark" href="<?= $this->url(array('slug' => $premiumAgent['link']), 'domain-agent-details'); ?>">
                                            <b><?= $premiumAgent['name']; ?></b></a>
                                        <br>
                                        <?= str_repeat('<img src="/images/star.png" alt="Star" />', round($premiumAgent['rating'])); ?>
                                    </div>

                                    <div class="line4 clearfix mt10"></div>
                                <?php endforeach; ?>
                            </div>
                            <!-- End of Tab 1 -->

                            <!-- Tab 2 -->
                            <div class="tab-pane" id="tab-comments">
                                <?php foreach ($this->popularAgents as $popularAgent): ?>
                                    <div class="col-md-4">
                                        <a href="<?= $this->url(array('slug' => $popularAgent['link']), 'domain-agent-details'); ?>"><img alt="<?= $popularAgent['name']; ?>" class="left mr20" src="<?= $popularAgent->getLogoUrl('85x50'); ?>"></a>
                                    </div>
                                    <div class="col-md-8">
                                        <a class="dark" href="<?= $this->url(array('slug' => $popularAgent['link']), 'domain-agent-details'); ?>">
                                            <b><?= $popularAgent['name']; ?></b></a>
                                        <br>
                                        <?= str_repeat('<img src="/images/star.png" alt="Star" />', round($popularAgent['rating'])); ?>
                                    </div>

                                    <div class="line4 clearfix mt10"></div>
                                <?php endforeach; ?>
                            </div>
                            <!-- End of Tab 2 -->

                        </div>







                    </div>
                </div>
                <!-- END OF IMG RIGHT TEXT -->
                <div class="clearfix"></div>
                <br><br>





            </div>



            <div class="clearfix"></div><br><br>
        </div>
        <!-- END CONTENT -->			



    </div>


</div>