<div class="modal mod fade active in" id="findSpecialist" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
            <div class="modal-content modal-lg">
    
                
                
                    <form action="<?= $this->url(array(),'domain-find-specialist'); ?>" method='POST'>
                        <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title"><?= $this->translate('Find your specialist with Rate-Pole.com'); ?></h4>
                        </div>
                        <div class="modal-body">
                            <div class="col-md-6">
                            <?php
                            echo $this->form->name;
                            echo $this->form->email;
                            echo $this->form->address;
                            echo $this->form->town;
                            echo $this->form->postcode;
                            echo $this->form->phone;
                            echo $this->form->message;
                            echo $this->form->getElement('g-recaptcha-response');
                            
                            ?>
                            </div>
                            <div class="col-md-6">
                                <?php
                                echo "1.".$this->translate('Enter your details')."<br />";
                                echo "2.".$this->translate('Tell us what kind of specialist are you looking for and of what do you want specialist to do for you.')."<br />";
                                echo "3.".$this->translate('We will contact proper specialist in your nearby area for you!')."<br />";
                                echo "<br />";

                                ?>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="modal-footer">
                                <button type="button" class="btn btn-default left" data-dismiss="modal"><?= $this->translate('Close'); ?></button>
                                <button type="submit" id="Valuation_Submit" class="btn btn-info"><?= $this->translate('Send message'); ?></button>
                        </div>
                    </form>
            </div>
            <!-- /.modal-content -->
    </div>
<!-- /.modal-dialog -->
</div>
