<?php
MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $this->translate('Premium Package'));
echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>
<div class="container">
    <div class="container mt25 offset-0">
        <div class="col-md-12 pagecontainer2 offset-0">
            <div class="hpadding50c">
                <h1 class="lato size30 slim"><?= $this->translate('Premium Package') ?></h1>
                <p class="aboutarrow"></p>
            </div>
            <div class="line3"></div>

            <div class="hpadding50c">
                <!-- LEFT IMG -->
                <div class="col-md-8 cpdd01 grey2">


                    <div class="pl30 pr30 pb50">
                        Oceń-Fachowca.pl daje Twojej firmie możliwość skorzystania z naszego pakietu Premium. Sprawdź poniżej co zyskujesz korzystając z pakietu Premium. <br /><br />
                        1. <strong>Reklama firmy podązająca za Tobą na całej stronie.</strong> Każda osoba odwiedzająca Twój profil zobaczy Twoje logo i reklame. Taki profil zdecydowanie bardziej przyciąga wzrok i może zachęcić daną osobę do
                         skorzystania z usług Twojej firmy. Dodatkowo, w każdym miejscu na stronie, w którym pojawi się nazwa Twojej firmy, Twoje logo pojawi się razem z nią.
                        <br /><br /><strong>Nie masz swojego loga lub reklamy?</strong> Nie martw się! Jako członek pakietu Premium stworzymy reklame i logo specjalnie dla Ciebie!<br /><br />
                        2. <strong>Wyświetlanie na czołowych miejscach w wynikach wyszukiwania.</strong> Każda osoba wyszukująca firmy w Twoim regionie lub kategorii zobaczy Twoją firmę na szczycie wyników wyszukiwania. <br /><br />
                        3. <strong>Firma przypisana do 3 kategorii</strong> Twoja firma może oferować usługi, które pasują w wiele kategorii. Firmy posiadające standardowe konto mogą wybrać tylko 1 kategorie.
                        Dla członków pakietu Premium oferujemy możliwość wyboru do 3 kategorii. W ten sposób Twoja firma pojawi się na szczycie większej ilości wyników wyszukiwania.
                        <br /><br />
                        4. <strong>Natychmiastowe wsparcie.</strong> Posiadając konto premium, otrzymujesz bezpośredni adres email do naszego zespołu wsparcia. Twojej prośbie zostanie nadany najwyższy priorytet, nasz zespół
                        odpowie na nią najszybciej jak to możliwe. Prośby firm nie będących członkami pakietu Premium mogą zająć do 48 godzin na odpowiedź. 
                        <br /><br />
                        5. <strong>Zapytania od klientów</strong> Otrzymujemy na naszą stronę zapytania od klientów przez nasz formularz 'znajdź Twojego fachowca'. Zapytania w Twojej okolicy, które wpisują się w działalność Twojej firmy
                        zostaną przesłane do Twojej firmy. Te osoby moga zostać Twoimi nowymi klientami!
                        <br /><br />
                        Aby zamówić pakiet Premium dla Twojej firmy, wyślij maila na adres <a href='premium@ocen-fachowca.pl'>premium@ocen-fachowca.pl</a> bądź napisz do nas przez <a href='<?= $this->url(array(), 'domain-contact'); ?>'>formularz kontaktowy</a>.
                    </div>
                </div>
                <!-- END OF LEFT IMG -->

                <!-- IMG RIGHT TEXT -->
                <div class="col-md-4 cpdd02">
                    <div class="opensans grey">
                        <?php if (count($this->popularArticles) > 0) { ?>
                            <h2 class="lato size18 dark bold"><?= $this->translate('Popular articles'); ?></h2><br>

                            <ul class="blogcat">
                                <?php foreach ($this->popularArticles as $popularArticle): ?>
                                    <li>
                                        <a href="<?php echo $this->url(array('slug' => $popularArticle['Translation'][$this->language]['slug']), 'domain-news-article'); ?>">
                                            <?= MF_Text::truncate($popularArticle['Translation'][$this->language]['title'], 40); ?>
                                        </a> 
                                        <span class="badge2 pull-right indent0"><i class="fa fa-comment"></i> <?= count($popularArticle['Comments']); ?></span></li>
                                <?php endforeach; ?>
                            </ul>
                            <br>
                        <?php } ?>
                        <?php echo $this->action('banner-sidebar2', 'index', 'banner'); ?>
                        <br /><br />


                        <!-- Nav tabs -->
                        <ul class="nav navigation-tabs3">
                            <li class="active"><a href="#tab-newtopic" data-toggle="tab"><span class="glyphicon glyphicon-star"></span> <?= $this->translate('Featured'); ?></a></li>
                            <li><a href="#tab-comments" data-toggle="tab"><span class="glyphicon glyphicon-stats"></span> <?= $this->translate('Popular'); ?> </a></li>

                        </ul>

                        <div class="tab-content4">
                            <!-- Tab 1 -->
                            <div class="tab-pane active" id="tab-newtopic">
                                <?php foreach ($this->premiumAgents as $premiumAgent): ?>
                                    <div class="col-md-4">
                                        <a href="<?= $this->url(array('slug' => $premiumAgent['link']), 'domain-agent-details'); ?>"><img alt="<?= $premiumAgent['name']; ?>" class="left mr20" src="<?= $premiumAgent->getLogoUrl('85x50'); ?>"></a>
                                    </div>
                                    <div class="col-md-8">
                                        <a class="dark" href="<?= $this->url(array('slug' => $premiumAgent['link']), 'domain-agent-details'); ?>">
                                            <b><?= $premiumAgent['name']; ?></b></a>
                                        <br>
                                        <?= str_repeat('<img src="/images/star.png" alt="Star" />', round($premiumAgent['rating'])); ?>
                                    </div>

                                    <div class="line4 clearfix mt10"></div>
                                <?php endforeach; ?>
                            </div>
                            <!-- End of Tab 1 -->

                            <!-- Tab 2 -->
                            <div class="tab-pane" id="tab-comments">
                                <?php foreach ($this->popularAgents as $popularAgent): ?>
                                    <div class="col-md-4">
                                        <a href="<?= $this->url(array('slug' => $popularAgent['link']), 'domain-agent-details'); ?>"><img alt="<?= $popularAgent['name']; ?>" class="left mr20" src="<?= $popularAgent->getLogoUrl('85x50'); ?>"></a>
                                    </div>
                                    <div class="col-md-8">
                                        <a class="dark" href="<?= $this->url(array('slug' => $popularAgent['link']), 'domain-agent-details'); ?>">
                                            <b><?= $popularAgent['name']; ?></b></a>
                                        <br>
                                        <?= str_repeat('<img src="/images/star.png" alt="Star" />', round($popularAgent['rating'])); ?>
                                    </div>

                                    <div class="line4 clearfix mt10"></div>
                                <?php endforeach; ?>
                            </div>
                            <!-- End of Tab 2 -->

                        </div>
                    </div>
                </div>
                <!-- END OF IMG RIGHT TEXT -->
                <div class="clearfix"></div>
            </div>



            <div class="clearfix"></div>
        </div>
        <!-- END CONTENT -->	

    </div>

</div>