<?php
MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $this->translate('Privacy policy'));
echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>
<div class="container">
    <div class="container mt25 offset-0">
        <div class="col-md-12 pagecontainer2 offset-0">
            <div class="hpadding50c">
                <h1 class="lato size30 slim"><?= $this->translate('Privacy policy') ?></h1>
                <p class="aboutarrow"></p>
            </div>
            <div class="line3"></div>

            <div class="hpadding50c">



                <!-- LEFT IMG -->
                <div class="col-md-8 cpdd01 grey2">
                    <div class="pl30 pr30 pb50">
                        <strong>Our commitment to you</strong>
                        <p>This website (Rate-Pole.com) is provided by Kardimobile Ltd, with registered address at registered office address: 52 Landressy Place, Glasgow G40 1HF.</p>
                        <p>Rate-Pole.com respects your privacy and is committed to protecting personal information collected from you through our website. This privacy policy governs the way we collect and use information, and by using the services on our website ('Services') you agree to be bound by this policy. All references within this policy to 'we/us/our' refer to Kardimobile Ltd</p>
                        <strong>Information we collect</strong>
                        <p>When you use the Services you will have the option to provide us with personal information, such as your email address, so that we may keep you informed.</p>
                        <p>When visiting our website, we may place one or more cookies (a small file that is stored by your browser to recognise you and store your preferences) on your computer. This helps us to improve our Services by personalising information you may want. You may adjust the settings on your browser to refuse cookies but some of the Services may not work if you do so. We may also log information from your computer including the existence of cookies, your IP address and information about your browser program in order to allow us to diagnose problems, administer and track your usage of the Services.
                            <a href="<?= $this->url(array(),'domain-cookie-policy'); ?>">View our Cookie Policy</a>
                        </p>
                        <strong>Master data</strong>
                        <p>When you create a profile on the Website, we collect the following master data: Your username, your password and your email address. The purpose of the collection of this information is to identify you as a user when you log on to the Website.</p>
                        <strong>Reviews</strong>
                        <p>When you make a review of a company, we collect the information you state in the review, including which company you review, which service(s) the review concerns, and how you evaluate the company.</p>
                        <strong>IP addresses and browser settings</strong>
                        <p>When visiting the Website, the IP address and the browser settings of your computer are registered. The IP address is the numerical address of the computer used when visiting the Website. Browser settings are e.g. the type of browser you use, browser language, time zone etc. The IP address and browser settings are registered to enable us to trace the used computer in case of misuse or unlawful actions in connection with the visit on or use of the Website. Further, the IP address is used to derive your approximate location (city level).</p>
                        <strong>Newsletter</strong>
                        <p>If you sign up for Rate-Pole's newsletters, Rate-Pole.com register the information supplied by you (e.g. your name, email address etc.).</p>
                        <p>We will not hand out our mailing list to third parties.</p>
                        <p>If you no longer wish to receive newsletters from Rate-Pole.com, you may opt out of such communications by following the instructions at the bottom of any of our emails.</p>
                        <strong>How we use information</strong>
                        <p>We use the information we collect to provide the Services and to communicate with you. We will only share your personal information outside our group in the following circumstances:</p>
                        <ul>
                            <li>When you have consented or directed us to share the information.</li>
                            <li>With service providers or affiliate companies who perform services on our behalf.</li>
                            <li>In order to satisfy any requirement under applicable law, regulation or legal process. Or to protect our rights or prevent any concerns relating to fraud or security.</li>
                            <li>In the event of a merger or sale of all or part of our business whereby personal information may be transferred as an asset of the business.</li>
                            <li>to keep you informed about us and our services about this website;</li>
                            <li>We collect IP addresses and computer hostnames from users leaving reviews and submitting information. This is done for the purposes of moderating the site only.</li>
                            <li>We may share with third parties aggregate information or information that does not personally identify you.</li>
                        </ul>
                        <strong>Accessing and updating your personal information</strong>
                        <p>Whenever you use our services, we aim to provide you with access to your personal information. If that information is wrong, we strive to give you ways to update or amend it quickly - unless we have to keep that information for legitimate business or legal purposes. When updating your personal information, we may ask you to verify your identity before we can act on your request.</p>
                        <p>We may reject requests that are unreasonably repetitive, require disproportionate technical effort (for example, developing a new system or fundamentally changing an existing practice), risk the privacy of others, or would be extremely impractical (for instance, requests concerning information residing on backup systems).</p>
                        <p>We aim to maintain our services in a manner that protects information from accidental or malicious destruction. Because of this, after you delete information from our services, we may not immediately delete residual copies from our active servers and may not remove information from our backup systems.</p>
                        <strong>Third parties</strong>
                        <p>We use third parties to serve advertisements on our website and these third parties may use parties or other means to help measure the effectiveness of their advertisements. Our website may also include links to other unrelated websites and/or contact forms to other unrelated parties which may collect personal information. Our privacy policy does not extend to these third parties or other websites and we recommend that users refer directly to these parties regarding their privacy policies before supplying personal details to these companies. <a href="<?= $this->url(array(),'domain-cookie-policy'); ?>">View our Cookie Policy</a></p>
                        <p>We may use your Personal Information to customise or enhance your experience on the Rate-Pole.com (including the display of advertisements) and communications related to our products or services or those of third parties. In addition, we may share other information we may have about you and your use of the Rate-Pole.com (such as which pages you have visited) with third parties for those purposes and for the purpose of facilitating the serving of targeted ads for the Rate-Pole.com on other Web sites.</p>
                        <strong>Safety and security</strong>
                        <p>Personal information is processed and stored in our databases and we have taken reasonable steps to secure and protect the information under our control, including establishing processes to prevent unauthorized access or disclosure of this information. However, whilst we make every effort to ensure the security of your information, we are unable to guarantee the protection of the information from misuse, accidental disclosure or unauthorised acts by others. Information provided by you may be stored or processed outside the United Kingdom.</p>
                        <strong>Changes to Privacy Policy</strong>
                        <p>We reserve the right to change this privacy policy at any time without prior notice to you. Any changes will be posted on our website and become effective at the time of posting. In the event that material changes are made that affect the use or disclosure of your personal information, we will make reasonable efforts to notify you of these changes.</p>

                    </div>
                </div>
                <!-- END OF LEFT IMG -->

                <!-- IMG RIGHT TEXT -->
                <div class="col-md-4 cpdd02">
                    <div class="opensans grey">
                        <?php if (count($this->popularArticles) > 0) { ?>
                            <h2 class="lato size18 dark bold"><?= $this->translate('Popular articles'); ?></h2><br>

                            <ul class="blogcat">
                                <?php foreach ($this->popularArticles as $popularArticle): ?>
                                    <li>
                                        <a href="<?php echo $this->url(array('slug' => $popularArticle['Translation'][$this->language]['slug']), 'domain-news-article'); ?>">
                                            <?= MF_Text::truncate($popularArticle['Translation'][$this->language]['title'], 40); ?>
                                        </a> 
                                        <span class="badge2 pull-right indent0"><i class="fa fa-comment"></i> <?= count($popularArticle['Comments']); ?></span></li>
                                <?php endforeach; ?>
                            </ul>
                            <br>
                        <?php } ?>
                        <?php echo $this->action('banner-sidebar2', 'index', 'banner'); ?>
                        <br /><br />


                        <!-- Nav tabs -->
                        <ul class="nav navigation-tabs3">
                            <li class="active"><a href="#tab-newtopic" data-toggle="tab"><span class="glyphicon glyphicon-star"></span> <?= $this->translate('Featured'); ?></a></li>
                            <li><a href="#tab-comments" data-toggle="tab"><span class="glyphicon glyphicon-stats"></span> <?= $this->translate('Popular'); ?> </a></li>

                        </ul>

                        <div class="tab-content4">
                            <!-- Tab 1 -->
                            <div class="tab-pane active" id="tab-newtopic">
                                <?php foreach ($this->premiumAgents as $premiumAgent): ?>
                                    <div class="col-md-4">
                                        <a href="<?= $this->url(array('slug' => $premiumAgent['link']), 'domain-agent-details'); ?>"><img alt="<?= $premiumAgent['name']; ?>" class="left mr20" src="<?= $premiumAgent->getLogoUrl('85x50'); ?>"></a>
                                    </div>
                                    <div class="col-md-8">
                                        <a class="dark" href="<?= $this->url(array('slug' => $premiumAgent['link']), 'domain-agent-details'); ?>">
                                            <b><?= $premiumAgent['name']; ?></b></a>
                                        <br>
                                        <?= str_repeat('<img src="/images/star.png" alt="Star" />', round($premiumAgent['rating'])); ?>
                                    </div>

                                    <div class="line4 clearfix mt10"></div>
                                <?php endforeach; ?>
                            </div>
                            <!-- End of Tab 1 -->

                            <!-- Tab 2 -->
                            <div class="tab-pane" id="tab-comments">
                                <?php foreach ($this->popularAgents as $popularAgent): ?>
                                    <div class="col-md-4">
                                        <a href="<?= $this->url(array('slug' => $popularAgent['link']), 'domain-agent-details'); ?>"><img alt="<?= $popularAgent['name']; ?>" class="left mr20" src="<?= $popularAgent->getLogoUrl('85x50'); ?>"></a>
                                    </div>
                                    <div class="col-md-8">
                                        <a class="dark" href="<?= $this->url(array('slug' => $popularAgent['link']), 'domain-agent-details'); ?>">
                                            <b><?= $popularAgent['name']; ?></b></a>
                                        <br>
                                        <?= str_repeat('<img src="/images/star.png" alt="Star" />', round($popularAgent['rating'])); ?>
                                    </div>

                                    <div class="line4 clearfix mt10"></div>
                                <?php endforeach; ?>
                            </div>
                            <!-- End of Tab 2 -->

                        </div>







                    </div>
                </div>
                <!-- END OF IMG RIGHT TEXT -->
                <div class="clearfix"></div>
                <br><br>





            </div>



            <div class="clearfix"></div><br><br>
        </div>
        <!-- END CONTENT -->			



    </div>


</div>