<?php
MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $this->translate('Privacy policy'));
echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>
<div class="container">
    <div class="container mt25 offset-0">
        <div class="col-md-12 pagecontainer2 offset-0">
            <div class="hpadding50c">
                <h1 class="lato size30 slim"><?= $this->translate('Privacy policy') ?></h1>
                <p class="aboutarrow"></p>
            </div>
            <div class="line3"></div>

            <div class="hpadding50c">



                <!-- LEFT IMG -->
                <div class="col-md-8 cpdd01 grey2">
                    <div class="pl30 pr30 pb50">
                        <strong>Nasze zobowiązania wobec Ciebie</strong>
                        <p>Ta strona internetowa (Oceń-Fachowca.pl) jest stworzona przez Kardimobile Ltd, zarejestrowaną pod adresem: 52 Landressy Place, Glasgow G40 1HF.</p>
                        <p>Oceń-Fachowca.pl szanuje Twoją prywatnośc i zobowiązuje się chronić dane pobierane od Ciebie przez stronę internetową.
                            Niniejsza polityka prywatności reguluje sposób możemy zbierać i wykorzystywać informacje, i korzystając z usług na naszej stronie internetowej ( "Usługi"), zgadzasz się przestrzegać tej zasady.
                            Wszystkie odniesienia tej polityki słowami "my / nas / Nasze" odnoszą się do Kardimobile Ltd</p>
                        <strong>Informacje, które gromadzimy</strong>
                        <p>Podczas korzystania z Usług będziesz miał możliwość zapewnić nam swoje dane osobowe takie jak adres email, aby informować Cię o wszelkich zmianach na stronie.</p>
                        <p>Odwiedzając naszą stronę internetową, możemy umieścić jeden lub więcej plików cookie (małe pliki, które są przechowywane przez przeglądarkę w celu rozpoznawania Ciebie i przechowywania Twoich preferencji) na komputerze. To pomaga nam poprawić jakość naszych usług przez personalizacje informacji, których szukasz. Możesz zmienić ustawienia w przeglądarce aby odmówić wysyłania ciasteczek, ale jeśli to zrobisz niektóre usługi mogą przestać działać. Możemy również rejestrować dane z komputera takie jak istnienie cookie, adres IP oraz informacje o programie swojej przeglądarki w celu umożliwienia nam diagnozowania problemów, zarządzać i śledzić korzystania z Usług.</p>
                        <p>
                            Odwiedzając naszą stronę internetową, możemy umieścić jeden lub więcej plików cookie (małe pliki, które są przechowywane przez przeglądarkę w celu rozpoznawania Ciebie i przechowywania Twoich preferencji) na komputerze. To pomaga nam poprawić jakość naszych usług przez personalizacje informacji, których szukasz. Możesz zmienić ustawienia w przeglądarce aby odmówić wysyłania ciasteczek, ale jeśli to zrobisz niektóre usługi mogą przestać działać. Możemy również rejestrować dane z komputera takie jak istnienie cookie, adres IP oraz informacje o programie swojej przeglądarki w celu umożliwienia nam diagnozowania problemów, zarządzać i śledzić korzystania z Usług.
                            <a href="<?= $this->url(array(),'domain-cookie-policy'); ?>">Polityka cookies</a>
                        </p>
                        <strong>Podstawowe dane</strong>
                        <p>Podczas tworzenia profilu na stronie internetowej, zbieramy następujące dane podstawowe: Twoja nazwa użytkownika, hasło i adres e-mail. Celem zbierania tych informacji jest do identyfikacji użytkownika jako użytkownik po zalogowaniu się na stronie internetowej.</p>
                        <strong>Opinie</strong>
                        <p>
                            Kiedy dodajesz opinie o firmie, zbieramy informacje, które podajesz takie jak nazwa ocenianej firmy, usługi jakie świadczy firma czy Twoja ocena danej firmy.</p>
                        <strong>Adresy IP oraz ustawienia przeglądarki</strong>
                        <p>Odwiedzając stronę internetową, Twój adres IP oraz ustawienia przeglądarki na komputerze zostają zarejestrowane. Adres IP to numeryczny adres komputera używanego podczas odwiedzania strony internetowej. Ustawienia przeglądarki to np rodzaj używanej przeglądarki, język przeglądarki, strefa czasowa itd. Ustawienia adresu IP i przeglądarki są rejestrowane, aby umożliwić nam śledzenia używanego komputera w przypadku niewłaściwego stosowania lub działań niezgodnych z prawem w związku z wizytą na lub korzystania z Strona internetowa. Ponadto, adres IP jest używany w celu uzyskania przybliżonej lokalizacji (na poziomie miasta).</p>
                        <strong>Newsletter</strong>
                        <p>Jeżeli zapiszesz się do Newslettera Oceń-Fachowca.pl, Oceń-Fachowca.pl rejestruje informacje podane przez Ciebie (np. imie, adres email).</p>
                        <p>Twój adres email nie zostanie przekazany stronom trzecim.</p>
                        <p>Jeżeli nie chcesz otrzymywać newslettera z Oceń-Fachowca.pl, możesz w każdej chwili wypisać się klikając w link znajdujący się na dole otrzymanego emaila.</p>
                        <strong>Do czego wykorzystujemy informacje</strong>
                        <p>Używamy zebrane informacje do świadczenia Usług oraz do komunikowania się z Tobą. Będziemy udostępniać Twoje dane osobowe poza naszą firmą TYLKO w następujących okolicznościach:</p>
                        <ul>
                            <li>Gdy udzieliłeś nam stosownej zgody na dzielenie się Twoimi informacjami.</li>
                            <li>Z usługodawcami, które wykonują usługi w naszym imieniu.</li>
                            <li>Aby spełnić wszelkie wymogi zgodnie z obowiązującymi przepisami prawa, regulacji lub procedur prawnych. Także w celu ochrony naszych praw lub aby uniemożliwić jakiekolwiek obawy związane z oszustwem lub bezpieczeństwa.</li>
                            <li>W przypadku fuzji lub sprzedaży firmy, zgodnie z którą dane osobowe mogą byćprzekazane jako składnik aktywów przedsiębiorstwa.</li>
                            <li>Aby informować Cię o naszej działalnosci i Usługach</li>
                            <li>Gromadzimy adresy IP i nazwy hostów komputerów przez użytkowników dodających opinie. Te informacje są wykorzystywane w celach moderacyjnych.</li>
                            <li>Możemy udostępniać stronom trzecim zbiorcze informacje lub informacje, które nie umożliwiają identyfikacji użytkownika.</li>
                        </ul>
                        <strong>Uzyskiwanie dostępu i aktualizacja Twoich danych osobowych</strong>
                        <p>Zawsze przy korzystaniu z naszych usług, staramy się zapewnić Państwu dostęp do swoich danych osobowych. Jeżeli informacje te są błędne, staramy się dać sposoby aktualizacji lub szybkiej zmiany - chyba że musimy zachować tę informację dla legalnej działalności lub do celów prawnych. Podczas aktualizowania Twoich danych osobowych, możemy poprosić o zweryfikowanie tożsamości przed możliwością działania na Twoje zlecenie.</p>
                        <p>Możemy odmówić żadania aktualizacji, które jest nieracjonalnie powtarzalne, wymaga niewspółmiernych wysiłków technicznych, narusza prywatność innych lub będzie wyjątkowo niepraktyczne.</p>
                        <p>Naszym celem jest świadczenie naszych usług w sposób, który chroni dane przed przypadkowym lub celowym zniszczeniem. Z tego powodu, po usunięciu żądanych informacji , dane te mogą pozostać zachowane w kopiach zapasowych naszych serwerów.</p>
                        <strong>Osoby trzecie</strong>
                        <p>Korzystamy z usług firm zewnetrznych do wyświetlania reklam na naszej stronie. Te firmy zewnętrzne mogą korzystać z oprogramowania do mierzenia efektywności ich reklam. Nasza strona może także zawierać linki do innych stron ,niepowiązanych z naszą stroną. 
                            Nasza polityka prywatności nie obejmuje tych stron trzecich lub innych stron i zaleca, aby użytkownicy odnoszą się bezpośrednio do tych podmiotów w zakresie ich polityki prywatności przed dostarczeniem danych osobowych do tych spółek. </p>
                        <p>Możemy wykorzystywać dane użytkownika w celu dostosowania lub ulepszyć Twoje doświadczenie z Oceń-Fachowca.pl (łącznie z wyświetlaniem reklam) i do komunikacji w celu polepszenia naszych Usług bądź usług firm zewnętrznych. 
                            Dodatkowo, możemy dzielić się posiadanymi przez nas informacjami o Tobie i korzystaniu z Oceń-Fachowca.pl (np. które strony odwiedziłeś) z firmami zewnętrznymi w w/w celach</p>
                        <strong>Bezpieczeństwo i ochrona</strong>
                        <p>Personal information is processed and stored in our databases and we have taken reasonable steps to secure and protect the information under our control, including establishing processes to prevent unauthorized access or disclosure of this information. However, whilst we make every effort to ensure the security of your information, we are unable to guarantee the protection of the information from misuse, accidental disclosure or unauthorised acts by others. Information provided by you may be stored or processed outside the United Kingdom.</p>
                        <P>Dane osobowe są przetwarzane i przechowywane w naszych bazach danych. Podjęliśmy stosowne kroki w celu zabezpieczenia i ochrony informacji pod naszą kontrolą, w tym ustanowienia procesów, aby zapobiec nieautoryzowanemu dostępowi lub ujawnieniu tych informacji. Jednak mimo, że dokładamy wszelkich starań, aby zapewnić bezpieczeństwo informacji, nie jesteśmy w stanie zagwarantować ochrony informacji wynikłego niewłaściwego użytkowania, przypadkowego ujawniania lub niedozwolonej czynności przez innych. Informacje dostarczone przez użytkownika mogą być przechowywane lub przetwarzane poza granicami Rzeczypospolitej Polskiej. </p>
                        <strong>Zmiany w Polityce Prywatności</strong>
                        <p>Zastrzegamy sobie prawo zmiany powyższej polityki prywatności w dowolnym czasie bez uprzedniego powiadomienia. Wszelkie zmiany będą publikowane na naszej stronie internetowej i stają się skuteczne w chwili nadania. W przypadku, gdy istotne zmiany są dokonywane, które wpływają na wykorzystanie lub ujawnienie danych osobowych, dołożymy uzasadnionych starań, aby powiadomić o tych zmianach.</p>

                    </div>
                </div>
                <!-- END OF LEFT IMG -->

                <!-- IMG RIGHT TEXT -->
                <div class="col-md-4 cpdd02">
                    <div class="opensans grey">
                        <?php if (count($this->popularArticles) > 0) { ?>
                            <h2 class="lato size18 dark bold"><?= $this->translate('Popular articles'); ?></h2><br>

                            <ul class="blogcat">
                                <?php foreach ($this->popularArticles as $popularArticle): ?>
                                    <li>
                                        <a href="<?php echo $this->url(array('slug' => $popularArticle['Translation'][$this->language]['slug']), 'domain-news-article'); ?>">
                                            <?= MF_Text::truncate($popularArticle['Translation'][$this->language]['title'], 40); ?>
                                        </a> 
                                        <span class="badge2 pull-right indent0"><i class="fa fa-comment"></i> <?= count($popularArticle['Comments']); ?></span></li>
                                <?php endforeach; ?>
                            </ul>
                            <br>
                        <?php } ?>
                        <?php echo $this->action('banner-sidebar2', 'index', 'banner'); ?>
                        <br /><br />


                        <!-- Nav tabs -->
                        <ul class="nav navigation-tabs3">
                            <li class="active"><a href="#tab-newtopic" data-toggle="tab"><span class="glyphicon glyphicon-star"></span> <?= $this->translate('Featured'); ?></a></li>
                            <li><a href="#tab-comments" data-toggle="tab"><span class="glyphicon glyphicon-stats"></span> <?= $this->translate('Popular'); ?> </a></li>

                        </ul>

                        <div class="tab-content4">
                            <!-- Tab 1 -->
                            <div class="tab-pane active" id="tab-newtopic">
                                <?php foreach ($this->premiumAgents as $premiumAgent): ?>
                                    <div class="col-md-4">
                                        <a href="<?= $this->url(array('slug' => $premiumAgent['link']), 'domain-agent-details'); ?>"><img alt="<?= $premiumAgent['name']; ?>" class="left mr20" src="<?= $premiumAgent->getLogoUrl('85x50'); ?>"></a>
                                    </div>
                                    <div class="col-md-8">
                                        <a class="dark" href="<?= $this->url(array('slug' => $premiumAgent['link']), 'domain-agent-details'); ?>">
                                            <b><?= $premiumAgent['name']; ?></b></a>
                                        <br>
                                        <?= str_repeat('<img src="/images/star.png" alt="Star" />', round($premiumAgent['rating'])); ?>
                                    </div>

                                    <div class="line4 clearfix mt10"></div>
                                <?php endforeach; ?>
                            </div>
                            <!-- End of Tab 1 -->

                            <!-- Tab 2 -->
                            <div class="tab-pane" id="tab-comments">
                                <?php foreach ($this->popularAgents as $popularAgent): ?>
                                    <div class="col-md-4">
                                        <a href="<?= $this->url(array('slug' => $popularAgent['link']), 'domain-agent-details'); ?>"><img alt="<?= $popularAgent['name']; ?>" class="left mr20" src="<?= $popularAgent->getLogoUrl('85x50'); ?>"></a>
                                    </div>
                                    <div class="col-md-8">
                                        <a class="dark" href="<?= $this->url(array('slug' => $popularAgent['link']), 'domain-agent-details'); ?>">
                                            <b><?= $popularAgent['name']; ?></b></a>
                                        <br>
                                        <?= str_repeat('<img src="/images/star.png" alt="Star" />', round($popularAgent['rating'])); ?>
                                    </div>

                                    <div class="line4 clearfix mt10"></div>
                                <?php endforeach; ?>
                            </div>
                            <!-- End of Tab 2 -->

                        </div>







                    </div>
                </div>
                <!-- END OF IMG RIGHT TEXT -->
                <div class="clearfix"></div>
                <br><br>





            </div>



            <div class="clearfix"></div><br><br>
        </div>
        <!-- END CONTENT -->			



    </div>


</div>