<!--
        #################################
                - THEMEPUNCH BANNER -
        #################################
-->
<div id="dajy" class="fullscreen-container mtslide sliderbg fixed">
    <div class="fullscreenbanner">
        <ul>

            <!-- papercut fade turnoff flyin slideright slideleft slideup slidedown-->

            <!-- FADE -->
            <li data-transition="fade" data-slotamount="1" data-masterspeed="300"> 										
                <img src="/images/trophy2.jpg" alt="
                <?php
                echo $this->translate('Best company of') . " ";
                if ($this->language == 'pl') {
                    echo MF_Text::polishMonthFromNo($this->bestAgent['month']);
                } else {
                    $dt = DateTime::createFromFormat('!m', $this->bestAgent['month']);
                    echo $dt->format('F');
                }
                ?>
                     "/>
                <div class="tp-caption scrolleffect sft"
                     data-x="center"
                     data-y="120"
                     data-speed="1000"
                     data-start="800"
                     data-easing="easeOutExpo"  >
                    <div class="sboxpurple textcenter">
                        <span class="lato size28 slim caps white">
                            <?php
                            echo $this->translate('Best company of') . " ";
                            if ($this->language == 'pl') {
                                echo MF_Text::polishMonthFromNo($this->bestAgent['month']);
                            } else {
                                $dt = DateTime::createFromFormat('!m', $this->bestAgent['month']);
                                echo $dt->format('F');
                            }
                            ?>
                        </span><br />
                        <span class="lato size100 slim caps white">
                            <a class='bestFirmOfTheMonth' href='<?= $this->url(array('slug' => $this->bestAgent['Agent']['link']), 'domain-agent-details'); ?>'><?= $this->bestAgent['Agent']['name']; ?></a>
                        </span><br/>
                        <span class="lato size48 slim uppercase yellow">
                            <?= MF_Text::showStars($this->bestAgent['Agent']['rating'], 'big'); ?>
                        </span><br/>
                    </div>
                </div>	
            </li>
            <li data-transition="fade" data-slotamount="1" data-masterspeed="300">
                <img src="/images/find-your-specialist.jpg" alt="<?= $this->translate('Find your specialist!'); ?>"/>
                <div class="tp-caption scrolleffect sft"
                     data-x="center"
                     data-y="120"
                     data-speed="1000"
                     data-start="800"
                     data-easing="easeOutExpo"  >
                    <div class="sboxpurple textcenter padding20 pt40 slidersepia" >
                        <span class="lato size65 slim caps white">
                            <a data-toggle="modal" data-target="#findSpecialist" href='javascript:void(0)'>
                            <?php
                            echo $this->translate('Find your specialist!') . " ";
                            ?>
                            </a>
                        </span><br /><br /><br /><br />
                        <span class="lato size48 slim caps yellowgreen">
                            
                            <a data-toggle="modal" data-target="#findSpecialist" href='javascript:void(0)'>
                            <?= $this->translate('Tell us what you want to do.'); ?>
                            </a>
                        </span><br/><br /><br />
                        <span class="lato size28 white slim uppercase">
                            <a data-toggle="modal" data-target="#findSpecialist" href='javascript:void(0)'>
                            <?= $this->translate('We will contact proper specialist in your nearby area for you!'); ?>
                            </a>
                        </span>
                    </div>
                </div>
            </li>

        </ul>
        <div class="tp-bannertimer none"></div>
    </div>
</div>

<!--
##############################
 - ACTIVATE THE BANNER HERE -
##############################
-->
<script type="text/javascript">

    $(document).ready(function () {



        $('.fullscreenbanner').revolution(
                {
                    delay: 9000,
                    startwidth: 1920,
                    startheight: 600,
                    onHoverStop: "on", // Stop Banner Timet at Hover on Slide on/off

                    thumbWidth: 100, // Thumb With and Height and Amount (only if navigation Tyope set to thumb !)
                    thumbHeight: 50,
                    thumbAmount: 3,
                    hideThumbs: 0,
                    navigationType: "bullet", // bullet, thumb, none
                    navigationArrows: "solo", // nexttobullets, solo (old name verticalcentered), none

                    navigationStyle: false, // round,square,navbar,round-old,square-old,navbar-old, or any from the list in the docu (choose between 50+ different item), custom


                    navigationHAlign: "left", // Vertical Align top,center,bottom
                    navigationVAlign: "bottom", // Horizontal Align left,center,right
                    navigationHOffset: 30,
                    navigationVOffset: 30,
                    soloArrowLeftHalign: "left",
                    soloArrowLeftValign: "center",
                    soloArrowLeftHOffset: 20,
                    soloArrowLeftVOffset: 0,
                    soloArrowRightHalign: "right",
                    soloArrowRightValign: "center",
                    soloArrowRightHOffset: 20,
                    soloArrowRightVOffset: 0,
                    touchenabled: "on", // Enable Swipe Function : on/off


                    stopAtSlide: -1, // Stop Timer if Slide "x" has been Reached. If stopAfterLoops set to 0, then it stops already in the first Loop at slide X which defined. -1 means do not stop at any slide. stopAfterLoops has no sinn in this case.
                    stopAfterLoops: -1, // Stop Timer if All slides has been played "x" times. IT will stop at THe slide which is defined via stopAtSlide:x, if set to -1 slide never stop automatic

                    hideCaptionAtLimit: 0, // It Defines if a caption should be shown under a Screen Resolution ( Basod on The Width of Browser)
                    hideAllCaptionAtLilmit: 0, // Hide all The Captions if Width of Browser is less then this value
                    hideSliderAtLimit: 0, // Hide the whole slider, and stop also functions if Width of Browser is less than this value


                    fullWidth: "off", // Same time only Enable FullScreen of FullWidth !!
                    fullScreen: "off", // Same time only Enable FullScreen of FullWidth !!


                    shadow: 0								//0 = no Shadow, 1,2,3 = 3 Different Art of Shadows -  (No Shadow in Fullwidth Version !)

                });


    });
</script>
