<?php
MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $this->translate('Sorry'), true);
echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>
<div class="container">
    <div class="container mt25 offset-0">
        <!-- CONTENT -->
        <div class="col-md-12 pagecontainer2 offset-0">
            <div class="hpadding50c">
                <p class="lato size30 slim"><?= $this->translate('We are sorry'); ?></p>
                <p class="aboutarrow"></p>
            </div>
            <div class="line3"></div>

            <div class="hpadding50c">

                <p class="lato size22 slim textcenter">
                    <?php 
                    
                    switch($this->param):
                         case 'newsletter':
                            echo $this->translate('This email has already been subscribed for our newsletter.');
                            break;
                    endswitch;
                    ?>
                </p>
                <br>
                <div class="line3"></div>
            </div>



            <div class="clearfix"></div><br><br>
        </div>
        <!-- END CONTENT -->			



    </div>


</div>