<?php
MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $this->translate('Privacy policy'));
echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>
<div class="container">
    <div class="container mt25 offset-0">
        <div class="col-md-12 pagecontainer2 offset-0">
            <div class="hpadding50c">
                <h1 class="lato size30 slim"><?= $this->translate('Privacy policy') ?></h1>
                <p class="aboutarrow"></p>
            </div>
            <div class="line3"></div>

            <div class="hpadding50c">



                <!-- LEFT IMG -->
                <div class="col-md-8 cpdd01 grey2">
                    <div class="pl30 pr30 pb50">
                <strong>General</strong>
                <ol start="1" class="list1">
                    <li>This website ("Rate-Pole.com") is provided by Kardimobile Ltd, with registered office address: 52 Landressy Place, G40 1HF Glasgow. </li>
                    <li>These terms and conditions ('Terms and Conditions') together with the <a href="<?= $this->url(array(),'domain-privacy-policy'); ?>">Privacy Policy</a> set out how you may use our Website. By accessing the Website, you agree to these Terms and Conditions. If you do not agree to these Terms and Conditions, you are not authorised to use the Website. You should read all the Terms and Conditions prior to using the Website. You should also save and/or print out a copy of these Terms and Conditions for future reference.</li>
                    <li>This Website is offered to you conditioned upon your acceptance without modification of any/all the terms, conditions, and notices set forth below (collectively, the "Agreement"). By accessing or using this Website in any manner, you agree to be bound by the Agreement and represent that you have read and understood its terms. Please read the Agreement carefully, as it contains information concerning your legal rights and limitations on these rights, as well as a section regarding applicable law and jurisdiction of disputes. If you do not accept all of these terms and conditions you are not authorized to use this Website.</li>
                    <li>You must not misuse the site.</li>
                    <li>You must not use or attempt to use any automated program (including, but not limited to, spiders or other website crawling technology) to access our site or systems, to search, display or obtain links to any part of the site without prior written permission. Any such use or attempted use (without permission) is strictly forbidden and potentially illegal.</li>
                    <li>You are not permitted to use, or cause others to use, any automated system or software to extract content or data from this website for commercial purposes (''screen scraping''), except in cases where you or any applicable third party has entered into a written Licence Agreement directly with us that expressly permits such activity.</li>
                    <li>You accept that you are solely responsible for ensuring that your device’s operating system, including its browser(s), meets all relevant technical specifications necessary to use the site and that it is compatible with the site.</li>
                </ol>
                <strong>Changes to Terms of Use</strong>
                <ol start="8" class="list1">
                    <li>We reserve the right in our sole discretion to change these Terms of Use at any time without prior notice to you. Any changes will be posted on our website and become effective at the time of posting. Your continued use of the Services after the effective date of such changes will constitute acceptance of and agreement to any such changes. We reserve the right to modify, suspend or discontinue all or part of the Services at any time to you and/or others, with or without notice. We shall not be liable to you or any other party should we exercise our right to modify, suspend or discontinue all or part of the services.</li>
                </ol>
                <strong>User Registration</strong>
                <ol start="9" class="list1">
                    <li>To use the services on the site, you must complete a registration form and submit it to us. At our discretion, we may refuse your application for registration. If we do accept your registration, we will confirm this in writing via email to your registered email address.</li>
                    <li>Each user account is created by administrator based on company registration</li>
                    <li>It is your responsibility to update and inform us of any changes to your registered details.
                        <ul>
                            <li>Registered Users provide true, accurate, current and complete information about themselves as requested in the registration form;</li>
                            <li>Registered Users do not do anything that would assist anyone who is not a Registered User to gain access to their profile or any documents contained therein;</li>
                            <li>Registered Users do not maliciously create additional registration accounts for the purpose of abusing the functionality of the site, or other users; nor do they seek to pass themselves off as another user;</li>
                            <li>Registered Users have read and understood the Website Terms of Use and the <a href="<?= $this->url(array(),'domain-privacy-policy'); ?>">Privacy Policy</a>.</li>
                        </ul>
                    </li>
                    <li>You accept sole and personal responsibility for the use of and for keeping confidential your username and password. You must notify us immediately of any unauthorised use of them or any other breach of security of this Site of which you become aware.</li>
                </ol>
                <strong>Your Review Content</strong>
                <ol start="13" class="list1">
                    <li>You agree to use the Website in accordance with the following rules. All content submitted by you, including, but not limited to, your name, biographical information and all other names, likenesses, graphics, logos, marks, text, images, photographs, and all other information and material shall be called ''Your Content'' for short.</li>
                    <li>You grant to Kardimobile Ltd a non-exclusive, perpetual, irrevocable, transferable, royalty-free license (including full rights to sub-license) to use Your Content (including, without limit, the right to adapt, alter, amend or change Your Content) in any media throughout the world without restriction, and you warrant that any material you submit is your own work.</li>
                    <li>All content that you upload will be considered non-confidential and non-proprietary and we have the right to use, copy, distribute and disclose to third parties any such content for any purpose. We also have the right to identify you to any third parties that claims or alleges that content posted or uploaded by you to the site breaches their legal rights.</li>
                    <li>You agree that you are a genuine consumer with a genuine experience of the product or service you are reviewing and you do not have any professional or personal relationship with the company</li>
                    <li>You have submitted the review based on your own genuine beliefs and have not been given an incentive by the company to submit a review of a specific rating or disposition</li>
                    <li>Publication of Your Content will be at our sole discretion and we are entitled to make additions or deletions to any such material prior to publication, after publication or to refuse publication.</li>
                    <li>We want everyone to be able to share their views on Rate-Pole.com. As such, you agree to use the commenting procedure in an appropriate manner. It is at our discretion to prevent you submitting comments on reviews for excessive use or misuse of the functionality. You also agree to only submit one review per company, product or service per annum. You agree not to leave any website links, email addresses or personal information (including phone numbers) in your reviews, comments and questions on the website.</li>
                    <li>If Your Content contains any material that is not owned by or licensed to You and/or which is subject to third party rights, You are responsible for obtaining, prior to submission of Your Content, all releases, consents and/or licenses necessary to permit use and exploitation of Your Content by us in accordance with these Terms and Conditions without additional compensation.</li>
                    <li>Whenever you submit Your Content to the Website, Your Content must comply with our Restrictions and Content Standards (below). If you do not comply with our Content Standards, we reserve the right to suspend you from using the Website and/or accessing your profile without notice.</li>
                    <li>You can log in to your account at any time to edit/amend/remove a review – if you do not action this through the automated tools in your own account, manual administration by Rate-Pole.com may result in an administration fee being charged</li>
                </ol>
                <strong>Restrictions and Content Standards</strong>
                <ol start="23" class="list1">
                    <li>The views expressed by users of the site do not reflect our views or values in any way.</li>
                    <li>You undertake to us that Your Content or its use in accordance with these Terms and Conditions shall not:
                        <ul>
                            <li>infringe copyrights or database rights, trademarks, rights of privacy, publicity or other intellectual property or other rights of any other person or entity</li>
                            <li>contain any personal information relating to any persons under 18 unless You are either their parent or legal guardian or have obtained the signature and authority of a parent or legal guardian of any such person permitting You to submit such person’s name or other content related to such person</li>
                            <li>contain any content that does not meet our Restrictions and Content Standards</li>
                            <li>contain any malicious code, such as viruses, worms, Trojan horses or other potentially harmful programs or material; or</li>
                            <li>violate any applicable law, statute, ordinance, rule or regulation.</li>
                        </ul>
                    </li>
                    <li>Your Content must:
                        <ul>
                            <li>be accurate where it states facts</li>
                            <li>be genuinely held where it states opinions</li>
                            <li>comply with applicable law in any country in which it is posted.</li>
                        </ul>
                    </li>
                    <li>Your Content must not:
                        <ul>
                            <li>contain any material which is defamatory of any other person</li>
                            <li>contain any material which is obscene, offensive, libellous, menacing, threatening, abusive, fraudulent, criminal or infringes the rights of other people or is in any way illegal</li>
                            <li>promote discrimination based on race, sex, religion, nationality, disability, sexual orientation or age</li>
                            <li>infringe any copyright, database right or trade mark of any other person</li>
                            <li>contain misleading or deceptive statements or omissions or misrepresent Your identity or affiliation with any person</li>
                            <li>falsely represent that You are a consumer</li>
                            <li>contain any unsolicited or unauthorised advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes or other forms of solicitation or advertisement commercial or otherwise</li>
                            <li>be made in breach of any legal duty owed to a third party such as a contractual duty or a duty of confidence</li>
                            <li>be likely to harass any other person</li>
                            <li>be likely to disrupt our service in any way</li>
                            <li>give the impression that they emanate from us where this is not the case; and</li>
                            <li>advocate, promote or assist any unlawful act such as (by way of example only) copyright infringement or computer misuse</li>
                        </ul>
                    </li>
                    <li><strong>Reviews cannot come from the agent themselves, from a competitor of an agent or from a relative of an agent. Kardimobile Ltd reserve the rights to publish information regarding companies who have been caught attempting to influence their own or other company's rankings.</strong></li>
                    <li>Rate-Pole.com accepts no responsibility or liability for the use by any estate or letting agent or other third party of any personal information about you forwarded to any estate or letting agent or to any third party which comes to your attention directly or indirectly through your use of this website.</li>
                    <li>By submitting content to the Site, you grant us a royalty-free, perpetual, irrevocable, and non-exclusive right and licence to use, reproduce, distribute, display, modify and edit this content in connection with the Site’s services, and to sublicense it. We will not pay for these and, at our sole discretion, we can remove or amend them at any time.
                    Please see <a href="<?= $this->url(array(),'domain-about-reviews'); ?>">Review Guidelines</a></li>
                </ol>
                <strong>External Links and Third Parties</strong>
                <ol start="30" class="list1">
                    <li>Rate-Pole.com does not make any representation as to the security, quality or propriety of any website which may be accessed through this website. Most linked websites accessed through this website are independent websites over which Rate-Pole.com does not exercise any control, whether financial, editorial or of any other kind and are not in any way endorsed by Rate-Pole.com.</li>
                    <li>Accordingly, Rate-Pole.com has no responsibility or liability to you in respect of any products or services purchased or obtained by you from any such linked website nor in respect of the use of any personally identifying information by any such linked website or its owner.</li>
                    <li>Our website may contain links to third party products, services and/or websites that are not affiliated with us. We have no control over the products, services or websites of these third parties and we do not guarantee or take responsibility for them. Our website may also contain advertising from third parties and we are not responsible for any misleading or inaccurate advertisements which are the sole responsibility of the advertiser. Any links or advertisements on our website should not be taken as an endorsement by us of any kind. Furthermore, our website contains data provided by third parties and we accept no responsibility for any inaccuracies in this material. You agree to release us from any claims or disputes of any kind arising from or in any way connected to such disputes with third parties.</li>
                </ol>
                <strong>Liability</strong>
                <ol start="33" class="list1">
                    <li>All reviews and comments on this web site are the opinions of the reviewers. Whilst Rate-Pole.com takes reasonable care to ensure that information on this site is accurate, complete and up to date, Rate-Pole.com offers no warranty that any such information is correct, and you should not rely solely on the information on this site when selecting companies and services.</li>
                    <li>Materials posted on our Website are not intended as advice and should not be relied upon as such. We therefore disclaim all liability and responsibility arising from any reliance placed on such information.</li>
                    <li>To the fullest extent permissible by law, we exclude and disclaim all warranties, terms, conditions and representations that might otherwise be implied by law in relation to this Website. In particular we do not represent or warrant that the Website will be error-free, free of viruses or other harmful components, or that defects will be corrected. You must take your own precautions in this respect.</li>
                    <li>We do not accept liability for any failure to maintain the Website and/or late or failed delivery of any materials.</li>
                    <li>We shall not be liable, under these Terms and Conditions for any indirect, special, incidental or consequential damages or otherwise, even if advised of the possibility of such damages.</li>
                    <li>The materials may contain inaccuracies and typographical errors. We do not warrant the accuracy or completeness of the materials.</li>
                    <li>We shall not be liable for any loss caused as a result of your actions or inactions based on the materials available on this Website. However, nothing in these Terms and Conditions shall affect your statutory rights, and nothing in these Terms and Conditions shall exclude our liability for:
                        <ul>
                            <li>death or personal injury arising through negligence</li>
                            <li>fraudulent misrepresentation; and/or</li>
                            <li>anything else that cannot be excluded or limited by us under UK Law</li>
                        </ul>
                    </li>
                </ol>
                
                <strong>Ranking System</strong>
                <ol start="49" class="list1">
                    <li>Rate-Pole.com produce a ranking position for each listed company on our website. This is based on our own algorithm and is calculated on the number of stars and the number of reviews that each listed agent has achieved, at the latest point in time.</li>
                    <li>Each star rating represents an individual banding.</li>
                    <li>Listed companies do not need to have received 100% of their reviews with 5 stars, in order to achieve the 5 star banding.</li>
                    <li>Where two or more listed companies have received the same number of stars, then the agent with the most reviews overall will be ranked higher.</li>
                    <li>The ranking system is for the sole purpose of the Rate-Pole website and, as such, the ranking is derived solely from the review ratings of the customer experiences published to our website. This does not imply that, out with the rankings collated from these reviews, any agent conducts their business activities any better or worse than another agent.</li>
                    <li>Rate-Pole reserve the right to review, alter or make changes to the ranking system, at our discretion.</li>
                </ol>
                <strong>Intellectual Property</strong>
                <ol start="55" class="list1">
                    <li>The content of the Website, including but not limited to text, graphics, logos, software, awards emblems and trademarks are the property of Kardimobile Ltd and are protected by copyright and other laws. You may not modify, publish, transmit, participate in the transfer or sale, create derivative works or in any way exploit, any of the content, without our prior written consent. Kardimobile Ltd does not tolerate copyright infringement and will actively pursue any known infringement to the full extent of the law.</li>
                    <li>You may access, view and print out one copy of this Website and all information, images, and other content displayed on the Website ('materials') on a single device strictly in accordance with these Terms and Conditions. You may only view, print out and use the website and the materials for your own personal, non-commercial use.</li>
                    <li>The use of the data held in the Kardimobile Ltd directory, as a source or target for direct marketing, telemarketing, market research, or any other marketing activity on yours, or someone else's behalf, is strictly prohibited.</li>
                </ol>
                <strong>Access/Availability of the Website</strong>
                <ol start="58" class="list1">
                    <li>We strive to ensure that our website and the services are available to you at all times but cannot guarantee that either the website or the services will operate continuously, without interruptions or be fault free. On occasion, necessary maintenance or upgrade work requires us to make the website and the Services unavailable without notice, but we aim to keep downtime to a minimum. We accept no liability for any interruption or loss of service. We reserve the absolute right to alter, suspend or discontinue any part of our website or the Services, including your access to it.
                </li></ol>
                <strong>Commerical Relationships</strong>
                <ol start="59" class="list1">
                    <li>Kardimobile Ltd have a commercial relationship with some companies who have our Premium Support Service and also other industry related companies who advertise their services on our site.
                        The level of service or advertising that an agent or company have with us, has no impact on the review ratings and/or their ranking.
                    </li>
                </ol>
                <strong>Privacy</strong>
                <ol start="60" class="list1">
                    <li>The privacy of your personal data is important to us. Please see our <a href="<?= $this->url(array(),'domain-privacy-policy'); ?>">Privacy Policy</a></li>
                </ol>
                <strong>Cookies</strong>
                <ol start="61" class="list1">
                    <li>Please see our <a href="<?= $this->url(array(),'domain-cookie-policy'); ?>">Cookie Policy</a></li>
                </ol>
                <strong>Contact Us</strong>
                <p>If you have any concerns or queries about material which appears on our website or if you have questions about your use of this website or these Terms and Conditions please get in touch using the
                    <a href="<?= $this->url(array(),'domain-contact'); ?>">'contact us'</a> function on the website.</p>
                <p>Our postal address for correspondence is 52 Landressy Place, G40 1HF Glasgow.</p>

            
                    </div>
                </div>
                <!-- END OF LEFT IMG -->

                <!-- IMG RIGHT TEXT -->
                <div class="col-md-4 cpdd02">
                    <div class="opensans grey">
                        <?php if (count($this->popularArticles) > 0) { ?>
                            <h2 class="lato size18 dark bold"><?= $this->translate('Popular articles'); ?></h2><br>

                            <ul class="blogcat">
                                <?php foreach ($this->popularArticles as $popularArticle): ?>
                                    <li>
                                        <a href="<?php echo $this->url(array('slug' => $popularArticle['Translation'][$this->language]['slug']), 'domain-news-article'); ?>">
                                            <?= MF_Text::truncate($popularArticle['Translation'][$this->language]['title'], 40); ?>
                                        </a> 
                                        <span class="badge2 pull-right indent0"><i class="fa fa-comment"></i> <?= count($popularArticle['Comments']); ?></span></li>
                                <?php endforeach; ?>
                            </ul>
                            <br>
                        <?php } ?>
                        <?php echo $this->action('banner-sidebar2', 'index', 'banner'); ?>
                        <br /><br />


                        <!-- Nav tabs -->
                        <ul class="nav navigation-tabs3">
                            <li class="active"><a href="#tab-newtopic" data-toggle="tab"><span class="glyphicon glyphicon-star"></span> <?= $this->translate('Featured'); ?></a></li>
                            <li><a href="#tab-comments" data-toggle="tab"><span class="glyphicon glyphicon-stats"></span> <?= $this->translate('Popular'); ?> </a></li>

                        </ul>

                        <div class="tab-content4">
                            <!-- Tab 1 -->
                            <div class="tab-pane active" id="tab-newtopic">
                                <?php foreach ($this->premiumAgents as $premiumAgent): ?>
                                    <div class="col-md-4">
                                        <a href="<?= $this->url(array('slug' => $premiumAgent['link']), 'domain-agent-details'); ?>"><img alt="<?= $premiumAgent['name']; ?>" class="left mr20" src="<?= $premiumAgent->getLogoUrl('85x50'); ?>"></a>
                                    </div>
                                    <div class="col-md-8">
                                        <a class="dark" href="<?= $this->url(array('slug' => $premiumAgent['link']), 'domain-agent-details'); ?>">
                                            <b><?= $premiumAgent['name']; ?></b></a>
                                        <br>
                                        <?= str_repeat('<img src="/images/star.png" alt="Star" />', round($premiumAgent['rating'])); ?>
                                    </div>

                                    <div class="line4 clearfix mt10"></div>
                                <?php endforeach; ?>
                            </div>
                            <!-- End of Tab 1 -->

                            <!-- Tab 2 -->
                            <div class="tab-pane" id="tab-comments">
                                <?php foreach ($this->popularAgents as $popularAgent): ?>
                                    <div class="col-md-4">
                                        <a href="<?= $this->url(array('slug' => $popularAgent['link']), 'domain-agent-details'); ?>"><img alt="<?= $popularAgent['name']; ?>" class="left mr20" src="<?= $popularAgent->getLogoUrl('85x50'); ?>"></a>
                                    </div>
                                    <div class="col-md-8">
                                        <a class="dark" href="<?= $this->url(array('slug' => $popularAgent['link']), 'domain-agent-details'); ?>">
                                            <b><?= $popularAgent['name']; ?></b></a>
                                        <br>
                                        <?= str_repeat('<img src="/images/star.png" alt="Star" />', round($popularAgent['rating'])); ?>
                                    </div>

                                    <div class="line4 clearfix mt10"></div>
                                <?php endforeach; ?>
                            </div>
                            <!-- End of Tab 2 -->

                        </div>







                    </div>
                </div>
                <!-- END OF IMG RIGHT TEXT -->
                <div class="clearfix"></div>
                <br><br>





            </div>



            <div class="clearfix"></div><br><br>
        </div>
        <!-- END CONTENT -->			



    </div>


</div>