<?php
MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $this->translate('Error'), true);
echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>
<div class="container">
    <div class="container mt25 offset-0">


        <!-- CONTENT -->
        <div class="col-md-12 pagecontainer2 offset-0">
            <div class="hpadding50c">
                <p class="lato size30 slim">Error</p>
                <p class="aboutarrow"></p>
            </div>
            <div class="line3"></div>

            <div class="hpadding50c">


                <section class="column">
                    <section>
                        <div style="padding-bottom: 100px;"><?php echo $this->message ?></div>

                        <?php if (isset($this->exception)): ?>

                            <h2>Exception information:</h2>
                            <p>
                                <b>Message:</b> <?php echo $this->exception->getMessage() ?>
                            </p>

                            <h2>Stack trace:</h2>
                            <pre><?php echo $this->exception->getTraceAsString() ?>
                            </pre>

                            <h2>Request Parameters:</h2>
                            <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
                            </pre>

                        <?php endif ?>  
                    </section>
                </section>

            </div>



            <div class="clearfix"></div><br><br>
        </div>
        <!-- END CONTENT -->			



    </div>


</div>