
<a href="<?= $this->url(array(),'domain-staff-search'); ?>"><?= $this->translate('Search staff member'); ?></a>

<!-- FOOTER -->

<div class="footerbgblack">
    <div class="container">		

        <div class="col-md-3">
            <span class="ftitleblack">Let's socialize</span>
            <div class="scont">
                <a href="#" class="social1b"><img src="/assets/images/icon-facebook.png" alt=""/></a>
                <a href="#" class="social2b"><img src="/assets/images/icon-twitter.png" alt=""/></a>
                <a href="#" class="social3b"><img src="/assets/images/icon-gplus.png" alt=""/></a>
                <a href="#" class="social4b"><img src="/assets/images/icon-youtube.png" alt=""/></a>
                <br/><br/><br/>
                <a href="#"><img src="/assets/images/logosmal2.png" alt="" /></a><br/>
                <span class="grey2">&copy; 2013  |  <a href="#">Privacy Policy</a><br/>
                    All Rights Reserved </span>
                <br/><br/>

            </div>
        </div>
        <!-- End of column 1-->

        <div class="col-md-3">
            <span class="ftitleblack">Travel Specialists</span>
            <br/><br/>
            <ul class="footerlistblack">
                <li><a href="#">Golf Vacations</a></li>
                <li><a href="#">Ski & Snowboarding</a></li>
                <li><a href="#">Disney Parks Vacations</a></li>
                <li><a href="#">Disneyland Vacations</a></li>
                <li><a href="#">Disney World Vacations</a></li>
                <li><a href="#">Vacations As Advertised</a></li>
            </ul>
        </div>
        <!-- End of column 2-->		

        <div class="col-md-3">
            <span class="ftitleblack">Travel Specialists</span>
            <br/><br/>
            <ul class="footerlistblack">
                <li><a href="#">Weddings</a></li>
                <li><a href="#">Accessible Travel</a></li>
                <li><a href="#">Disney Parks</a></li>
                <li><a href="#">Cruises</a></li>
                <li><a href="#">Round the World</a></li>
                <li><a href="#">First Class Flights</a></li>
            </ul>				
        </div>
        <!-- End of column 3-->		

        <div class="col-md-3 grey">
            <span class="ftitleblack">Newsletter</span>
            <div class="relative">
                <input type="email" class="form-control fccustom2black" id="exampleInputEmail1" placeholder="Enter email">
                <button type="submit" class="btn btn-default btncustom">Submit<img src="/assets/images/arrow.png" alt=""/></button>
            </div>
            <br/><br/>
            <span class="ftitleblack">Customer support</span><br/>
            <span class="pnr">1-866-599-6674</span><br/>
            <span class="grey2">office@travel.com</span>
        </div>			
        <!-- End of column 4-->			


    </div>	
</div>

<div class="footerbg3black">
    <div class="container center grey"> 
        <a href="#">Home</a> | 
        <a href="#">About</a> | 
        <a href="#">Last minute</a> | 
        <a href="#">Early booking</a> | 
        <a href="#">Special offers</a> | 
        <a href="#">Blog</a> | 
        <a href="#">Contact</a>
        <a href="#top" class="gotop scroll"><img src="/assets/images/spacer.png" alt=""/></a>
    </div>
</div>




<!-- Javascript -->	
<script src="/assets/js/js-details.js"></script>

<!-- Googlemap -->	
<script src="/assets/js/initialize-google-map.js"></script>

<!-- Custom Select -->
<script type='text/javascript' src='/assets/js/jquery.customSelect.js'></script>

<!-- Custom functions -->
<script src="/assets/js/functions.js"></script>

<!-- Nicescroll  -->	
<script src="/assets/js/jquery.nicescroll.min.js"></script>

<!-- jQuery KenBurn Slider  -->
<script type="text/javascript" src="/plugins/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>

<!-- CarouFredSel -->
<script src="/assets/js/jquery.carouFredSel-6.2.1-packed.js"></script>
<script src="/assets/js/helper-plugins/jquery.touchSwipe.min.js"></script>

<script type="text/javascript" src="/assets/js/helper-plugins/jquery.mousewheel.min.js"></script>
<script type="text/javascript" src="/assets/js/helper-plugins/jquery.transit.min.js"></script>
<script type="text/javascript" src="/assets/js/helper-plugins/jquery.ba-throttle-debounce.min.js"></script>

<!-- Counter -->	
<script src="/assets/js/counter.js"></script>	

<!-- Carousel-->	
<script src="/assets/js/initialize-carousel-detailspage.js"></script>		

<!-- Js Easing-->	
<script src="/assets/js/jquery.easing.js"></script>


<!-- Bootstrap-->	
<script src="/assets/dist/js/bootstrap.min.js"></script>