<?php 
                              $logoUrl = '/images/logo.png';
                              if($this->language=='en'){
                                  $logoUrl = '/images/ratepole_logo.png';
                              }
                              ?>
<!--<a href="<?php //  $this->url(array(),'domain-staff-search'); ?>"><?= $this->translate('Search staff member'); ?></a>-->

<!-- FOOTER -->

<div class="footerbgblack">
    <div class="container">		
        
        <div class="col-md-3">
            <a href="/">
                    <img src="<?= $logoUrl; ?>" alt="<?= $this->translate('Rate Pole'); ?>" class="logo" style="display: inline-block; width: 100px;">
                </a>
        </div>
        <div class="col-md-3">
            <span class="ftitleblack"><?= $this->translate('Follow us'); ?></span>
            <div class="scont">
                <?php
                    if($this->language=='pl'){
                        $facebookLink = 'http://facebook.com/ocenfachowca';
                        $twitterLink = 'https://twitter.com/ocenfachowca';
                    }
                    else{
                        $facebookLink = 'http://facebook.com/Rate-Pole-546889205490101';
                        $twitterLink = 'https://twitter.com/rate_pole';
                    }
                
                ?>
                <br />
                <a href="<?= $facebookLink; ?>" class="social1b"><img src="/assets/images/icon-facebook.png" alt=""/></a>
                <a href="<?= $twitterLink; ?>" class="social2b"><img src="/assets/images/icon-twitter.png" alt=""/></a>

            </div>
        </div>
        <!-- End of column 1-->

        <!-- End of column 2-->		

        <div class="col-md-3">
            <span class="ftitleblack"><?= $this->translate('Useful information'); ?></span>
            <br/><br/>
            <ul class="footerlistblack">
                <li><a href="<?= $this->url(array(),'domain-advertising'); ?>"><?= $this->translate('Advertising'); ?></a></li>
                <li><a href="<?= $this->url(array(),'domain-premium-package'); ?>"><?= $this->translate('Premium Package'); ?></a></li>
                <li><a href="<?= $this->url(array(),'domain-about-reviews'); ?>"><?= $this->translate('About reviews'); ?></a></li>
                <li><a href="<?= $this->url(array(),'domain-privacy-policy'); ?>"><?= $this->translate('Privacy policy'); ?></a></li>
                <li><a href="<?= $this->url(array(),'domain-terms-conditions'); ?>"><?= $this->translate('Terms and conditions'); ?></a></li>
                <li><a href="<?= $this->url(array(),'domain-contact'); ?>"><?= $this->translate('Contact'); ?></a></li>
            </ul>				
        </div>
        <!-- End of column 3-->		

        <div class="col-md-3 grey">
            <span class="ftitleblack">Newsletter</span>
            <div class="relative">
                <form method='POST' action='<?= $this->url(array(),'domain-newsletter-register'); ?>'>
                    <input type="email" class="form-control fccustom2black" name='email' id="exampleInputEmail1" placeholder="<?= $this->translate('Enter email'); ?>">
                    <button type="submit" class="btn btn-default btncustom">Submit<img src="/assets/images/arrow.png" alt="Subscribe"/></button>
                </form>
            </div>
        </div>			
        <!-- End of column 4-->			


    </div>	
</div>

<div class="footerbg3black">
    <div class="container center grey"> 
        <span class="grey2">&copy; <?= date('Y'); ?> <?= $this->translate('Rate Pole'); ?>  | <?= $this->translate('All Rights Reserved'); ?></span>
        <a href="#top" class="gotop scroll"><img src="/assets/images/spacer.png" alt="Go to top"/></a>
    </div>
</div>




<!-- Javascript -->	
<script src="/assets/js/js-details.js"></script>

<!-- Googlemap -->	
<script src="/assets/js/initialize-google-map.js"></script>

<!-- Custom Select -->
<script type='text/javascript' src='/assets/js/jquery.customSelect.js'></script>

<!-- Custom functions -->
<script src="/assets/js/functions.js"></script>

<!-- Nicescroll  -->	
<script src="/assets/js/jquery.nicescroll.min.js"></script>

<!-- jQuery KenBurn Slider  -->
<script type="text/javascript" src="/plugins/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>

<!-- CarouFredSel -->
<script src="/assets/js/jquery.carouFredSel-6.2.1-packed.js"></script>
<script src="/assets/js/helper-plugins/jquery.touchSwipe.min.js"></script>

<script type="text/javascript" src="/assets/js/helper-plugins/jquery.mousewheel.min.js"></script>
<script type="text/javascript" src="/assets/js/helper-plugins/jquery.transit.min.js"></script>
<script type="text/javascript" src="/assets/js/helper-plugins/jquery.ba-throttle-debounce.min.js"></script>

<!-- Counter -->	
<script src="/assets/js/counter.js"></script>	

<!-- Carousel-->	
<script src="/assets/js/js-index.js"></script>		

<!-- Js Easing-->	
<script src="/assets/js/jquery.easing.js"></script>


<!-- Bootstrap-->	
<script src="/assets/dist/js/bootstrap.min.js"></script>