
    <!-- Libs -->
    <script src="/assets/js/libs/jquery-1.10.2.min.js"></script>
    <script type='text/javascript' src='/assets/js/libs/jquery.flexslider-min.js'></script>
	<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
	<script src="/assets/js/jquery.bxslider.min.js"></script>

    <!-- Custom -->
    <link rel="stylesheet" href="/assets/css/prettyPhoto.css" type="text/css" media="screen" charset="utf-8" />
    <script src="/assets/js/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>
<script src="/assets/js/isotope.pkgd.min.js"></script>
    <script src="/assets/js/scripts.js"></script>