

<?php 
echo $this->headTitle();
echo $this->headMeta();
echo $this->headLink();
        ?>

<!--<title>-->
   <?php // if(strlen(strip_tags($this->headTitle()))):
//        echo strip_tags($this->headTitle());
//       else: 
//           echo "UKS Jedynka Krzeszowice";
//           endif; ?>
    
    
<!--</title>-->
  	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	
    <!-- Bootstrap -->
    <link href="/assets/dist/css/bootstrap.css" rel="stylesheet" media="screen">
    <link href="/assets/css/custom.css" rel="stylesheet" media="screen">


	<link href="/assets/examples/carousel/carousel.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="assets/js/html5shiv.js"></script>
      <script src="assets/js/respond.min.js"></script>
    <![endif]-->
	
    <!-- Fonts -->	
	<link href='http://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:700,400,300,300italic' rel='stylesheet' type='text/css'>	
	<!-- Font-Awesome -->
    <link rel="stylesheet" type="text/css" href="/assets/css/font-awesome.css" media="screen" />
    <!--[if lt IE 7]><link rel="stylesheet" type="text/css" href="assets/css/font-awesome-ie7.css" media="screen" /><![endif]-->
	
    <!-- REVOLUTION BANNER CSS SETTINGS -->
    <link rel="stylesheet" type="text/css" href="/assets/css/fullscreen.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="/plugins/rs-plugin/css/settings.css" media="screen" />
	
    <!-- Picker UI-->	
	<link rel="stylesheet" href="/assets/css/jquery-ui.css" />	
	
	<!-- bin/jquery.slider.min.css -->
	<link rel="stylesheet" href="/plugins/flexslider/flexslider.css" type="text/css">
	<link rel="stylesheet" href="/plugins/jslider/css/jslider.css" type="text/css">
	<link rel="stylesheet" href="/plugins/jslider/css/jslider.round-blue.css" type="text/css">
	<link rel="stylesheet" href="/plugins/select2/css/select2.min.css" type="text/css">
        
	<link rel="stylesheet" href="/css/custom-style.min.css" type="text/css">
	<link rel="stylesheet" href="/css/mobile.min.css" type="text/css">
        
	
    <!-- jQuery-->	
    <script src="/assets/js/jquery.v2.0.3.js"></script>
	<script src="/assets/js/jquery-ui.js"></script>	
	
	<!-- bin/jquery.slider.min.js -->
	<script type="text/javascript" src="/plugins/jslider/js/jshashtable-2.1_src.js"></script>
	<script type="text/javascript" src="/plugins/jslider/js/jquery.numberformatter-1.2.3.js"></script>
	<script type="text/javascript" src="/plugins/jslider/js/tmpl.js"></script>
	<script type="text/javascript" src="/plugins/jslider/js/jquery.dependClass-0.1.js"></script>
	<script type="text/javascript" src="/plugins/jslider/js/draggable-0.1.js"></script>
	<script type="text/javascript" src="/plugins/jslider/js/jquery.slider.js"></script>
	<script type="text/javascript" src="/plugins/select2/js/select2.min.js"></script>
	<!-- end -->

    
    <!-- META TAGS -->
    <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="msvalidate.01" content="2B29F8D28D9D14D639FD9EA1FDD28219" />

  <script src="/plugins/flexslider/jquery.flexslider-min.js"></script>


    <!--  ANALYTICS CODE START -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-19423409-3', 'auto');
        ga('send', 'pageview', { 'dimension1' : '<?= !isset($pagetype) ? 'other' : $pagetype; ?>'});
    </script>
    <!--  ANALYTICS CODE STOP -->



    <!-- Internet Explorer is CRAP - Get a better browser! -->
    <!--[if lt IE 9]>
    <script src="/js/html5shiv.js"></script>
    <script src="/js/respond.min.js"></script>
    <![endif]-->

</head>
     
    