<?php

/**
 * Review_Model_Doctrine_BaseReviewTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $lang
 * @property clob $review
 * @property clob $feedback
 * @property clob $fee_feedback
 * @property Review_Model_Doctrine_Review $Review
 * 
 * @package    Admi
 * @subpackage Review
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Review_Model_Doctrine_BaseReviewTranslation extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('review_review_translation');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('lang', 'string', 64, array(
             'primary' => true,
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('review', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('feedback', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('fee_feedback', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Review_Model_Doctrine_Review as Review', array(
             'local' => 'id',
             'foreign' => 'id'));
    }
}