<?php

/**
 * Review_Model_Doctrine_BaseReview
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $agent_id
 * @property integer $branch_id
 * @property integer $rating
 * @property bool $recommend
 * @property clob $review
 * @property string $firstname
 * @property string $lastname
 * @property string $phone
 * @property string $display_name
 * @property string $email
 * @property boolean $view
 * @property string $ip
 * @property string $hostname
 * @property clob $feedback
 * @property date $service_date
 * @property boolean $featured
 * @property string $activation_ip
 * @property string $activation_hostname
 * @property integer $helpful
 * @property integer $staff
 * @property integer $staff2
 * @property clob $notes
 * @property clob $fee_feedback
 * @property string $approved_by
 * @property Doctrine_Collection $Translation
 * @property Doctrine_Collection $Files
 * @property Doctrine_Collection $Comments
 * @property Doctrine_Collection $AbuseReports
 * @property Doctrine_Collection $AlertsSend
 * @property Review_Model_Doctrine_RankingWeek $RankingWeek
 * 
 * @package    Admi
 * @subpackage Review
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Review_Model_Doctrine_BaseReview extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('review_review');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('agent_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('branch_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('rating', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('recommend', 'bool', null, array(
             'type' => 'bool',
             'default' => 0,
             ));
        $this->hasColumn('review', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('firstname', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('lastname', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('display_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('view', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('ip', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('hostname', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('feedback', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('service_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('featured', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('activation_ip', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('activation_hostname', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('helpful', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('staff', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('staff2', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('notes', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('fee_feedback', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('approved_by', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Review_Model_Doctrine_ReviewTranslation as Translation', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasMany('Review_Model_Doctrine_Files as Files', array(
             'local' => 'id',
             'foreign' => 'review_id'));

        $this->hasMany('Review_Model_Doctrine_Comment as Comments', array(
             'local' => 'id',
             'foreign' => 'review_id'));

        $this->hasMany('Review_Model_Doctrine_AbuseReport as AbuseReports', array(
             'local' => 'id',
             'foreign' => 'review_id'));

        $this->hasMany('Review_Model_Doctrine_AlertSend as AlertsSend', array(
             'local' => 'id',
             'foreign' => 'review_id'));

        $this->hasOne('Review_Model_Doctrine_RankingWeek as RankingWeek', array(
             'local' => 'id',
             'foreign' => 'review_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'review',
              1 => 'feedback',
              2 => 'fee_feedback',
             ),
             'tableName' => 'review_review_translation',
             'className' => 'ReviewTranslation',
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}