<?php

/**
 * Review_Model_Doctrine_Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Review
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Review_Model_Doctrine_Comment extends Review_Model_Doctrine_BaseComment
{

}