<?php

/**
 * Review_Model_Doctrine_RankingWeekTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Review_Model_Doctrine_RankingWeekTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Review_Model_Doctrine_RankingWeekTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Review_Model_Doctrine_RankingWeek');
    }
}