<?php

/**
 * Review_Model_Doctrine_Review
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Review
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Review_Model_Doctrine_Review extends Review_Model_Doctrine_BaseReview
{
    public static function getReviewCapacity($capacity)
    {
        switch($capacity)
        {
                    case 1:
                            return "Lettings (as a Landlord)";
                            break;
                    case 2:
                            return "Lettings (as a Tenant)";
                            break;
                    case 3:
                            return "Sales (as a Vendor)";
                            break;
                    case 4:
                            return "Sales (as a Buyer)";
                            break;
                    case 5:
                            return "Surveys";
                            break;
                    case 6:
                            return "Conveyancing";
                            break;
                    case 7:
                            return "Lettings (Prospective customer)";
                            break;
                    case 8:
                            return "Sales (Prospective customer)";
                            break;
                    case 9:
                            return "They manage our building";
                            break;
                    case 10:
                            return "They are our factor";
                            break;
                    case 11:
                            return "They manage our estate";
                            break;
                    case 12:
                            return "They arranged our mortgage";
                            break;
                    case 13:
                            return "Re-Mortgages (Prospective Customer)";
                            break;
                    case 14:
                            return "Mortgages (Prospective Customer)";
                            break;
                    case 15:
                            return "Repair/Property Management";
                            break;
        case 16:
                            return "Repair (tradesman)";
                            break;
                    case 17:
                            return "Property Management";
                            break;
                    case 18:
                            return "Admin";
                            break;
                    case 19:
                            return "Accounts";
                            break;
                    case 20:
                            return "Buying agent";
                            break;
                    case 21:
                            return "Relocation agent";
                            break;
                    case 22:
                            return "Holiday rental";
                            break;
                    default:
                            return false;
                            break;
            }

    }
    
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Staff_Model_Doctrine_Staff as Staff', array(
             'local' => 'staff',
             'foreign' => 'id'));

        $this->hasOne('Staff_Model_Doctrine_Staff as Staff2', array(
             'local' => 'staff2',
             'foreign' => 'id'));

        $this->hasOne('Branch_Model_Doctrine_Branch as Branch', array(
             'local' => 'branch_id',
             'foreign' => 'id'));
        
        
        $this->hasOne('Agent_Model_Doctrine_Agent as Agent', array(
             'local' => 'agent_id',
             'foreign' => 'id'));
        
        $this->hasMany('Review_Model_Doctrine_Comment as Comments', array(
             'local' => 'id',
             'foreign' => 'review_id'));
    }
}