<?php

/**
 * Review_Model_Doctrine_Temp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Review
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Review_Model_Doctrine_Temp extends Review_Model_Doctrine_BaseTemp
{   
     public function setUp()
    {
        parent::setUp();
        $this->hasOne('Staff_Model_Doctrine_Staff as Staff', array(
             'local' => 'staff',
             'foreign' => 'id'));

        $this->hasOne('Staff_Model_Doctrine_Staff as Staff2', array(
             'local' => 'staff2',
             'foreign' => 'id'));

        $this->hasOne('Branch_Model_Doctrine_Branch as Branch', array(
             'local' => 'branch_id',
             'foreign' => 'id'));
        
        $this->hasOne('Agent_Model_Doctrine_Agent as Agent', array(
             'local' => 'agent_id',
             'foreign' => 'id'));
    }
}