<?php

/**
 * Staff_Model_Doctrine_AreaCoveredTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Staff_Model_Doctrine_AreaCoveredTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Staff_Model_Doctrine_AreaCoveredTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Staff_Model_Doctrine_AreaCovered');
    }
}