<?php

/**
 * Staff_Model_Doctrine_BaseStaffBranch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $staff_id
 * @property integer $branch_id
 * 
 * @package    Admi
 * @subpackage Staff
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Staff_Model_Doctrine_BaseStaffBranch extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('staff_staff_branch');
        $this->hasColumn('staff_id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('branch_id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}