<?php

/**
 * Staff_Model_Doctrine_Staff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Staff
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Staff_Model_Doctrine_Staff extends Staff_Model_Doctrine_BaseStaff
{
     public static $staffPhotoDimensions = array(
        '126x126' => 'Photo in admin panel',                  // admin
        '80x80' => 'Main',
        '265x265' => 'Main2',
    );
    
    public static function getStaffPhotoDimensions() {
        return self::$staffPhotoDimensions;
    }
    
    
    public function getFullName(){
        return $this->firstname." ".$this->lastname;
    }
    
    public function getPictureUrl($dimensions = '80x80'){
//        var_dump($this->get('PhotoRoot')->toArray());exit;
        if($this->get('PhotoRoot')&&strlen($this->get('PhotoRoot')->filename)){
            return MF_Text::getPhotoPath($this->get('PhotoRoot'),$dimensions);
        }
        else{
            return '/assets/images/user-avatar.jpg';
        }
       
    }
    
     public function setUp()
    {
        parent::setUp();
        $this->hasOne('Agent_Model_Doctrine_Agent as Agent', array(
             'local' => 'agent_id',
             'foreign' => 'id'));
        
        $this->hasOne('Branch_Model_Doctrine_Branch as Branch', array(
             'local' => 'branch_id',
             'foreign' => 'id'));

        
        $this->hasOne('Media_Model_Doctrine_Photo as PhotoRoot', array(
             'local' => 'photo_root_id',
             'foreign' => 'id'));
    }
}