<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('newsletter_group_translation');
        $this->dropTable('newsletter_sent');
        $this->changeColumn('newsletter_message', 'sent', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->createTable('newsletter_group_translation', array(
             'id' => 
             array(
              'primary' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'lang' => 
             array(
              'primary' => '1',
              'type' => 'string',
              'length' => '64',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('newsletter_sent', array(
             'id' => 
             array(
              'primary' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '6',
             ),
             'message_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'subscriber_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'group_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'send_at' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'sent' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }
}