<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('newsletter_page', 'newsletter_page_message_id_newsletter_message_id', array(
             'name' => 'newsletter_page_message_id_newsletter_message_id',
             'local' => 'message_id',
             'foreign' => 'id',
             'foreignTable' => 'newsletter_message',
             ));
        $this->addIndex('newsletter_page', 'newsletter_page_message_id', array(
             'fields' => 
             array(
              0 => 'message_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('newsletter_page', 'newsletter_page_message_id_newsletter_message_id');
        $this->removeIndex('newsletter_page', 'newsletter_page_message_id', array(
             'fields' => 
             array(
              0 => 'message_id',
             ),
             ));
    }
}