<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('newsletter_message_group', 'newsletter_message_group_message_id_newsletter_group_id', array(
             'name' => 'newsletter_message_group_message_id_newsletter_group_id',
             'local' => 'message_id',
             'foreign' => 'id',
             'foreignTable' => 'newsletter_group',
             ));
        $this->createForeignKey('newsletter_message_group', 'newsletter_message_group_group_id_newsletter_message_id', array(
             'name' => 'newsletter_message_group_group_id_newsletter_message_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'newsletter_message',
             ));
        $this->addIndex('newsletter_message_group', 'newsletter_message_group_message_id', array(
             'fields' => 
             array(
              0 => 'message_id',
             ),
             ));
        $this->addIndex('newsletter_message_group', 'newsletter_message_group_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('newsletter_message_group', 'newsletter_message_group_message_id_newsletter_group_id');
        $this->dropForeignKey('newsletter_message_group', 'newsletter_message_group_group_id_newsletter_message_id');
        $this->removeIndex('newsletter_message_group', 'newsletter_message_group_message_id', array(
             'fields' => 
             array(
              0 => 'message_id',
             ),
             ));
        $this->removeIndex('newsletter_message_group', 'newsletter_message_group_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
    }
}