<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('newsletter_group_translation', 'newsletter_group_translation_id_newsletter_group_id', array(
             'name' => 'newsletter_group_translation_id_newsletter_group_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'newsletter_group',
             ));
        $this->createForeignKey('newsletter_group_translation', 'newsletter_group_translation_id_newsletter_group_id_1', array(
             'name' => 'newsletter_group_translation_id_newsletter_group_id_1',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'newsletter_group',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('newsletter_group_translation', 'newsletter_group_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('newsletter_group_translation', 'newsletter_group_translation_id_newsletter_group_id');
        $this->dropForeignKey('newsletter_group_translation', 'newsletter_group_translation_id_newsletter_group_id_1');
        $this->removeIndex('newsletter_group_translation', 'newsletter_group_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}