<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('newsletter_page', 'newsletter_page_attachment_id_attachment_serwis10_attachment_id');
        $this->dropForeignKey('newsletter_page', 'newsletter_page_photo_root_id_media_photo_id');
    }

    public function down()
    {
        $this->createForeignKey('newsletter_page', 'newsletter_page_attachment_id_attachment_serwis10_attachment_id', array(
             'name' => 'newsletter_page_attachment_id_attachment_serwis10_attachment_id',
             'local' => 'attachment_id',
             'foreign' => 'id',
             'foreignTable' => 'attachment_serwis10_attachment',
             ));
        $this->createForeignKey('newsletter_page', 'newsletter_page_photo_root_id_media_photo_id', array(
             'name' => 'newsletter_page_photo_root_id_media_photo_id',
             'local' => 'photo_root_id',
             'foreign' => 'id',
             'foreignTable' => 'media_photo',
             ));
    }
}