<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('newsletter_group');
        $this->dropTable('newsletter_message_group');
        $this->dropTable('newsletter_subscriber_group');
        $this->createTable('newsletter_message_category', array(
             'message_id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'category_id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'message_id',
              1 => 'category_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('newsletter_subscriber_category', array(
             'subscriber_id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'category_id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'subscriber_id',
              1 => 'category_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->createTable('newsletter_group', array(
             'id' => 
             array(
              'primary' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('newsletter_message_group', array(
             'message_id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'group_id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'message_id',
              1 => 'group_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('newsletter_subscriber_group', array(
             'subscriber_id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'group_id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'subscriber_id',
              1 => 'group_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->dropTable('newsletter_message_category');
        $this->dropTable('newsletter_subscriber_category');
    }
}