<script src='/plugins/jrating/jRating.jquery.js'></script>
<link rel='stylesheet' href='/plugins/jrating/jRating.jquery.css'  />
<script type="text/javascript" src="/js/jquery.validate.min.js"></script>
<?php
$agent = $this->agent;
$form = $this->form;
?>
<script type="text/javascript">
    $(document).ready(function () {
        var agent_id = $('#agent_id').val();

	$( ".custompicker" ).datepicker({
            firstDay: 0,
            maxDate: new Date,
            'monthNames': ['<?= $this->translate('January'); ?>', '<?= $this->translate('February'); ?>', '<?= $this->translate('March'); ?>', 
            '<?= $this->translate('April'); ?>', '<?= $this->translate('May'); ?>', '<?= $this->translate('June'); ?>', '<?= $this->translate('July'); ?>', 
           '<?= $this->translate('August'); ?>', '<?= $this->translate('September'); ?>', '<?= $this->translate('October'); ?>', '<?= $this->translate('November'); ?>', 
            '<?= $this->translate('December'); ?>'],
            'dayNamesMin': ['<?= $this->translate('Mo'); ?>', '<?= $this->translate('Tu'); ?>', '<?= $this->translate('We'); ?>', 
            '<?= $this->translate('Th'); ?>', '<?= $this->translate('Fr'); ?>', '<?= $this->translate('Sa'); ?>', '<?= $this->translate('Su'); ?>']
        });
        $('input[name="recommend"]').on('click',function(){
           if($(this).val()=='1'){
                $('.change_mind').hide();
           }
           else{
                $('.change_mind').show();
           }
        });
        
        // more complex jRating call
        $("#rating").jRating({
            step: true,
            rateMax: 5,
            canRateAgain: true,
            nbRates: 1000,
            length: 5, // nb of stars
            onSuccess : function(review,rate){
                $('#rating_elem').val(rate);
              }
        });

        var bid = $('#branch').val();
        

        clear_dropdown(bid,agent_id,'',false,0);

        $('#branch').on('change', function () {
            var bid = $('#branch').val();


            clear_dropdown(bid,agent_id,'',false,0);
        });
        
        
        var timeout;

        var staff1letters = 0;
        $('#staff1').bind('paste keyup input', function () {

            var input = $(this);

            clearTimeout(timeout);
            
            timeout = setTimeout(function(){
                staff1letters = input.val().length;


                var bid = $('#branch').val();
                var query = input.val();
                var sid = $('#staff1_id').val();
                var listElement = $('#staff1_list');
                if (staff1letters > 2) {
                    $.ajax({
                        type: "POST",
                        dataType: "json",
                        url: "/staff/ajax/find-staff/",
                        data: {branch: bid, query: query, sid: sid,agent:agent_id},
                        success: function (response) {
                            listElement.html(response.result);
                            if (staff1letters > 2 && !listElement.is(':visible')) {
                                $('#staff1_list').slideDown(700);
                            }

                        }
                    });
                }
            }, 200);
            return false;
        });


        $('#staff1_list').on('click', 'li', function (e) {
            // if button to remove staff is clicked, remove staff
            var target = $(e.target);
            var element = $(this);
            if (target.attr('class') == 'removeStaff') {

                $('#staff1_list li.selected').remove();
                $('#staff1_id').val('');
                $('#staff1').val('');
                
                clear_dropdown(bid,agent_id,'',false,1);
            }
            // otherwise just select the staff member
            else {

                var id = $(this).attr('data-id');
                var name = $(this).attr('data-name');
                $('#staff1').val(name);
                $('#staff1_id').val(id);
                $('#staff1_list li.selected').removeClass('selected');
                $(this).addClass('selected');
                $('#staff1_list li').not('.selected').remove();
                staff1letters = 0;

                $(this).append('<button type="button" rel="1" class="removeStaff">x</button>')

                if (target.attr('class') == 'namespan noexists namespan3 addnewperson') {

                    element.find('.addnewperson').html('<i class="fa fa-check"></i> <?= $this->translate('Person added'); ?>')
                }
            }
        });

        var staff2letters = 0;
        $('#staff2').bind('paste keyup input', function () {

            var input = $(this);

            clearTimeout(timeout);
            
            timeout = setTimeout(function(){
                
                staff2letters = input.val().length;
                var bid = $('#branch').val();
                var query = input.val();
                var sid = $('#staff2_id').val();
                var listElement = $('#staff2_list');
                if (staff2letters > 2) {
                    $.ajax({
                        type: "POST",
                        dataType: "json",
                        url: "/staff/ajax/find-staff/",
                        data: {branch: bid, query: query, sid: sid,agent:agent_id},
                        success: function (response) {
                            listElement.html(response.result);
                            if (staff2letters > 2 && !listElement.is(':visible')) {
                                listElement.slideDown(700);
                            }

                        }
                    });
                }
            }, 200);
            return false;
        });


        $('#staff2_list').on('click', 'li', function (e) {
            // if button to remove staff is clicked, remove staff
            var target = $(e.target);
            var element = $(this);
            if (target.attr('class') == 'removeStaff') {

                $('#staff2_list li.selected').remove();
                $('#staff2_id').val('');
                $('#staff2').val('');
                clear_dropdown(bid,agent_id,'',false,2);
            }
            // otherwise just select the staff member
            else {

                var id = $(this).attr('data-id');
                var name = $(this).attr('data-name');
                $('#staff2').val(name);
                $('#staff2_id').val(id);
                $('#staff2_list li.selected').removeClass('selected');
                $(this).addClass('selected');
                $('#staff2_list li').not('.selected').remove();
                staff1letters = 0;

                $(this).append('<button type="button" rel="2" class="removeStaff">x</button>')

                if (target.attr('class') == 'namespan noexists namespan3 addnewperson') {

                    element.find('.addnewperson').html('<i class="fa fa-check"></i> <?= $this->translate('Person added'); ?>')
                }
            }
        });
        
        $('.step_wrapper input,.step_wrapper textarea,.step_wrapper select').on('focus', function () {
            var step_id = $(this).parents('.step_wrapper').attr('rel');
            $('.steps').removeClass('active');
            $('#step' + step_id).addClass('active');
        });
        
        $('#review').keyup(function() {
            if (null != $(this).val().match(/\b/g)) {
                var counter = $(this).val().match(/\b/g).length/2;
                $('#f_review_count').val(counter);
                if(counter=='1'){
                    $('#f_review_count2').html(counter + ' <?= $this->translate('word'); ?>');
                }
                else{
                    
                    $('#f_review_count2').html(counter + ' <?= $this->translate('words'); ?>');
                }
            }
        });

        jQuery.validator.addMethod("twentywords", function(value, element, param) {
            return ($('#f_review_count').val() > 19);
        }, "<?= $this->translate('Your review must contain at least 20 words'); ?>");


        $("#addreview").validate({
            rules: {
                review: {
                    twentywords: true
                }
            }
        });
        
        function clear_dropdown(bid,agent_id,query,sid,type){
            
            $.ajax({
                type: "POST",
                dataType: "json",
                url: "/staff/ajax/find-staff/",
                data: {branch: bid, query: query, sid: sid,agent:agent_id},
                success: function (response) {

                if(type==0){
                    var listElement = $('#staff1_list');
                    var listElement2 = $('#staff2_list');
                    listElement.html(response.result);
                    listElement2.html(response.result);

                    listElement.slideDown(700);
                    listElement2.slideDown(700);
                }
                else{
                    if(type == 1){
                        
                        var listElement = $('#staff1_list');
                        listElement.html(response.result);

                        listElement.slideDown(700);
                    }
                    else{
                        var listElement2 = $('#staff2_list');
                        listElement2.html(response.result);

                        listElement2.slideDown(700);
                    }
                }
                }
            });
        }
    });
</script>


<?php
MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $this->translate('Rate review') . " - " . $agent['name'], true);
echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>
<div class="container addReviewPage">

    <div class="container mt25 offset-0">


        <!-- LEFT CONTENT -->
        <div class="col-md-8 pagecontainer2 offset-0">


            <form id="addreview" class="add-review-form" name="add-review" method="post" >
                
                <div class="hpadding50c defaultheader2">
                    <h1><?= $this->translate('Rate review'); ?></h1>
                    <p class="aboutarrow"></p>
                </div>
                <div class="line3"></div>
                <div class="padding30 grey">

                    <span class="step_wrapper" rel="1">

                        <?= $this->form->agent_id; ?>
                        <span class="sectionHeader">1.<?= $this->translate('Select review rating and branch'); ?></span>
                        <div class="clearfix"></div>
                        <!--<div class="line4"></div>-->

                        <br />
                        <div class="col-lg-4 col-xs-12 textright col-sm-4">
                            <label for="rating">
                                <span>
                        <?= $this->translate('Your rating'); ?>
                                </span>
                                <span class="red">*</span>
                            </label>
                        </div>
                        <div class="col-lg-8 col-xs-12 col-sm-8">
                            <div id='rating' class="basic" data-average="12" data-id="1"></div>
                             <?= $this->form->rating; ?>
                        </div>

                        <div class="clearfix"></div>
                        <br />
                        <span class="whichOffice ">
                            <?= $this->translate('Select branch from the list. If you cannot find proper branch, enter the town of the branch in the box to the right.'); ?>
                        </span>
                        
                        <div class="clearfix"></div>
                        <div class="selectBranchWrapper">
                            <div class="col-md-4 col-xs-4">
                                <label for="branch"><span><?= $this->translate('Branch'); ?></span><span class="red">*</span></label>
                            </div>
                            <div class="col-md-4 col-xs-4 reviewBranchSelect">
                                <?= $this->form->branch; ?>
                            </div>
                            <div class="col-md-4 col-xs-4 reviewBranchNotListed">
                                <span class="size12"><?= $this->translate('Enter branch town if not listed'); ?>*</span>
                                <?= $this->form->other_branch; ?>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </span>
                    <br />
                    <span class="step_wrapper" rel="2">
                        <div class="line4"></div>
                        <span class="sectionHeader">2.<?= $this->translate('Allocate staff to the review (optional)'); ?>  </span>
                        <div class="clearfix"></div>
                       
                        <?= $this->translate('Select an existing staff member from the drop down list. If the staff member does not exist, type in his/her name'); ?> <br/><br/>


                        <div class="col-md-6">
                            <div class="staff_label">
                                <?= $this->translate('Staff Member'); ?> 1: 
                                <input class="form-control" type="text" id="staff1" name="staff1" />
                            </div>
                            <?= $this->form->staff1_id; ?>
                            <div id="staff1_list" class="review_staff_list"></div>
                        </div>

                        <div class="col-md-6 ">
                            <div class="staff_label">
                                <?= $this->translate('Staff Member'); ?> 2: 

                                <input  class="form-control" type="text" id="staff2"  name="staff2" />
                            </div>
                            <?= $this->form->staff2_id; ?>
                            <div id="staff2_list" class="review_staff_list"></div>
                        </div>
                        <div class="clearfix"></div>
                    </span>
                    <br />
                    <span class="step_wrapper" rel="3">
                        <div class="line4"></div>
                        <span class="sectionHeader">3. <?= $this->translate('Enter your review'); ?>  </span>
                        <div class="clearfix"></div>
                        <br /><br />
                        <div class="col-md-12 col-sm-12">
                            <?= $this->translate('Please note we do not accept postive reviews from prospective customers. Your review has to have at least 20 words'); ?><br/><br/>
                        
                            <?= $this->form->review; ?>
                            <input type="hidden" name="f_review_count" id="f_review_count" />
                            <div id="f_review_count2"></div>
                        </div>




                        <div class="clearfix"></div>

                        <br/>

                        <div class="col-md-4 col-xs-4">
                            <label for="recommend">
                                <span ><?= $this->translate('Would you recommend'); ?> <?= $this->translate('this company'); ?>?</span>
                                <span class="red">*</span>
                            </label>
                        </div>
                        <div class="col-md-8 isRecommendedRadio">
                            <div>
                                <?= $this->form->recommend; ?>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <style>
                            .change_mind{
                                display:none;
                            }
                        </style>
                        <div class="change_mind">
                            <br />
                            <div class="col-md-4 col-xs-4">
                                <label for="feedback">
                                    <span><?= $this->translate('What the company could have done to help you change your mind'); ?>?</span>
                                </label>
                            </div>
                            <div class="col-md-8 col-sm-8">
                                <?= $this->form->feedback; ?>
                            </div>
                        </div>

                        <div class="clearfix"></div>
                        <br />
                        <div class="col-md-4 col-xs-12">
                            <label for="display_name">
                                <span><?= $this->translate('Your display name'); ?></span><span class="red">*</span>
                            </label>
                        </div>
                        <div class="col-md-8 col-xs-12">
                            <?= $this->form->display_name; ?>
                        </div>
                        <div class="clearfix"></div>

                        <br />
                        <?= $this->translate('Please select the date when you used the services of this company most recently'); ?>
                            
                        <div class="clearfix"></div>
                        <br />
                        <div class="col-md-4 col-xs-12">
                            <label><span><?= $this->translate('Service date'); ?></span><span class="red">*</span>

                            </label>
                        </div>
                        <div class="col-md-8 col-xs-12">
                            <?= $this->form->service_date; ?>
                        </div>
                        <div class="clearfix"></div>

                       
                    </span>
                    <div class="clearfix"></div>
                    <span class="step_wrapper">

                        <div class="line4"></div>
                        <span class="sectionHeader">4. <?= $this->translate('Your details'); ?></span>
                        <div class="clearfix"></div>
                        <div class="alert-info alert alert-custom">
                            <strong><?= $this->translate('None of these contact details will be published or handed out.'); ?></strong> <br/>
                            <br/>

                            <div class="col-md-4 col-xs-12">
                                <label for="firstname"><span ><?= $this->translate('First name'); ?></span><span class="red">*</span></label>
                            </div>
                            <div class="col-md-8 col-xs-12">
                                <?= $this->form->firstname; ?>
                            </div>
                            <div class="clearfix"></div>

                            <br />
                            <div class="col-md-4 col-xs-12">
                                <label for="lastname"><span><?= $this->translate('Last name'); ?></span><span class="red">*</span></label>
                            </div>
                            <div class="col-md-8 col-xs-12">
                                <?= $this->form->lastname; ?>
                            </div>
                            <div class="clearfix"></div>



                            <br />
                            <div class="col-md-4 col-xs-12">
                                <label for="email"><span><?= $this->translate('Email'); ?></span><span class="red">*</span></label>
                            </div>
                            <div class="col-md-8 col-xs-12">
                                <?= $this->form->email; ?>
                            </div>
                            <div class="clearfix"></div>



                            <br />
                            <div class="col-md-4 col-xs-12">
                                <label for="phone"><?= $this->translate('Phone no'); ?></span></label>
                            </div>
                            <div class="col-md-8 col-xs-12">
                                <?= $this->form->phone; ?>
                            </div>
                            <br />
                            <div class="clearfix"></div>
                            <br />
                            <?= $this->translate('In order to prevent abuse on this website, our moderation team may contact yourself if there are any issues regarding the review.'); ?>
                        </div>



                    </span>

                    <br />
                    <p>
                        <?= $this->form->terms; ?>
                        <label for="f_terms"><span style="color:Red;">*</span>
                            <?= $this->translate('I have read and understood the rules above, and hereby agree to the'); ?> <a target="_blank" href="<?= $this->url(array(),'domain-terms-conditions'); ?>"><?= $this->translate('Terms and Conditions'); ?></a> <?= $this->translate('of this website.'); ?> <?= $this->translate('I also confirm this review is based on my direct experience with the company, and is truthful, honest and fair.'); ?></label>
                    </p>
                    <p>
                        <?= $this->form->assoc; ?>
                        <label for="f_assoc"><span style="color:Red;">*</span><?= $this->translate('I confirm that I am not associated with this company in any other way than as an existing or past customer. I understand the consequences of attempting to influence a ranking by posting a false or misleading review.'); ?></label>
                    </p>

                    <?= $this->form->agent_id; ?>
                    <?= $this->form->submit; ?>


                </div>

            </form>
        </div>
        <!-- END OF LEFT CONTENT -->

        <!-- RIGHT CONTENT -->
        <div class="col-md-4" >

            <div class="detailsright offset-0 pagecontainer2 needassistancebox">
                <div class="padding20">
                    <h1 class="h2 mt0"><a href='<?= $this->url(array('slug' => $agent['link']),'domain-agent-details'); ?>'><?= $agent['name']; ?></a></h1>
                <span class="stars">
                    <?= str_repeat('<img src="/images/star.png">',round($agent['rating'])); ?>
                </span>
            </div>
                
            <?php if($agent['premium_support']){ ?>
                <img src="<?= $agent->getLogoUrl('225x90'); ?>" alt="<?= $agent['name'];?> logo" class="agentMainLogo" />
                <div class="line3"></div>
            <?php } ?>

            <div class="line3"></div>
                <div class="col-md-6 bordertype1 padding20">
                    <span class="opensans size30 bold grey2"><?= ($agent['customer_satisfaction']*100); ?>%</span><br/>
                    <?= $this->translate('of customers'); ?><br/><?= $this->translate('recommends'); ?>
                </div>
                <div class="col-md-6 bordertype2 padding20">
                    <span class="opensans size30 bold grey2"><?= $agent['rating']; ?></span>/5<br/>
                    <?= $this->translate('customers ratings'); ?>
                </div>

                <div class="col-md-6 bordertype3">
                    <?= $agent['votes']; ?> <?= $this->translate('reviews'); ?>
                </div>
                <div class="col-md-6 bordertype3">
                </div>
                <div class="clearfix"></div>

            </div>
            <br />

            <div class="pagecontainer2 needassistancebox">
                <div class="cpadding1 pl20" >
                    <span class="icon-lock"></span>
                    <h3 class="opensans"><?= $this->translate('Rules'); ?></h3>
                    <div class="p15 overflow">
                        <ul class="blogcat" style="list-style-type:disc">
                            <li><?= $this->translate('We welcome all constructive reviews.'); ?></li>
                            <li><?= $this->translate('Be honest and fair.'); ?></li>
                            <li><?= $this->translate('Review only companies you have direct experience with.'); ?></li>
                            <li><?= $this->translate('Use of any offensive language is not acceptable.'); ?></li>
                            <li><?= $this->translate('Usage of temporary email addresses are forbidden.'); ?></li>
                            <li><?= $this->translate('You are allowed to add only 1 review of certain company every 6 months.'); ?></li>
                            <li><?= $this->translate('We do not accept any reviews added within company network.'); ?></li>
                            <li><?= $this->translate('We moderate every reviews checking multiple factors. The moderation process may take up to 7 days.'); ?></li>
                            <li><?= $this->translate('Read our'); ?> <a href="<?= $this->url(array(),'domain-terms-conditions'); ?>" target="_blank" class="modal-terms"><?= $this->translate('Terms and Conditions'); ?></a> <?= $this->translate('before you publish a review.'); ?></li>
                        </ul>
                    </div>
                </div>
            </div><br/>
            
            
        </div>
        <!-- END OF RIGHT CONTENT -->


    </div>


</div>
