Wiadomość kontaktowa ze strony
    
    <br /><br />
    
    <?php
    echo $this->translate('First and last name')." - ".$this->values['name']."<br />";
    echo $this->translate('Email')." - ".$this->values['email']."<br />";
    echo $this->translate('Phone')." - ".$this->values['telephone']."<br />";
    echo $this->translate('Company')." - ".$this->values['company']."<br />";
    echo "<br /><br />";
    echo nl2br($this->values['message']);
?>
<br /><br />
<?= $this->translate('Kind regards'); ?>, <br />
<?= $this->translate('Rate Pole'); ?>

