<?= $this->translate('Dear')." ".$this->branch['Agent']['name']." ".$this->branch['office_name']; ?><br /><br />
<?= $this->translate('We received a new client enquiry to our website which your company might be interested in. Please see the details below:');?><br />
<br />
<?php
    echo $this->translate('First and last name')." - ".$this->values['name']."<br />";
    echo $this->translate('Email')." - ".$this->values['email']."<br />";
    echo $this->translate('Phone')." - ".$this->values['phone']."<br />";
    echo $this->translate('Address')." - ".$this->values['address']." ".$this->values['town']." ".$this->values['postcode']."<br />";
    echo "<br /><br />";
    echo nl2br($this->values['message']);
?>
<br /><br />
<?= $this->translate('Please do not hesitate to contact this customer as it may be new business opportunity for you.');?><br /><br />
<?= $this->translate('Kind regards'); ?>, <br />
<?= $this->translate('Rate Pole'); ?>

