<?= $this->translate('Dear')." ".$this->branch['Agent']['name']." ".$this->branch['office_name']; ?><br /><br />
<?= $this->translate('You have new customer enquiry through Rate Pole. Please see the details below:');?><br /><br />
<?php
    echo $this->translate('First and last name')." - ".$this->values['firstname']." ".$this->values['lastname']."<br />";
    echo $this->translate('Email')." - ".$this->values['email']."<br />";
    echo $this->translate('Phone')." - ".$this->values['phone']."<br />";
    echo "<br /><br />";
    echo nl2br($this->values['message']);
?>
<br /><br />
<?= $this->translate('Please do not hesitate to contact this customer as it may be new business opportunity for you.');?><br /><br />
<?= $this->translate('Kind regards'); ?>, <br />
<?= $this->translate('Rate Pole'); ?>

