<?php
$staff = $this->staff;
$branch = $this->staff['Branch'];
$agent = $this->staff['Agent'];
?>


<?php
    MF_View_Helper_Breadcrumb::getInstance()->addLink($this->url(array('slug' => $agent['link']),'domain-agent-details'), $agent['name']);
    MF_View_Helper_Breadcrumb::getInstance()->addLink($this->url(array('agent' => $agent['link'],'slug' => $branch['office_link']),'domain-branch-details'), $branch['office_name']);
    MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $staff['firstname']." ".$staff['lastname'], true);
    echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>



<div class="container">
    <?= MF_Text::showFormMessages(); ?>
    <div class="container pagecontainer offset-0">	

        <!-- SLIDER -->
        <div class="col-md-8 details-slider staff-content-wrapper">
            <div class="col-md-4">
                            <img src="<?= $this->staff->getPictureUrl('265x265'); ?>" alt="<?= $staff['firstname']." ".$staff['lastname']; ?>" class="img-responsive"/>
            </div>
            <div class="col-md-8">
                <div class="staff-description">
                    <?php 
                    if(strlen($staff['position'])){
                        echo $staff['position']." ".$this->translate('in')." ".$agent['name']."<br /><br />";
                    }

                    if(strlen($staff['Translation'][$this->language]['description'])){
                        echo $staff['Translation'][$this->language]['description']; 
                    } 
                    else{
                        echo $this->translate('This employee has no description available');
                    }

                    ?>

                </div>
            </div>
            <div class="clearfix"></div>
            <hr />
            
                <div class="col-md-6 ">
                <a href="<?= $this->url(array('agent' => $agent['link'],'branch' => $branch['office_link']),'domain-add-review-branch'); ?>" class="booknow margtop20 btnmarg"><?= $this->translate('Add review'); ?></a>
                </div>

        </div>
        <!-- END OF SLIDER -->			

        <!-- RIGHT INFO -->
        <div class="col-md-4 detailsright offset-0">
            <div class="padding20">
                <h1 class="h2 mt0 lato"><?= $staff['firstname']." ".$staff['lastname']; ?></h1>
                <span class="stars">
                    <?= str_repeat('<img src="/images/star.png">',round($staff['rating'])); ?>
                </span>
            </div>

            <div class="line3"></div>



            <div class="col-md-6 bordertype1 padding20">
                <span class="opensans size30 bold grey2"><?= ($staff['customer_satisfaction']*100); ?>%</span><br/>
                <?= $this->translate('of customers'); ?><br/><?= $this->translate('recommends'); ?>
            </div>
            <div class="col-md-6 bordertype2 padding20">
                <span class="opensans size30 bold grey2"><?= $staff['rating']; ?></span>/5<br/>
                <?= $this->translate('customers ratings'); ?>
            </div>
           
            <div class="line3"></div>
            <div class="col-md-6 bordertype3">
                <?= $staff['active_reviews']; ?> <?= $this->translate('reviews'); ?>
            </div>
            <div class="col-md-6 bordertype3">
                <a href="<?= $this->url(array('id' => $staff['id']),'domain-update-staff'); ?>" class="grey underline"><?= $this->translate('Edit details'); ?></a>
            </div>

        </div>
        <!-- END OF RIGHT INFO -->

    </div>
    <!-- END OF container-->

    <div class="container mt25 offset-0">

        <div class="col-md-8 pagecontainer2 offset-0">
            <div class="cstyle10"></div>

            <ul class="nav nav-tabs" id="myTab">
                <li class="active"><a data-toggle="tab" href="#reviews"><span class="reviews"></span><span class="hidetext"><?= $this->translate('Reviews'); ?></span>&nbsp;</a></li>
            </ul>			
            <div class="tab-content4" >

                <?= $this->render('index/reviews.phtml'); ?>

            </div>
        </div>

        <div class="col-md-4" >

            <div class="pagecontainer2 needassistancebox">
                <div class="cpadding1">
                    <span class="icon-help"></span>
                    <h3 class="opensans"><?= $this->translate('Contact'); ?></h3>
                     <?php echo $branch['address']." <br />";
                            echo $branch['postcode'].", ".$branch['town'];
                        ?>
                        <?php if(strlen($branch['phone'])){ ?>
                            <p class="opensans size30 lblue xslim"><?= $branch['phone']; ?></p>
                        <?php } ?>
                        <?php if(strlen($branch['url'])){
                            $url = $branch['url'];
                            if (strpos($url, 'http://')==false) {
                                $url = 'http://'.$url;
                             }
                            ?>
                            <p class="size14 grey">WWW: <a target="_blank" href='<?= $url; ?>'><?= $branch['url']; ?></a></p>
                        <?php } ?>
                </div>
            </div>

            <div class="pagecontainer2 mt20 alsolikebox">
                <div class="cpadding1">
                    <span class="icon-location"></span>
                    <h3 class="opensans"><?= $this->translate('Working hours'); ?></h3>
                    <div class="clearfix"></div>
                    <?php 
                    if(count($branch['OpeningHours'])>0){
                        $openingHours = array();
                        foreach($branch['OpeningHours'] as $hour): 
                            $openingHours[$hour['day_id']] = $hour;
                        endforeach;
                        ksort($openingHours);

                        echo '<ul class="sidebar-opening-hours">';
                        foreach($openingHours as $day_id => $day):
                            echo '<li ';
                            if($day_id == date('N'))
                            {
                                echo 'class="current"';
                            }
                            echo '>';
                                if($this->language=='pl'){
                                    echo MF_Text::polishDayOfWeek($day_id);
                                }
                                else{
                                    echo MF_Text::dayOfWeek($day_id);
                                }
                                echo '<span class="pull-right">';
                                    if($day['closed']){
                                        echo $this->translate('Closed');
                                    }
                                    else{
                                        echo substr($day['from'],0,5)." - ".substr($day['to'],0,5);
                                    }

                                echo '</span>';
                            echo '</li>';
                        endforeach;
                        echo '</ul>';
                    }
                    else{
                        echo $this->translate('No data');
                    }
                    ?>
                </div>
                
                <br/>


            </div>				

        </div>
    </div>



</div>
