<?php

/**
 * Property_Model_Doctrine_AlertTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Property_Model_Doctrine_AlertTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Property_Model_Doctrine_AlertTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Property_Model_Doctrine_Alert');
    }
}