<?php

/**
 * Property_Model_Doctrine_Alert
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Property
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Property_Model_Doctrine_Alert extends Property_Model_Doctrine_BaseAlert
{

}