<?php

/**
 * Property_Model_Doctrine_PropertyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Property_Model_Doctrine_PropertyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Property_Model_Doctrine_PropertyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Property_Model_Doctrine_Property');
    }
}