<!DOCTYPE HTML>
<html lang = "en">
	<head>
		<?php echo $this->render('_head.phtml'); ?>
	</head>

	<body>

		<a href="#dat-menu" class="ot-menu-toggle"><i class="fa fa-bars"></i>Toggle Menu</a>
		<div class="boxed active">
			
			<header class="header">
				<?php echo $this->render('_header.phtml'); ?>
			</header>
			
			<section class="content">
				
				<div class="wrapper">
					

					<?php echo $this->layout()->breakingNews; ?>


					<div class="main-content has-sidebar">
                                            
						<div class="left-content">
							<?php echo $this->layout()->content; ?>
						</div>
                                                
                                                <aside id="sidebar">
							
							<?php echo $this->layout()->bannerRight; ?>
                                                    
							<?php echo $this->layout()->lastNewsSidebar; ?>
							
							<?php echo $this->layout()->bannerSidebar2; ?>
                                                    
							<?php echo $this->layout()->nextEvents; ?>
                                                    
							<?php echo $this->layout()->bannerSidebar3; ?>
							
							<?php echo $this->layout()->mainPageGalleries; ?>
							
						</aside>
					</div>
					
				</div>
				
			</section>
			
			
       <?php echo $this->render('_footer.phtml'); ?>
		</div>

	</body>
</html>