<!DOCTYPE html> 
<html>
<head>
    <?= $this->render('_head.phtml'); ?>
</head>

<body>
    <div class="root">
	<header class="h10 sticky-enabled no-topbar">
	<?= $this->render('_header.phtml'); ?>
	</header>
       
	<section class="content reverse toup">
		<section class="main">
			<?php echo $this->layout()->content; ?>
		</section>
	</section>
        <?= $this->render('_footer.phtml'); ?>
    </div>
</body>

</html>