
<!DOCTYPE html>
<html>
  <?= $this->render('_head.phtml'); ?>
  <body id="top">
    
      
	<?= $this->render('_header.phtml'); ?>


	<?= $this->layout()->slider; ?>

      <?= $this->layout()->content; ?>
		



	<?= $this->render('_footer.phtml'); ?>
	
<!--     Javascript 
	
     This page JS 
	<script src="assets/js/js-index3.js"></script>	
	
     Custom functions 
    <script src="assets/js/functions.js"></script>
	
     Picker UI	
	<script src="assets/js/jquery-ui.js"></script>		
	
	 Easing 
    <script src="assets/js/jquery.easing.js"></script>
	
     jQuery KenBurn Slider  
    <script type="text/javascript" src="rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
	
    Nicescroll  	
	<script src="assets/js/jquery.nicescroll.min.js"></script>
	
     CarouFredSel 
    <script src="assets/js/jquery.carouFredSel-6.2.1-packed.js"></script>
    <script src="assets/js/helper-plugins/jquery.touchSwipe.min.js"></script>
	<script type="text/javascript" src="assets/js/helper-plugins/jquery.mousewheel.min.js"></script>
	<script type="text/javascript" src="assets/js/helper-plugins/jquery.transit.min.js"></script>
	<script type="text/javascript" src="assets/js/helper-plugins/jquery.ba-throttle-debounce.min.js"></script>
	
     Custom Select 
	<script type='text/javascript' src='assets/js/jquery.customSelect.js'></script>	

     Include all compiled plugins (below), or include individual files as needed 
    <script src="dist/js/bootstrap.min.js"></script>-->
  </body>
</html>
