<div class="single-block">
    <!-- BEGIN .content-block -->
    <div class="content-block main left">
        <div class="block">



            <div class="block-title">
                <h2>Regulamin</h2>
            </div>
            <div class="block-content">
               <?= $this->page['Translation'][$this->language]['content']; ?>
            </div>


        </div>
        <!-- END .content-block -->
    </div>
    <!-- END .single-block -->
</div>
