<?php
$branch = $this->branch;
$agent = $this->agent;
if(count($agent['Branches'])>1){
    $branchName = $agent['name']." ".$branch['office_name'];
}
else{
    $branchName = $agent['name'];
}
?>

<?php
    MF_View_Helper_Breadcrumb::getInstance()->addLink($this->url(array('slug' => $agent['link']),'domain-agent-details'), $agent['name']);
    MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $branch['office_name'], true);
    echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>



<div class="container companyBranchDetails">
    <div class="container pagecontainer offset-0">

    <?= MF_Text::showFormMessages(); ?>
        <!-- SLIDER -->
        <div class="col-md-8 details-slider">
            <div class="company-ad">
                <img src="<?= $agent->getAdUrl('728x90'); ?>" alt="<?= $agent['name'];?> advertisment" />
            </div>
            
        </div>
        
        <div class="col-md-4 detailsright detailsright2 offset-0">
            <div class="padding20">
                <h1 class="h2 mt0 lato"><?php
                
                if(count($agent['Branches'])>1){
                    echo "<a href='".$this->url(array('slug' => $agent['link']),'domain-agent-details')."'>".$agent['name']."</a><br /> ".$branch['office_name']; 
                }
                else{
                    echo $agent['name']; 
                }
                ?></h1>
                <span class="stars">
                    <?= str_repeat('<img src="/images/star.png">',round($branch['rating'])); ?>
                </span>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="line3"></div>
        
            
            
            
            
        <div class="col-md-8 details-slider">
            <div class="company-description">
                <?php 
                
                if(strlen($branch['Agent']['Translation'][$this->language]['description'])){
                    echo $branch['Agent']['Translation'][$this->language]['description']; 
                } 
                else{
                    echo $this->translate('This company has no description available');
                }
                
                ?>

            </div>
            
            <div class="line3"></div>
            
            <div class="hpadding20">
                <div class=" col-md-6">
                    <a href="<?= $this->url(array('agent' => $agent['link'],'slug' => $branch['office_link']),'domain-branch-contact'); ?>" class="add2fav margtop20"><?= $this->translate('Contact company'); ?></a>
                </div>
                <div class=" col-md-6">
                    <a href="<?= $this->url(array('agent' => $agent['link'],'branch' => $branch['office_link']),'domain-add-review-branch'); ?>" class="booknow btnmarg margtop20"><?= $this->translate('Add review'); ?></a>
                </div>
            </div>

        </div>
        <!-- END OF SLIDER -->			

        <!-- RIGHT INFO -->


        <div class="col-md-4 detailsright offset-0">
            
            <div class="col-md-6 bordertype1 padding20">
                <span class="opensans size30 bold grey2"><?= ($branch['customer_satisfaction']*100); ?>%</span><br/>
                <?= $this->translate('of customers'); ?><br/><?= $this->translate('recommends'); ?>
            </div>
            <div class="col-md-6 bordertype2 padding20">
                <span class="opensans size30 bold grey2"><?= (float)$branch['rating']; ?></span>/5<br/>
                <?= $this->translate('customers ratings'); ?>
            </div>
           
            <div class="col-md-6 bordertype3">
                <?= (int)$branch['votes']; ?> <?= $this->translate('reviews'); ?>
            </div>
            <div class="col-md-6 bordertype3">
                <a href="<?= $this->url(array(),'domain-login'); ?>" class="grey underline"><?= $this->translate('Edit details'); ?></a>
            </div>
            <div class="clearfix"></div>

        </div>
        <!-- END OF RIGHT INFO -->

    </div>
    <!-- END OF container-->

    <div class="container mt25 offset-0">

        <div class="col-md-8 pagecontainer2 offset-0">
            <div class="cstyle10"></div>

            <ul class="nav nav-tabs" id="myTab">
                <li class="active"><a data-toggle="tab" href="#reviews"><span class="reviews"></span><span class="hidetext"><?= $this->translate('Reviews'); ?></span>&nbsp;</a></li>
                <li><a data-toggle="tab" href="#staff-members"><span class="summary"></span><span class="hidetext"><?= $this->translate('Staff members'); ?></span>&nbsp;</a></li>

            </ul>			
            <div class="tab-content4" >


                <?= $this->render('index/reviews.phtml'); ?>
                <?= $this->partial('index/staff-members.phtml',array('branch' => $branch)); ?>

            </div>
        </div>

        <div class="col-md-4" >

            
            <?php if($agent['premium_support']){ ?>
                <img src="<?= $agent->getLogoUrl('225x90'); ?>" alt="<?= $agent['name'];?> logo" class="agentMainLogo" />
                <div class="line3"></div>
            <?php } ?>
            
            <div class="pagecontainer2 needassistancebox">
                <div class="cpadding1">
                    <span class="icon-help"></span>
                    <h3 class="opensans"><?= $this->translate('Contact'); ?></h3>
                     <?php echo $branch['address']." <br />";
                            echo $branch['postcode'].", ".$branch['town'];
                        ?>
                        <?php if(strlen($branch['phone'])){ ?>
                            <p class="opensans size30 lblue xslim"><?= $branch['phone']; ?></p>
                        <?php } ?>
                        <?php if(strlen($branch['url'])){
                            $url = $branch['url'];
                            if (strpos($url, 'http://')==false) {
                                $url = 'http://'.$url;
                             }
                            ?>
                            <p class="size14 grey">WWW: <a target="_blank" href='<?= $url; ?>'><?= $branch['url']; ?></a></p>
                        <?php } ?>
                </div>
            </div>
                
                <?php if(strlen($branch['lng'])){ ?>
                <br/>
            <style>
      #map {
        width: 355px;
        height: 190px;
      }
    </style>
  </head>
            <script src="https://maps.googleapis.com/maps/api/js?callback=initMap" async defer></script>
            <div class="needassistancebox" id="map"></div>
            <script>
              function initMap() {
                var mapDiv = document.getElementById('map');
                var map = new google.maps.Map(mapDiv, {
                  center: {lat: <?= $branch['lat']; ?>, lng: <?= $branch['lng']; ?>},
                  zoom: 9
                });
                var marker = new google.maps.Marker({
                    position: {lat: <?= $branch['lat']; ?>, lng: <?= $branch['lng']; ?>},
                    map: map,
                    title: '<?= $branchName; ?>'
                  });
              }
            </script>
                <?php } ?>
            <div class="pagecontainer2 mt20 alsolikebox">
                <div class="cpadding1">
                    <span class="icon-location"></span>
                    <h3 class="opensans"><?= $this->translate('Opening hours'); ?></h3>
                    <div class="clearfix"></div>
                    <?php 
                    if(count($branch['OpeningHours'])>0){
                        $openingHours = array();
                        foreach($branch['OpeningHours'] as $hour): 
                            $openingHours[$hour['day_id']] = $hour;
                        endforeach;
                        ksort($openingHours);

                        echo '<ul class="sidebar-opening-hours">';
                        foreach($openingHours as $day_id => $day):
                            echo '<li ';
                            if($day_id == date('N'))
                            {
                                echo 'class="current"';
                            }
                            echo '>';
                                if($this->language=='pl'){
                                    echo MF_Text::polishDayOfWeek($day_id);
                                }
                                else{
                                    echo MF_Text::dayOfWeek($day_id);
                                }
                                echo '<span class="pull-right">';
                                    if($day['closed']){
                                        echo $this->translate('Closed');
                                    }
                                    else{
                                        echo substr($day['from'],0,5)." - ".substr($day['to'],0,5);
                                    }

                                echo '</span>';
                            echo '</li>';
                        endforeach;
                        echo '</ul>';
                    }
                    else{
                        echo $this->translate('No data');
                    }
                    ?>
                </div>
                
                <br/>


            </div>				

        </div>
    </div>



</div>
