<?php
MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $this->translate('Find company'), true);
echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>
<div class="container">

    <div class="container mt25 offset-0">


        <!-- LEFT CONTENT -->
        <div class="col-md-8 pagecontainer2 offset-0">
            <div class="padding30 grey">
                <div class="hpadding50c defaultheader">
                    <h1 class="h2 mt0"><?= $this->translate('Find company'); ?></h1>
                    <p class="aboutarrow"></p>
                </div>
                <div class="line3"></div>
                <br />
                <div class="bs-example bs-example-tabs">


                    <div class="tab-content3" id="myTabContent">
                        <div id="air" class="tab-pane fade active in">

                            <form method='GET' action='<?= $this->url(array(), 'domain-search-company'); ?>'>
                                <?= $this->form->area; ?>
                                <br />
                                <?= $this->form->category_id; ?>
                                <br />
                                <?= $this->form->name; ?>
                            </form>

                        </div>

                        <div class="" style='background:none;'>
                            <button type="submit" id='searchHomepage' class="btn-search"><?= $this->translate('Search'); ?></button>
                        </div>
                    </div>
                    <div class='clearfix'></div>


                </div>

                <hr />

                <div class="hpadding50c defaultheader">
                    <h2><?= $this->translate('Find company by category'); ?></h2>
                    <p class="aboutarrow"></p>
                </div>
                <div class="line3"></div>
                <div class='clearfix'></div>

                <?php foreach ($this->agentCategories as $key => $category): ?>
                    <div class="col-md-4">
                        <h3 class="black h4"><?= $category['Translation'][$this->language]['title']; ?></h3>
                        <ul class="small-padding">
                            <?php foreach ($category->getNode()->getChildren() as $subcategory): ?>
                                <li>
                                    <a href="<?= $this->url(array(), 'domain-area-search'); ?>?category[]=<?= $subcategory['id']; ?>">
                                        <?= $subcategory['Translation'][$this->language]['title']; ?>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <?php
                    if ($key % 3 == 2) {
                        echo '<div class="clearfix"></div>';
                    }

                endforeach;
                ?>
                <div class="clearfix"></div>
            </div>
        </div>
        <!-- END OF LEFT CONTENT -->

        <!-- RIGHT CONTENT -->
        <div class="col-md-4" >



<?php echo $this->action('banner-sidebar2', 'index', 'banner'); ?>


        </div>
        <!-- END OF RIGHT CONTENT -->


    </div>


</div>

<script>

    $(function () {
    $("#category").select2();
        $('#searchHomepage').on('click', function () {
            $('.tab-pane.active form').submit();
        });

        $('#air form').on('submit', function () {
            var form = $(this);
            var area = $('#area').val().toLowerCase();

            form.attr('action', form.attr('action') + '/' + area);
            $('#area').val('');
        });

    });
</script>
