<?php

/**
 * Supplier_Model_Doctrine_BaseContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $supplier_id
 * @property string $firstname
 * @property string $lastname
 * @property string $position
 * @property string $email
 * @property string $tel
 * @property Supplier_Model_Doctrine_Supplier $Supplier
 * 
 * @package    Admi
 * @subpackage Supplier
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Supplier_Model_Doctrine_BaseContact extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('supplier_contact');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('supplier_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('firstname', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('lastname', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('position', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('tel', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Supplier_Model_Doctrine_Supplier as Supplier', array(
             'local' => 'supplier_id',
             'foreign' => 'id'));
    }
}