<?php

/**
 * Supplier_Model_Doctrine_Review
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Supplier
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Supplier_Model_Doctrine_Review extends Supplier_Model_Doctrine_BaseReview
{

}