<?php

/**
 * Supplier_Model_Doctrine_SupplierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Supplier_Model_Doctrine_SupplierTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Supplier_Model_Doctrine_SupplierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Supplier_Model_Doctrine_Supplier');
    }
}