<?php

/**
 * Agent_Model_Doctrine_Agent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Agent
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Agent_Model_Doctrine_Agent extends Agent_Model_Doctrine_BaseAgent
{
    public static $agentPhotoDimensions = array(
        '126x126' => 'Photo in admin panel',                  // admin
        '225x90' => 'Very main',
        '200x150' => 'Main',
        '250x150' => 'Main2',
        '150x80' => 'Directory search',
        '85x50' => 'Najnowsze informacje(85x50)',
    );
    
    public static function getAgentPhotoDimensions() {
        return self::$agentPhotoDimensions;
    }
    
    public function increaseView(){
        $this->views++;
        $this->save();
    }
    
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Media_Model_Doctrine_Photo as LogoRoot', array(
             'local' => 'logo_root_id',
             'foreign' => 'id'));
        
        $this->hasOne('Media_Model_Doctrine_Photo as AdRoot', array(
             'local' => 'ad_root_id',
             'foreign' => 'id'));
        
         $this->hasMany('Staff_Model_Doctrine_Staff as StaffMembers', array(
             'local' => 'id',
             'foreign' => 'agent_id'));
        
         $this->hasMany('Branch_Model_Doctrine_Branch as Branches', array(
             'local' => 'id',
             'foreign' => 'agent_id'));
         
         $this->hasOne('Branch_Model_Doctrine_Branch as HeadOffice', array(
             'local' => 'head_office_id',
             'foreign' => 'id'));
         
         
         $this->hasOne('User_Model_Doctrine_User as User', array(
             'local' => 'id',
             'foreign' => 'agent_id'));
    }
    
     public function getLogoUrl($dimensions = '200x150'){
        if($this->get('LogoRoot')&&file_exists(APPLICATION_PATH."/../public_html/".MF_Text::getPhotoPath($this->get('LogoRoot'),$dimensions))){
            return MF_Text::getPhotoPath($this->get('LogoRoot'),$dimensions);
        }
        else{
            return 'http://placehold.it/'.$dimensions.'?text=Brak+logo';
        }
    }
    
    public function getAdUrl($dimensions = '728x90'){
        if($this->get('AdRoot')&&file_exists(APPLICATION_PATH."/../public_html/".MF_Text::getPhotoPath($this->get('AdRoot'),$dimensions))&&$this->premium_support = 1){
            return MF_Text::getPhotoPath($this->get('AdRoot'),$dimensions);
        }
        else{
            return Advertising_Model_Doctrine_Advertising::getDefaultAd($dimensions);
        }
    }
    
}