<?php

/**
 * Agent_Model_Doctrine_Awards
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Agent
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Agent_Model_Doctrine_Awards extends Agent_Model_Doctrine_BaseAwards
{

}