<?php

/**
 * Agent_Model_Doctrine_BaseAgentCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $agent_id
 * @property integer $category_id
 * 
 * @package    Admi
 * @subpackage Agent
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Agent_Model_Doctrine_BaseAgentCategory extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('agent_agent_category');
        $this->hasColumn('agent_id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}