<?php

/**
 * Agent_Model_Doctrine_BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $route
 * @property string $target_id
 * @property string $target_href
 * @property integer $metatag_id
 * @property string $title
 * @property string $slug
 * @property string $unique_id
 * @property Doctrine_Collection $Agents
 * @property Doctrine_Collection $Translation
 * 
 * @package    Admi
 * @subpackage Agent
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Agent_Model_Doctrine_BaseCategory extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('agent_category');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('route', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('target_id', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('target_href', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('metatag_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('unique_id', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Agent_Model_Doctrine_Agent as Agents', array(
             'refClass' => 'Agent_Model_Doctrine_AgentCategory',
             'local' => 'category_id',
             'foreign' => 'agent_id'));

        $this->hasMany('Agent_Model_Doctrine_CategoryTranslation as Translation', array(
             'local' => 'id',
             'foreign' => 'id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'slug',
              1 => 'title',
             ),
             'tableName' => 'agent_category_translation',
             'className' => 'CategoryTranslation',
             ));
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($i18n0);
        $this->actAs($nestedset0);
    }
}