<?php

/**
 * Agent_Model_Doctrine_BasePostcode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $postcode
 * @property clob $radius0
 * @property clob $radius1
 * @property clob $radius5
 * @property clob $radius10
 * @property clob $radius20
 * 
 * @package    Admi
 * @subpackage Agent
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Agent_Model_Doctrine_BasePostcode extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('agent_postcode');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('postcode', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('radius0', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('radius1', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('radius5', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('radius10', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('radius20', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}