<?php

/**
 * Agent_Model_Doctrine_CategoryTranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Agent_Model_Doctrine_CategoryTranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Agent_Model_Doctrine_CategoryTranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Agent_Model_Doctrine_CategoryTranslation');
    }
}