<?php
    MF_View_Helper_Breadcrumb::getInstance()->addLink($this->url(array(),'domain-advertisment'), $this->translate('Advertisments'));
    MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $this->translate('Add advertisment'), true);
    echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>
<div class="container">


    <div class="container mt25 offset-0 advertismentList addAdvertismentStep1">

        <!-- LEFT CONTENT -->
        <div class="col-md-8 pagecontainer2 offset-0 advertismentCategoryList">
            <div class="hpadding50c">
                <h1 class="lato size30 slim"><?= $this->translate('Add advertisment'); ?></h1>
                <p class="aboutarrow"></p>
            </div>
            <div class="line3"></div>
            <div class="padding10 grey ">
                <div class="col-md-12">
                    <h2><?= $this->translate('Select advertisment category'); ?></h2>
                     <?php foreach($this->groupAndCategories as $key => $groups): ?>

                        <div class="col-md-4">
                            <h3 class="list-title"><?= $groups['Translation'][$this->language]['title']; ?></h3>
                                    <ul class="article-list">
                                        <?php foreach($groups['Categories'] as $category): ?>
                                            <li><a href="<?= $this->url(array('category' => $category['Translation'][$this->language]['slug']),'domain-add-advertisment-category'); ?>"><?= $category['Translation'][$this->language]['title']; ?></a></li>
                                        <?php endforeach; ?>
                                    </ul>
                        </div>
                        <?php if($key%3==2): ?>
                            <div class="clearfix"></div>

                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <?php echo $this->action('banner-sidebar2','index','banner'); ?>
        </div>
        
        <div class="clearfix"></div>
    </div>


</div>
