<div class="row anim3">
    <div class="col-md-3">
        <h2><?= $this->translate('Latest advertisments'); ?></h2><br/>
        <?= $this->translate('See advertisments for Polish employees.'); ?>
    </div>
    <div class="col-md-9">

        <!-- Carousel -->
        <div class="wrapper">
            <div class="list_carousel homepageFeaturedList">		
                <ul id="foo3" class="carousel_homepage">
                    <?php foreach ($this->lastAds as $advertisment):
                        ?>
                        <li>
                            <a href="<?= $this->url(array('category' => $advertisment['Category']['Translation'][0]['slug'], 'slug' => $advertisment['Translation'][$this->language]['slug']), 'domain-single-advertisment'); ?>">
                                <img class="fwimg" style="max-width:200px;"
                                     src="<?php echo (strlen($advertisment['Photos'][1]['filename']) ? MF_Text::getPhotoUrl($advertisment['Photos'][1]) : '/assets/images/photos/image-10.jpg'); ?>" 
                                     alt="<?= $advertisment['Translation'][$this->language]['title']; ?>" />
                            </a>
                            <div class="m1">
                                <h5 class="dark"><b><?= $advertisment['Translation'][$this->language]['title']; ?> </b></h5>
                                <span class="lh1 green size10"><?= $advertisment['Category']['Translation'][0]['title']; ?></span>							
                            </div>							
                        </li>
                    <?php endforeach; ?>
                </ul>
                <div class="clearfix"></div>
                <a id="prev_btn2" class="prev" href="#"><img src="/assets/images/spacer.png" alt=""/></a>
                <a id="next_btn2" class="next" href="#"><img src="/assets/images/spacer.png" alt=""/></a>
            </div>
        </div>

    </div>
</div>