
 <h3 class="page-title"> <?= $this->translate('Welcome to user panel'); ?></h3>
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <i class="icon-home"></i>
                                <!--<a href="<?= $this->url(array(),'domain-account'); ?>">-->
                                    
                                <!--</a>-->
                                <!--<i class="fa fa-angle-right"></i>-->
                            </li>
<!--                            <li>
                                <span><?= $this->translate('User panel'); ?></span>
                            </li>-->
                        </ul>
                    </div>
