<h3 class="page-title"> <?= $this->translate('Edit company'); ?> </h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="<?= $this->url(array(''),'domain-account'); ?>">
                <?= $this->translate('User panel'); ?>
            </a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span><?= $this->translate('Edit company'); ?></span>
        </li>
    </ul>
</div>
<div class="row awardRace">
    <div class="col-md-12">
    <?= MF_Text::showFormMessages(); ?>
        <!-- BEGIN SAMPLE TABLE PORTLET-->
            <div class="portlet box green form form-horizontal">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa-users fa "></i>
                        <span class="caption-subject"><?= $this->translate('Edit company'). " " . $this->agent['name']; ?></span>
                    </div>
                </div>
                <div class="portlet-body">

                    <form class="admin-form"  method="post" >
                        <div class="">
                              <?= $this->form->agent_id; ?>
                            <div class="clearfix"></div><br />

                            <div class="col-md-6">
                                <?= $this->form->description; ?>
                                <?= $this->form->facebook; ?>
                                <?= $this->form->twitter; ?>
                                <br />
                            </div>
                            
                            <div class="col-md-6">
                                <strong><?= $this->translate('Important!'); ?></strong><br />
                                <?= $this->translate('To edit other company details, please go to your branch list, select head office and edit its details.'); ?>
                            </div>
                            <div class="clearfix"></div>
                            <div style="text-align:center">
                                <?= $this->form->submit; ?>
                            </div>
                        </div>
                    </form>
                </div>
        </div>
        <!-- END SAMPLE TABLE PORTLET-->
    </div>
</div>

