<h3 class="page-title"> <?= $this->translate('Edit password'); ?> </h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="<?= $this->url(array('action' => ''),'domain-account'); ?>">
                <?= $this->translate('User panel'); ?>
            </a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span><?= $this->translate('Edit password'); ?></span>
        </li>
    </ul>
</div>
<div class="row awardRace">
    <div class="col-md-12">
    <?= MF_Text::showFormMessages(); ?>
        <!-- BEGIN SAMPLE TABLE PORTLET-->
            <div class="portlet box green form form-horizontal">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa-users fa "></i>
                        <span class="caption-subject"><?= $this->translate('Edit password') ?></span>
                    </div>
                </div>
                <div class="portlet-body">

                    <form class="admin-form"  method="post" >
                        <div class="">
                              <?= $this->form->agent_id; ?>
                            <div class="clearfix"></div><br />

                            <div class="col-md-6">
                                <?= $this->form->old_password; ?>
                                <?= $this->form->password; ?>
                                <?= $this->form->confirm_password; ?>
                                <br />
                            </div>
                            
                            <div class="col-md-6">
                                
                            </div>
                            <div class="clearfix"></div>
                            <div style="text-align:center">
                                <?= $this->form->submit; ?>
                            </div>
                        </div>
                    </form>
                </div>
        </div>
        <!-- END SAMPLE TABLE PORTLET-->
    </div>
</div>

