
 <h3 class="page-title"> <?= $this->translate('Welcome to user panel'); ?></h3>
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <i class="icon-home"></i>
                                <!--<a href="<?= $this->url(array(),'domain-account'); ?>">-->
                                    
                                <!--</a>-->
                                <!--<i class="fa fa-angle-right"></i>-->
                            </li>
<!--                            <li>
                                <span><?= $this->translate('User panel'); ?></span>
                            </li>-->
                        </ul>
                    </div>
<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="dashboard-stat blue">
            <div class="visual">
                <i class="fa fa-comments"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span data-counter="counterup" data-value="<?= (int)$this->user['Agent']['views']; ?>">0</span>
                </div>
                <div class="desc"> <?= $this->translate('Your company page visitors'); ?></div>
            </div>
            <a class="more" href="javascript:;">
                &nbsp;
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="dashboard-stat red">
            <div class="visual">
                <i class="fa fa-bar-chart-o"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span data-counter="counterup" data-value="<?= $this->user['Agent']['rank']; ?>">1</span> </div>
                <div class="desc"><?= $this->translate('Your overall rank'); ?> </div>
            </div>
            <a class="more" href="javascript:;"> 
                &nbsp;
                <!--                                    View more
                                                    <i class="m-icon-swapright m-icon-white"></i>-->
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="dashboard-stat green">
            <div class="visual">
                <i class="fa fa-shopping-cart"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span data-counter="counterup" data-value="<?= $this->user['Agent']['votes']; ?>">0</span>
                </div>
                <div class="desc"> <?= $this->translate('Reviews no'); ?> </div>
            </div>
            <a class="more" href="javascript:;"> 
                &nbsp;
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="dashboard-stat purple">
            <div class="visual">
                <i class="fa fa-globe"></i>
            </div>
            <div class="details">
                <div class="number"> 
                    <span data-counter="counterup" data-value="<?= $this->user['Agent']['customer_satisfaction'] * 100; ?>"></span>% </div>
                <div class="desc"><?= $this->translate('Customer satisfaction'); ?> </div>
            </div>
            <a class="more" href="javascript:;"> 
                &nbsp;
            </a>
        </div>
    </div>
</div>
<div class="clearfix"></div>
