<h3 class="page-title"> <?= $this->translate('My staff members'); ?> </h3>

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="<?= $this->url(array(),'domain-account'); ?>">
                <?= $this->translate('User panel'); ?>
            </a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span><?= $this->translate('My staff members'); ?></span>
        </li>
    </ul>
</div>

<div class="row awardRace">
    
    <?= MF_Text::showFormMessages(); ?>
    <div class="col-md-12">
        <!-- BEGIN SAMPLE TABLE PORTLET-->
        <div class="portlet box green ">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa-building fa "></i>
                    <span class="caption-subject"><?= $this->translate('My staff members'); ?></span>
                </div>
            </div>
            <div class="portlet-body">
                <div class="form-actions top">
                    <div class="btn-set pull-left">
                        <a href="<?= $this->url(array('action' => 'add-staff'),'domain-account');?>" class="btn btn-primary">
                            <i class="fa fa-plus"></i>
                            <?= $this->translate('Add staff member'); ?>
                        </a>
                    </div>
                    <br /><br />
                </div>
                <div class="table-scrollable">
                    <table class="table">
                        <tr>
                            <th><?= $this->translate('Name'); ?></th>
                            <th><?= $this->translate('Photo'); ?></th>
                            <th></th>
                        </tr>
                        <?php foreach($this->staffMembers as $staff){ ?>
                        <tr>
                            <td><?= $staff['firstname'] . " " . $staff['lastname']; ?></td>
                            <td><img src="<?= $staff->getPictureUrl('80x80'); ?>" /></td>
                            <td>
                                <a href="<?= $this->url(array('id' => $staff['id']), 'domain-edit-staff'); ?>" class="btn btn-primary">
                                    <i class="fa fa-pencil"></i>
                                    <?= $this->translate('Edit this staff member'); ?>
                                </a> &nbsp;
                                <a href="<?= $this->url(array('id' => $staff['id']), 'domain-delete-staff'); ?>" data-text="<?= $this->translate('Are you sure you want to delete')." ".$staff['firstname']." ".$staff['lastname']; ?>?" class="confirm btn btn-danger">
                                    <i class="fa fa-times"></i>
                                    <?= $this->translate('Delete staff member'); ?>
                                </a>
                            </td>
                        </tr>
                        <?php } ?>
                    </table>
                </div>
            </div>
        </div>
        <!-- END SAMPLE TABLE PORTLET-->
    </div>
</div>