<?php

/**
 * Advertising_Model_Doctrine_AdvertisingPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Advertising
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Advertising_Model_Doctrine_AdvertisingPage extends Advertising_Model_Doctrine_BaseAdvertisingPage
{

}