<?php

/**
 * Advertising_Model_Doctrine_Advertising
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Advertising
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Advertising_Model_Doctrine_Advertising extends Advertising_Model_Doctrine_BaseAdvertising
{
    public static $adPhotoDimensions = array(
        '126x126' => 'Photo in admin panel',                  // admin
        '728x90' => 'Very main',
    );
    
    public static function getAdPhotoDimensions() {
        return self::$adPhotoDimensions;
    }
    
    public static function getDefaultAd() {
        
        $translate = Zend_Registry::get('Zend_Translate');
        $lang = $translate->getLocale();
        if($lang=='pl')
            return '/images/reklama.gif';
        else
            return '/images/advertise.gif';
    }
}