<?php

/**
 * Advertising_Model_Doctrine_BaseAgent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $ad_id
 * @property integer $agent_id
 * @property boolean $active
 * @property Doctrine_Collection $Advertising
 * 
 * @package    Admi
 * @subpackage Advertising
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Advertising_Model_Doctrine_BaseAgent extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('advertising_agent');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('ad_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('agent_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('active', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Advertising_Model_Doctrine_Advertising as Advertising', array(
             'local' => 'ad_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}