<?php

/**
 * Advertising_Model_Doctrine_BasePage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $page
 * @property string $value
 * @property Doctrine_Collection $Ads
 * 
 * @package    Admi
 * @subpackage Advertising
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Advertising_Model_Doctrine_BasePage extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('advertising_page');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('page', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Advertising_Model_Doctrine_Advertising as Ads', array(
             'refClass' => 'Advertising_Model_Doctrine_AdvertisingPage',
             'local' => 'page_id',
             'foreign' => 'ad_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}