<?php

/**
 * Advertising_Model_Doctrine_SizeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Advertising_Model_Doctrine_SizeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Advertising_Model_Doctrine_SizeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Advertising_Model_Doctrine_Size');
    }
}