
<script type="text/javascript">
$(document).ready(function() {
   
    
    $('#explorer').dialog({
		autoOpen: false,
		modal: true,
		dialogClass: 'dialog',
	});
        
        $('#explorer2').dialog({
		autoOpen: false,
		modal: true,
		dialogClass: 'dialog',
	});
    
    $("#itemContainer").delegate(".actionBtn .add", "click", function(e) {
        e.preventDefault();
        
        var elf = $('#elfinder').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-logo-photo', 'agent') ?>/id/"+$('#id').val(),
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#main_photo_container").html(resp.body);
                            $("#itemContainer").trigger('update');
                        }
                    }
                });

                $('#explorer').dialog('close');
//                $.modal.close();
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
                    //multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                },
            }
        }).elfinder('instance');	
        
        $('#explorer').dialog('open');
    });
    
    $("#itemContainer").delegate(".actionBtn .delete", "click", function(e) {
        e.preventDefault();
        $.ajax({
            type: "post",
            dataType: "json",
            url: "<?php echo $this->adminUrl('remove-logo-photo', 'agent') ?>/id/"+$('#id').val()+"/photo-id/"+$(this).attr('rel'),
            data: data,
            success: function(resp) {
                if(resp.status == "success") {
                    $("#main_photo_container").html(resp.body);
                    $("#itemContainer").trigger('update');
                }
            }
        });
    });
    
     $("#itemCon").delegate("#add-photo", "click", function(e) {
        e.preventDefault();
        
        var elf = $('#elfinder2').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-ad-photo', 'agent') ?>/id/"+$('#id').val(),
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#main_photo_con").html(resp.body);
                            $("#itemCon").trigger('update');
                        }
                    }
                });

                $('#explorer2').dialog('close');
//                $.modal.close();
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
//                    multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                },
            }
        }).elfinder('instance');	
        
        $('#explorer2').dialog('open');
    });
    
    
      $("#itemCon").delegate(".actionBtn .delete", "click", function(e) {
        e.preventDefault();
        $.ajax({
            type: "post",
            dataType: "json",
            url: "<?php echo $this->adminUrl('remove-ad-photo', 'agent') ?>/id/"+$('#id').val()+"/photo-id/"+$(this).attr('rel'),
            data: data,
            success: function(resp) {
                if(resp.status == "success") {
                    $("#main_photo_con").html(resp.body);
                    $("#itemCon").trigger('update');
                }
            }
        });
    });
    
    
    
    $('#category_id').select2();
     $('.section').hide();
     $('.contentSection').show();
     $('.btnList li').click(function(){
        var rel = $(this).attr('rel');
        $('.section').hide();
        $('.'+rel).show();
     });
});
</script>

<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edytuj agenta') ?> </span>
                </h4>
                
            </div>
            <div class="content clearfix">
                <ul class="btnList">
                    <li rel="contentSection"><button class="btn" type="button">Treść</button></li>
                    <li rel="metatagSection"><button class="btn" type="button">Pokaż metatagi</button></li>
                </ul>
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    
                    <h3>Dane uzupełniającego</h3>  
                    <?= $this->form->name; ?>
                    <?= $this->form->category_id; ?>
                    <?= $this->form->premium_support; ?>
                    <ul id="myTab" class="nav nav-tabs pattern">
                            <li class="dropdown">
                                <?php foreach($this->languages as $key => $language): ?>
                                <li class="<?php if($language == $this->adminLanguage->getId()): ?>active<?php endif; ?>"><a href="#dropdown<?php echo $key + 1 ?>" data-toggle="tab"><?php echo $language ?></a></li>
                                <?php endforeach; ?>
                            </li>
                        </ul>
                    
                     <div class="tab-content">
                    <?php  foreach($this->languages as $key => $language):  ?>
                    <div class="tab-pane<?php if($language == $this->adminLanguage->getId()): ?> in active<?php endif; ?>" id="dropdown<?php echo $key + 1 ?>">
                        <span class="section contentSection">
                            <?php  if($this->form->translations->getSubForm($language)): ?>
                                <?php echo $this->form->translations->getSubForm($language)->description->setAttrib('class', '') ?>
                            <?php endif; ?>
                        </span>
                    </div>
                    <?php  endforeach; ?>
                     </div>
                    
                     <span>
                        <div class="page-header">
                            <h4><?php echo $this->translate('Agent logo') ?></h4>
                        </div>

                        <div id="itemContainer">
                            <ul id="main_photo_container" class="galleryView center">
                                <li class="pull-left">
                                <?php if($this->agent->get('LogoRoot')->getOffset()): ?>
                                    <a id="main_photo" href="/media/photos/<?php echo $this->agent->get('LogoRoot')->getOffset() ?>/<?php echo $this->agent->get('LogoRoot')->getFilename() ?>" rel="prettyPhoto" title="<?php echo $this->agent->get('LogoRoot')->getTitle() ?>">
                                        <img src="/media/photos/<?php echo $this->agent->get('LogoRoot')->getOffset() ?>/126x126/<?php echo $this->agent->get('LogoRoot')->getFilename() ?>" data-original="/media/photos/<?php echo $this->agent->get('LogoRoot')->getOffset() ?>/<?php echo $this->agent->get('LogoRoot')->getFilename() ?>" alt="<?php echo $this->agent->get('LogoRoot')->getTitle() ?>">
                                    </a>
                                    <?php else: ?>
                                    <a id="main_photo" href="/images/gallery/preload.png" title="<?php echo $this->translate('No photo') ?>">
                                        <img src="/images/gallery/preload.png" data-original="/images/gallery/preload.png" alt="<?php echo $this->translate('No photo') ?>">
                                    </a>
                                    <?php endif; ?>
                                    <div class="actionBtn">
                                        <a href="#" class="add"><span class="icon16 iconic-icon-cursor white"></span></a>
                                        <a href="#" class="delete"><span class="icon16 icomoon-icon-cancel-4 white"></span></a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                         <div class="page-header">
                             <h4><?php echo $this->translate('Gallery View') ?></h4>
                        </div>                  
                        <div id="itemCon">           
                            <button href="#" id="add-photo" style="width: 120px;"><?php echo $this->translate('Add photo') ?></button>
                            <ul id="main_photo_con" class="galleryView center">
                                <li class="pull-left">
                                <?php if($this->agent->get('AdRoot')->getOffset()): ?>
                                    <a id="main_photo" href="/media/photos/<?php echo $this->agent->get('AdRoot')->getOffset() ?>/<?php echo $this->agent->get('AdRoot')->getFilename() ?>" rel="prettyPhoto" title="<?php echo $this->agent->get('AdRoot')->getTitle() ?>">
                                        <img src="/media/photos/<?php echo $this->agent->get('AdRoot')->getOffset() ?>/126x126/<?php echo $this->agent->get('AdRoot')->getFilename() ?>" data-original="/media/photos/<?php echo $this->agent->get('AdRoot')->getOffset() ?>/<?php echo $this->agent->get('AdRoot')->getFilename() ?>" alt="<?php echo $this->agent->get('AdRoot')->getTitle() ?>">
                                    </a>
                                    <?php else: ?>
                                    <a id="main_photo" href="/images/gallery/preload.png" title="<?php echo $this->translate('No photo') ?>">
                                        <img src="/images/gallery/preload.png" data-original="/images/gallery/preload.png" alt="<?php echo $this->translate('No photo') ?>">
                                    </a>
                                    <?php endif; ?>
                                    <div class="actionBtn">
                                        <a href="#" class="add"><span class="icon16 iconic-icon-cursor white"></span></a>
                                        <a href="#" class="delete"><span class="icon16 icomoon-icon-cancel-4 white"></span></a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </span>
                            
                        <?php echo $this->form->id ?>
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <button name="save_only" id="btnSaveOnly" type="submit" class="btn btn-primary"><?php echo $this->translate('Save and stay') ?></button>
                        <a href="<?php echo $this->adminUrl('list-agent', 'agent') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                </form>
            </div>
            
        </div>
    </div>   
</div> 
    
<div id="explorer" class="dialog"><div id="elfinder"></div></div>
<div id="explorer2" class="dialog"><div id="elfinder2"></div></div>