<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#offer_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "sAjaxSource": "<?php echo $this->adminUrl('list-group-data', 'newsletter') ?>",
        "aaSorting": [[ 0, "desc" ]],
        "aoColumns": [
            null,
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#offer_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    
    $("#group_id").select2();
});
</script>

<div class="row-fluid">

    <div class="span6">
        
        <div class="box">

            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Add') ?></span>
                </h4>

            </div>
            <div class="content clearfix">

                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    <?php echo $this->form->name ?>
                    <?php echo $this->form->lastname ?>
                    <?php echo $this->form->email ?>
                    <?php echo $this->form->category_id ?>
                    
                    <?php echo $this->form->submit ?>
                    <?php echo $this->form->id ?>
                </form>
            </div>

        </div>
            
    </div>

    <div class="span6">
        
        <div class="box">

            <div class="title">

                <h4>
                    <span class="icon16 silk-icon-calculator"></span>
                    <span><?php echo $this->translate('Group list') ?></span>
                </h4>

            </div>
            <div class="content clearfix">

                <table id="offer_table" cellpadding="0" cellspacing="0" border="0" class="responsive display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Name') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>

            </div>

        </div>
        
    </div>

</div>