

<div class="row-fluid">

    <div class="span6">
        
        <div class="box">

            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Add') ?></span>
                </h4>

            </div>
            <div class="content clearfix">

                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    <?php echo $this->form->name ?>
                    <?php echo $this->form->lastname ?>
                    <?php echo $this->form->email ?>
                    <?php echo $this->form->category_id ?>
                    
                    <?php echo $this->form->submit ?>
                    <?php echo $this->form->id ?>
                </form>
            </div>

        </div>
            
    </div>

   
</div>