<?php

/**
 * Branch_Model_Doctrine_Branch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Branch
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Branch_Model_Doctrine_Branch extends Branch_Model_Doctrine_BaseBranch
{
    public function getOfficeImage(){
        return '/assets/images/office-placeholder.jpg';
    }
    
    public function setUp()
    {
        parent::setUp();
         $this->hasMany('Staff_Model_Doctrine_Staff as StaffMembers', array(
             'local' => 'id',
             'foreign' => 'branch_id'));
        
        $this->hasOne('Agent_Model_Doctrine_Agent as Agent', array(
             'local' => 'agent_id',
             'foreign' => 'id'));

    }
}