<?php

/**
 * Branch_Model_Doctrine_BranchTranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Branch_Model_Doctrine_BranchTranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Branch_Model_Doctrine_BranchTranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Branch_Model_Doctrine_BranchTranslation');
    }
}