<?php

/**
 * Branch_Model_Doctrine_UpdateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Branch_Model_Doctrine_UpdateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Branch_Model_Doctrine_UpdateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Branch_Model_Doctrine_Update');
    }
}