<?php

/**
 * Branch_Model_Doctrine_UpdateOpeningHours
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Branch
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Branch_Model_Doctrine_UpdateOpeningHours extends Branch_Model_Doctrine_BaseUpdateOpeningHours
{

}