<?php

/**
 * Advertisment_Model_Doctrine_AdvertismentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Advertisment_Model_Doctrine_AdvertismentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Advertisment_Model_Doctrine_AdvertismentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Advertisment_Model_Doctrine_Advertisment');
    }
    
    
    public function getShowAdvertismentQuery() {
        $q = $this->createQuery('n')
                ->addSelect('n.*')
                ->addSelect('nt.*')
                ->addSelect('pr.*')
                ->addSelect('c.*')
                ->addSelect('g.*')
                ->addSelect('ct.*,gt.*')
                ->addSelect('p.*')
                ->leftJoin('n.Translation nt')
                ;
        
        $q->leftJoin('n.PhotoRoot pr');
        $q->leftJoin('n.Photos p')
                ->leftJoin('n.Category c')
                ->leftJoin('c.Translation ct')
                ->leftJoin('c.Group g')
                ->leftJoin('g.Translation gt');
//        $q->addWhere('n.publish = 1');
//        $q->addWhere('n.publish_date <= NOW()');
        return $q;
    }
}