<?php

/**
 * Advertisment_Model_Doctrine_CategoryGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Advertisment_Model_Doctrine_CategoryGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Advertisment_Model_Doctrine_CategoryGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Advertisment_Model_Doctrine_CategoryGroup');
    }
}