<?php

/**
 * Advertisment_Model_Doctrine_CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Advertisment_Model_Doctrine_CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Advertisment_Model_Doctrine_CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Advertisment_Model_Doctrine_Category');
    }
    
    public function getCategoryQuery() {
          $q = $this->createQuery('c')
                ->select('c.*')
                ->addSelect('ct.*')
                ->leftJoin('c.Translation ct')
                ;
        
        return $q;
    }
}