<?php

/**
 * Advertisment_Model_Doctrine_GroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Advertisment_Model_Doctrine_GroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Advertisment_Model_Doctrine_GroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Advertisment_Model_Doctrine_Group');
    }
}