<!-- TAB 2 -->
<div id="agent-details" class="tab-pane fade">
    <div class="tab-pane1">
        <div class="row tc">
            <img src="/img/arlaetc.png" alt=""/>
        </div>
        <div class="line4"></div>
        <a href="#" class="pull-right" style="margin-left:10px;margin-bottom:10px;"><img src="http://placehold.it/200x200" alt=""/></a>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra mi sit amet metus semper, ut sodales nunc molestie. Donec vulputate lectus in pretium accumsan. Nam vitae urna at nibh malesuada lacinia sed at est. Nam ut sagittis tortor. Donec sit amet dui suscipit arcu tincidunt rhoncus nec quis libero. Mauris euismod felis nulla, eget mattis velit posuere ut. Suspendisse sit amet odio non libero viverra tempor vitae sit amet lectus.
<br /><br />
Nulla nibh mi, bibendum a feugiat vel, pharetra et felis. In id porttitor ante. Maecenas nec metus dapibus, consequat augue id, commodo lorem. Vestibulum lobortis enim turpis, vel dapibus massa hendrerit non. Nulla tincidunt sem orci, et ultrices lectus pellentesque vel. Sed dignissim vulputate hendrerit. Phasellus ut lacus justo.

        <!-- Carousel --> 
    </div>
    <div class="clearfix"></div>
    <br /><br />
    <div class="tab-pane2">
        <h4 class="darkbronze">Review statistics</h4>
        <div class="row">
            <table class="table table-condensed table-striped table-hover stats_table">
                <thead>
                    <tr>
                        <th colspan="2">From Landlords</th>
                        <th colspan="2">From Tenants</th>
                        <th colspan="2">From Vendors</th>
                        <th colspan="2">From Buyers</th>
                        <th colspan="2">Other</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><span class="green"><?= MF_View_Helper_Icon::THUMBS_UP; ?> </span></td>
                        <td><span class="red"><?= MF_View_Helper_Icon::THUMBS_DOWN; ?> </span></td>
                        <td><span class="green"><?= MF_View_Helper_Icon::THUMBS_UP; ?> </span></td>
                        <td><span class="red"><?= MF_View_Helper_Icon::THUMBS_DOWN; ?> </span></td>
                        <td><span class="green"><?= MF_View_Helper_Icon::THUMBS_UP; ?> </span></td>
                        <td><span class="red"><?= MF_View_Helper_Icon::THUMBS_DOWN; ?> </span></td>
                        <td><span class="green"><?= MF_View_Helper_Icon::THUMBS_UP; ?> </span></td>
                        <td><span class="red"><?= MF_View_Helper_Icon::THUMBS_DOWN; ?> </span></td>
                        <td><span class="green"><?= MF_View_Helper_Icon::THUMBS_UP; ?> </span></td>
                        <td><span class="red"><?= MF_View_Helper_Icon::THUMBS_DOWN; ?> </span></td>
                    </tr>
                    <tr>
                        <td><span class="disapp">38</span></td>
                        <td><span class="disapp">137</span></td>
                        <td><span class="disapp">38</span></td>
                        <td><span class="disapp">137</span></td>
                        <td><span class="disapp">38</span></td>
                        <td><span class="disapp">137</span></td>
                        <td><span class="disapp">38</span></td>
                        <td><span class="disapp">137</span></td>
                        <td><span class="disapp">38</span></td>
                        <td><span class="disapp">137</span></td>
                </tbody>
            </table>
        </div>
    </div>
</div>