<?php
MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $this->translate('Add company'), true);
echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>
<div class="container">

    <div class="container mt25 offset-0 addReviewPage addUnlistedAgentPage">


        <!-- LEFT CONTENT -->
        <div class="col-md-8 pagecontainer2 offset-0">


            <form class="form1 box1"method="post" >
                
                <div class="hpadding50c defaultheader2">
                    <h1><?= $this->translate('Add company'); ?></h1>
                    <p class="aboutarrow"></p>
                </div>
                <div class="line3"></div>
                <div class="padding30 grey">

                     <span class="steps">
                        <strong class="sectionHeader">1.<?= $this->translate('Company details'); ?></strong>
                        <hr />
                        
                                <?= $this->form->name; ?>
                                <?= $this->form->description; ?>
                                <?= $this->form->twitter; ?>
                                <?= $this->form->facebook; ?>


                    </span>
                    
                    <span class="steps">
                        <span class="sectionHeader">2.<?= $this->translate('Select company category / business sector'); ?></span>
                        <br /><br />
                                <div class="form-group">
                                    <div class="addCompanyCategoryList">
                                        <?php foreach($this->agentCategories as $agentCategory): ?>
                                        <div class="col-md-4">
                                            <strong><?= $agentCategory['Translation'][$this->language]['title']; ?></strong>
                                            <ul>
                                                <?php foreach($agentCategory->getNode()->getChildren() as $subcategory){ ?>
                                                    <li>
                                                        <label><?= $subcategory['Translation'][$this->language]['title']; ?><input type="radio" value="<?= $subcategory['id']; ?>" name="category_id" /></label>
                                                    </li>
                                                <?php } ?>
                                            </ul>
                                        </div>

                                        <?php endforeach; ?>
                                    </div>
                                </div>
                    </span>
                    <br />
                    <span class="steps">
                        <span class="sectionHeader">3.<?= $this->translate('Branch details'); ?></span>
                        <hr />
                                <?= $this->form->office_name; ?>
                                <?= $this->form->address; ?>
                                <?= $this->form->town; ?>
                                <?= $this->form->postcode; ?>
                                <?= $this->form->county; ?>
                                <?= $this->form->branch_email; ?>
                                <?= $this->form->phone; ?>
                        <hr />
                        <br />
                                <div class="col-md-12">
                                    <h4><?= $this->translate('Opening hours'); ?></h4>
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th></th>
                                                <th><?= $this->translate('Opening hour'); ?></th>
                                                <th><?= $this->translate('Closing hour'); ?></th>
                                                <th><?= $this->translate('Closed'); ?></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php for($i=1;$i<=7;$i++): ?>
                                                <tr>
                                                    <td>
                                                        <label>
                                                            <?php
                                                                if($this->language=='pl')
                                                                    echo MF_Text::polishDayOfWeek($i); 
                                                                else
                                                                    echo MF_Text::dayOfWeek($i); 
                                                            ?>
                                                        </label>
                                                    </td>
                                                    <td><?= $this->form->hoursForm->getElement('start_'.strtolower(jddayofweek($i-1, 2))); ?></td>
                                                    <td><?= $this->form->hoursForm->getElement('end_'.strtolower(jddayofweek($i-1, 2))); ?></td>
                                                    <td><?= $this->form->hoursForm->getElement('closed_'.strtolower(jddayofweek($i-1, 2))); ?></td>
                                                </tr>
                                            <?php endfor; ?>

                                        </tbody>
                                    </table>
                                </div>
                                <div class="clearfix"></div>

                    </span>
                    <span class="steps" >
                        <span class="sectionHeader">4.<?= $this->translate('Your details'); ?></span>
                        <hr />
                        <?= $this->translate('Your details will not be published. We gather them only for moderation purposes.'); ?>
                                <br /><br />
                        <?= $this->form->firstname; ?>
                                <?= $this->form->lastname; ?>
                                <?= $this->form->email; ?>
                <?php echo $this->form->getElement('g-recaptcha-response'); ?>

                                <br />
                    </span>
                    
                    <?= $this->form->submit; ?>


                </div>

            </form>
        </div>
        <!-- END OF LEFT CONTENT -->

        <!-- RIGHT CONTENT -->
        <div class="col-md-4" >
            <?php echo $this->action('banner-sidebar2','index','banner'); ?>
        </div>
        <!-- END OF RIGHT CONTENT -->


    </div>


</div>
<script>
    $(function(){
        
        $('.addCompanyCategoryList label').on('click',function(){
            $('.addCompanyCategoryList label').removeClass('active');
            var label = $(this);
            var input = label.find('input'); 
            if(input.is(':checked')){
                label.addClass('active');
            }
        });
        
        $('input.closed').on('click',function(){
            var tr = $(this).closest('tr');
            var inputs = tr.find('select');
            if($(this).is(':checked')){
                inputs.attr('disabled','disabled');
            }
            else{
                inputs.removeAttr('disabled');
            }
        });
        
        $('input.closed').each(function(){
            var tr = $(this).closest('tr');
            var inputs = tr.find('select');
            if($(this).is(':checked')){
                inputs.attr('disabled','disabled');
            }
            else{
                inputs.removeAttr('disabled');
            }
        });
    });
</script>