<!-- TAB 6 -->
<style>
    .medal{
        margin:0 auto;
        display:block;
    }
    .medalWrapper{
        padding-left:25px;
        border-right:1px solid #abc;
    }
    .medalWrapper:first-of-type{
        
        border-left:1px solid #abc;
    }
    </style>
<div id="awards" class="tab-pane fade">

    <div class="padding20">
        <div class='col-md-4 medalWrapper'>
            <div style='position:relative'>
                <img src="/img/gold-medal.png" class='medal' alt="allAgents gold medal" />
                <span style='position: absolute;
  top: 38%;
  text-align: center;
  width: 200px;
  font-size: 30px;
  line-height: 24px;
'>awards<br /> won</span>
            </div>
            <ul class="award_list">
                <li class="i-got-an-award ">
                    <a href="/awards/2014/agents/overall">2014 Best Overall Agent <br />in the UK </a>
                </li>                                                
                <li class="i-got-an-award">
                    <a href="/awards/2014/agents/lettings">2014 Best Letting Agent <br /> in the UK </a>
                </li>                        
                <li class="i-got-an-award">
                    <a href="/awards/2014/agents/overall/transparent">2014 Best Transparent Agent <br /> in the UK </a>
                </li>                        
                <li class="i-got-an-award">
                    <a href="/awards/2014/agents/sales/transparent">2014 Best Transparent <br />Estate Agent  in the UK  (Sales)</a>
                </li>                        
                <li class="i-got-an-award">
                    <a href="/awards/2014/agents/lettings/transparent">2014 Best Transparent <br /> Letting Agent  in the UK </a>
                </li> 
                <li class="i-got-an-award">
                    <a href="/awards/2014/agents/overall/medium-chain">2014 Best Overall <br />Medium Chain  in the UK </a>
                </li>                                            
            </ul>
        </div>
        
        <div class='col-md-4 medalWrapper'>
            <div style='position:relative'>
                <img src="/img/silver-medal.png" class='medal' alt="allAgents gold medal" />
                <span style='position: absolute;
  top: 38%;
  text-align: center;
  width: 200px;
  font-size: 30px;
  line-height: 24px;
'>awards<br /> won</span>
            </div>
            <!--<img src="/img/silver-medal.png" class='medal' alt="allAgents silver medal" />-->
            <ul class="award_list">
                <li class="i-got-an-award ">
                    <a href="/awards/2014/agents/overall">2014 Best Overall Agent <br />in the UK </a>
                </li>                                                
                <li class="i-got-an-award">
                    <a href="/awards/2014/agents/lettings">2014 Best Letting Agent <br /> in the UK </a>
                </li>                        
                <li class="i-got-an-award">
                    <a href="/awards/2014/agents/overall/transparent">2014 Best Transparent Agent <br /> in the UK </a>
                </li>                        
                <li class="i-got-an-award">
                    <a href="/awards/2014/agents/sales/transparent">2014 Best Transparent <br />Estate Agent  in the UK  (Sales)</a>
                </li>                        
                <li class="i-got-an-award">
                    <a href="/awards/2014/agents/lettings/transparent">2014 Best Transparent <br /> Letting Agent  in the UK </a>
                </li> 
                <li class="i-got-an-award">
                    <a href="/awards/2014/agents/overall/medium-chain">2014 Best Overall <br />Medium Chain  in the UK </a>
                </li>                                            
            </ul>
        </div>

        <div class='col-md-4 medalWrapper'>
            <div style='position:relative'>
                <img src="/img/bronze-medal.png" class='medal' alt="allAgents gold medal" />
                <span style='position: absolute;
  top: 38%;
  text-align: center;
  width: 200px;
  font-size: 30px;
  line-height: 24px;
'>awards<br /> won</span>
            </div>
            <ul class="award_list">
                <li class="i-got-an-award ">
                    <a href="/awards/2014/agents/overall">2014 Best Overall Agent <br />in the UK </a>
                </li>                                                
                <li class="i-got-an-award">
                    <a href="/awards/2014/agents/lettings">2014 Best Letting Agent <br /> in the UK </a>
                </li>                        
                <li class="i-got-an-award">
                    <a href="/awards/2014/agents/overall/transparent">2014 Best Transparent Agent <br /> in the UK </a>
                </li>                        
                <li class="i-got-an-award">
                    <a href="/awards/2014/agents/sales/transparent">2014 Best Transparent <br />Estate Agent  in the UK  (Sales)</a>
                </li>                        
                <li class="i-got-an-award">
                    <a href="/awards/2014/agents/lettings/transparent">2014 Best Transparent <br /> Letting Agent  in the UK </a>
                </li> 
                <li class="i-got-an-award">
                    <a href="/awards/2014/agents/overall/medium-chain">2014 Best Overall <br />Medium Chain  in the UK </a>
                </li>                                            
            </ul>
        </div>
        <div class="clearfix"></div>
        
    </div>
</div>