<!-- TAB 5 -->
<div id="complaints" class="tab-pane fade">
    <h4 class="darkbronze h3">Complaints Procedure</h4>
    <div class="hpadding20 pl0">
        <div class="complaints_content">
        1. Bradleys is a Member of The Property Ombudsman's Scheme and aims to provide the highest standards of service to all our Customers. To ensure that your interests are safeguarded, an Internal Complaints Procedure has been implemented. This provides for the matter to be dealt with internally by the Office Manager or the Department Head. In the event that we are not able to deal with the matter to our mutual satisfaction after following our Internal Complaints Procedure you may refer your complaint in writing to the Property Ombudsman. 
        <br />
        2. If you believe you have a complaint, please write in the first instance to the Office Manager or the Department Head at the address of the relevant office. 
        <br />
        3. Your complaint will be acknowledged within 3 working days, investigated thoroughly in accordance with the established in-house Procedures, and a reply sent to you within 21 working days of receipt of your letter. 
        <br />
        4. If you are not satisfied with the outcome of the initial investigation, you are provided with a further opportunity to have the complaint reviewed by our Managing Director at the address given below:
        Mr Francis Marshall FNAEA
        Bradleys Group Head Office
        7 Stevenstone Road
        Exmouth
        Devon
        EX8 2EP
        <br />
        </div>
        <small>Created at 10:49 am 21/03/2014. Last updated at 12:17 pm 08/04/2014 by allAgents</small>
    </div>
    
</div>