<?php
$agent = $this->agent;
$agentPsp = (int) $agent['premium_support'];
?>

<?php
    MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $agent['name'], true);
    echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>



<div class="container companyDetails">
    <div class="container pagecontainer offset-0">	
        
    <?= MF_Text::showFormMessages(); ?>
        <!-- SLIDER -->
        <div class="col-md-8 details-slider">
            <div class="company-ad">
                <img src="<?= $agent->getAdUrl('728x90'); ?>" alt="<?= $agent['name'];?> advertisment" />
            </div>
        </div>
        
        <div class="col-md-4 detailsright detailsright2 offset-0">
            <div class="padding20">
                <h1 class="h2 mt0 lato"><?= $agent['name']; ?></h1>
                <span class="stars">
                    <?= MF_Text::showStars($agent['rating']); ?>
                </span>
            </div>


        </div>
        <div class="clearfix"></div>
        <div class="line3"></div>
        <div class="col-md-8 details-slider">
            <div class="company-description">
                <?php 
                
                if(strlen($agent['Translation'][$this->language]['description'])){
                    echo $agent['Translation'][$this->language]['description']; 
                } 
                else{
                    echo $this->translate('This company has no description available');
                }
                
                ?>

            </div>
            <div class="line3"></div>
            
            <div class="hpadding20">
                <div class=" col-md-6">
                    <a href="<?= $this->url(array('slug' => $agent['link']),'domain-agent-contact'); ?>" class="add2fav margtop20"><?= $this->translate('Contact company'); ?></a>
                </div>
                <div class=" col-md-6">
                    <a href="<?= $this->url(array('agent' => $agent['link']),'domain-add-review'); ?>" class="booknow btnmarg margtop20"><?= $this->translate('Add review'); ?></a>
                </div>
            </div>
        </div>
        <!-- END OF SLIDER -->			

        <!-- RIGHT INFO -->

        <div class="col-md-4 detailsright offset-0">
            <div class="col-md-6 bordertype1 padding20">
                <span class="opensans size30 bold grey2"><?= ($agent['customer_satisfaction']*100); ?>%</span><br/>
                <?= $this->translate('of customers'); ?><br/><?= $this->translate('recommends'); ?>
            </div>
            <div class="col-md-6 bordertype2 padding20">
                <span class="opensans size30 bold grey2"><?= (int)$agent['rating']; ?></span>/5<br/>
                <?= $this->translate('customers ratings'); ?>
            </div>
           
            <div class="col-md-6 bordertype3">
                <?= (int)$agent['votes']; ?> <?= $this->translate('reviews'); ?>
            </div>
            <div class="col-md-6 bordertype3">
                <a href="<?= $this->url(array(),'domain-login'); ?>" class="grey underline"><?= $this->translate('Edit details'); ?></a>
            </div>
            <div class="clearfix"></div>

        </div>
        <!-- END OF RIGHT INFO -->

    </div>
    <!-- END OF container-->

    <div class="container mt25 offset-0">

        <div class="col-md-8 pagecontainer2 offset-0">
            <div class="cstyle10"></div>

            <ul class="nav nav-tabs" id="myTab">
                <li class="active"><a data-toggle="tab" href="#reviews"><span class="reviews"></span><span class="hidetext"><?= $this->translate('Reviews'); ?></span>&nbsp;</a></li>
                <li><a data-toggle="tab" href="#staff-members"><span class="summary"></span><span class="hidetext"><?= $this->translate('Staff members'); ?></span>&nbsp;</a></li>

            </ul>			
            <div class="tab-content4" >
                <?= $this->render('index/reviews.phtml'); ?>
                <?= $this->partial('index/staff-members.phtml',array('agent' => $agent)); ?>

            </div>
        </div>

        <div class="col-md-4" >

            <?php if($agent['premium_support']){ ?>
                <img src="<?= $agent->getLogoUrl('225x90'); ?>" alt="<?= $agent['name'];?> logo" class="agentMainLogo" />
                <div class="line3"></div>
            <?php } ?>
            <div class="pagecontainer2 needassistancebox">
                <div class="cpadding1">
                    <span class="icon-help"></span>
                    <h3 class="opensans"><?= $this->translate('Contact'); ?></h3>
                    <?php 
                    if($agent['HeadOffice']){
                        $headOffice = $agent['HeadOffice'];
                    }
                    else{
                        $headOffice = $agent['Branches'][0];
                    }
                         if(strlen($headOffice['phone'])){ ?>
                            <p class="opensans size30 lblue xslim"><?= $headOffice['phone']; ?></p>
                        <?php } ?>
                        <?php if(strlen($agent['HeadOffice']['url'])){ 
                            $url = $headOffice['url'];
                            if (strpos($url, 'http://')==false) {
                                $url = 'http://'.$url;
                             }
                            ?>
                            <p class="size14 grey">WWW: <a target="_blank" href='<?= $url; ?>'><?= $headOffice['url']; ?></a></p>
                        <?php } ?>
                    
                </div>
            </div>

            <div class="pagecontainer2 mt20 alsolikebox">
                <div class="cpadding1">
                    <span class="icon-location"></span>
                    <h3 class="opensans"><?= $this->translate('Branches'); ?></h3>
                    <div class="clearfix"></div>
                </div>
                <?php foreach($agent->get('Branches') as $branch){ ?>
                    <div class="cpadding1 ">
                        <div class='col-md-6'>
                            <a href="<?= $this->url(array('agent' => $agent['link'],'slug' => $branch['office_link']),'domain-branch-details'); ?>">
                                <img src="<?= $branch->getOfficeImage(); ?>" class="left mr20 img-responsive" alt="<?= $agent['name']." ".$branch['town']; ?>"/></a>
                        </div>
                        <div class='col-md-6'>
                        <a href="<?= $this->url(array('agent' => $agent['link'],'slug' => $branch['office_link']),'domain-branch-details'); ?>" class="dark"><b><?= $branch['office_name']; ?></b></a><br/>
                        <?php MF_Text::showStars($branch['rating']); ?>
                        <br />
                        
                        <?php echo $branch['address']." <br />";
                            echo $branch['postcode']." ".$branch['town'];
                        ?>
                        </div>
                        <div class='clearfix'></div>
                    </div>
                    <div class="line5"></div>
                <?php } ?>
                <br/>


            </div>				

        </div>
    </div>



</div>
