<!-- TAB 4 -->
<div id="fees" class="tab-pane fade">
    <div class="hpadding20">
        <div class='col-md-6'>
            <div class='fees'>
                <h6 class='h4 darkbronze'>Letting Fees</h6>
                <div>
                    Single Occupant - £150.00 <br />
                    Couple/2 Sharers - £150.00 <br />
                    3 People - £200.00 <br />
                    Then £50 each person thereafter<br />
                </div>
            </div>
            <div class='fees'>
                <h6 class='h4 darkbronze'>Management Fees</h6>
                <div>
                    Single Occupant - £150.00 <br />
                    Couple/2 Sharers - £150.00 <br />
                    3 People - £200.00 <br />
                    Then £50 each person thereafter<br />
                </div>
            </div>
        </div>
        <div class='col-md-6'>
            <div class='fees'>
                <h6 class='h4 darkbronze'>Sales Fees</h6>
                <div>
                    No fees submitted
                </div>
            </div>
            <div class='fees'>
                <h6 class='h4 darkbronze'>Conveyencing Fees</h6>
                <div>
                    No fees submitted
                </div>
            </div>
            <div class='fees'>
                <h6 class='h4 darkbronze'>Mortgage Advice</h6>
                <div>
                    No fees submitted
                </div>
            </div>
        </div>
    </div>
    <div class='clearfix'></div>
        <small>Created at 10:49 am 21/03/2014. Last updated at 12:17 pm 08/04/2014 by allAgents</small>
    <div class="line4"></div>
    <br /><br />
    <!-- End of collapse 8 -->


</div>