<!-- TAB 4 -->
<div id="jobs" class="tab-pane fade">
    <div class="hpadding20">
        <a href="#" class="btn btn-primary btn-large post_a_job pull-left">Post a job</a>
        <a href="#" class="btn btn-primary btn-large post_a_job pull-right">See all jobs</a>
        <div class='col-md-12'>
            <div class='job_advert'>
                <a href='#'><h5 class='h4 darkbronze'>Student Lettings Agents</h5></a>
                <strong>Canterbury, Kent - £19000</strong>
                <div class='job_text'>
                    Our client is an independent firm of chartered surveyors and property managers in the commercial and residential sectors throughout the South East region.
They currently require 3 Student Lettings agents to cover the running of the department and to oversee their Canterbury branch.<br /><br />
As a Student Lettings Agent you will be dealing with students, their parents, clients and contractors. A brief summary of duties include: undertaking viewings with tenants, negotiating with new clients, existing landlords and tenants, performing check ins and outs, dealing with property maintenance issues including advising on repairs, managing contractors, property inspections/appraisals/report writing and dealing with day-to-day Student Lettings work.

                </div>
                <div class='job_button_group'>
                    <a href='#'>Read more</a>|<a href='#'>Apply for this job</a>
                </div>
            </div>
            <div class='line4'></div>
            <div class='job_advert'>
                <a href='#'><h5 class='h4 darkbronze'>Student Lettings Agents</h5></a>
                <strong>Canterbury, Kent - £19000</strong>
                <div class='job_text'>
                    Our client is an independent firm of chartered surveyors and property managers in the commercial and residential sectors throughout the South East region.
They currently require 3 Student Lettings agents to cover the running of the department and to oversee their Canterbury branch.<br /><br />
As a Student Lettings Agent you will be dealing with students, their parents, clients and contractors. A brief summary of duties include: undertaking viewings with tenants, negotiating with new clients, existing landlords and tenants, performing check ins and outs, dealing with property maintenance issues including advising on repairs, managing contractors, property inspections/appraisals/report writing and dealing with day-to-day Student Lettings work.

                </div>
                <div class='job_button_group'>
                    <a href='#'>Read more</a>|<a href='#'>Apply for this job</a>
                </div>
            </div>
            <div class='line4'></div>
            <div class='job_advert'>
                <a href='#'><h5 class='h4 darkbronze'>Student Lettings Agents</h5></a>
                <strong>Canterbury, Kent - £19000</strong>
                <div class='job_text'>
                    Our client is an independent firm of chartered surveyors and property managers in the commercial and residential sectors throughout the South East region.
They currently require 3 Student Lettings agents to cover the running of the department and to oversee their Canterbury branch.<br /><br />
As a Student Lettings Agent you will be dealing with students, their parents, clients and contractors. A brief summary of duties include: undertaking viewings with tenants, negotiating with new clients, existing landlords and tenants, performing check ins and outs, dealing with property maintenance issues including advising on repairs, managing contractors, property inspections/appraisals/report writing and dealing with day-to-day Student Lettings work.

                </div>
                <div class='job_button_group'>
                    <a href='#'>Read more</a>|<a href='#'>Apply for this job</a>
                </div>
            </div>
            <div class='line4'></div>
            <div class='job_advert'>
                <a href='#'><h5 class='h4 darkbronze'>Student Lettings Agents</h5></a>
                <strong>Canterbury, Kent - £19000</strong>
                <div class='job_text'>
                    Our client is an independent firm of chartered surveyors and property managers in the commercial and residential sectors throughout the South East region.
They currently require 3 Student Lettings agents to cover the running of the department and to oversee their Canterbury branch.<br /><br />
As a Student Lettings Agent you will be dealing with students, their parents, clients and contractors. A brief summary of duties include: undertaking viewings with tenants, negotiating with new clients, existing landlords and tenants, performing check ins and outs, dealing with property maintenance issues including advising on repairs, managing contractors, property inspections/appraisals/report writing and dealing with day-to-day Student Lettings work.

                </div>
                <div class='job_button_group'>
                    <a href='#'>Read more</a>|<a href='#'>Apply for this job</a>
                </div>
            </div>
            <div class='line4'></div>
        </div>
        <div class='clearfix'></div>
        <a href="#" class="btn btn-primary btn-large post_a_job pull-left">Post a job</a>
        <a href="#" class="btn btn-primary btn-large post_a_job pull-right">See all jobs</a>
    </div>
    <div class='clearfix'></div>
    <div class="line4"></div>
    <br /><br />
    <!-- End of collapse 8 -->


</div>