<?php /* use Del\Icon; ?>
<style>
    .stars-small{
        margin-bottom:0px;
    }
    .stars-small i{
        font-size:15px;
        line-height: 15px;
    }
    .meet-the-team-desc strong{
        display:block;
        margin-bottom:10px;
    }
    </style>
<!-- TAB 2 -->
<div id="meet-the-team" class="tab-pane fade">
    <div class="tab-pane1">
        <div class="col-md-4">
            <img src="http://placehold.it/215x215" style="margin-bottom:10px; "/>
            <span class="staff-name-pos" style="float:left">
                <strong>Elvira</strong><br />
                Accountants
            </span>
            <span class="tt" title="4.5 Stars" style="float:right;">
                <!--FEATURED REVIEW&nbsp;&nbsp;-->
                <span class="gold stars stars-small">
                <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR_HALF_FULL ;?>
                </span>
                53 reviews
            </span>
        <div class="clearfix"></div>
        <br />
            <div class="meet-the-team-desc">
                <strong>About Elvira</strong>
                 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra mi sit amet metus semper, ut sodales nunc molestie. 
<a href="#" class="darkbronze block mt15">View full profile</a>
            </div>
        </div>
        <div class="col-md-4">
            <img src="http://placehold.it/215x215" style="margin-bottom:10px; "/>
            <span class="staff-name-pos" style="float:left">
                <strong>Elvira</strong><br />
                Accountants
            </span>
            <span class="tt" title="4.5 Stars" style="float:right;">
                <!--FEATURED REVIEW&nbsp;&nbsp;-->
                <span class="gold stars stars-small">
                <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR_HALF_FULL ;?>
                </span>
                53 reviews
            </span>
        <div class="clearfix"></div>
        <br />
            <div class="meet-the-team-desc">
                <strong>About Elvira</strong>
                 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra mi sit amet metus semper, ut sodales nunc molestie. 

<a href="#" class="darkbronze block mt15">View full profile</a>
            </div>
        </div>
        <div class="col-md-4">
            <img src="http://placehold.it/215x215" style="margin-bottom:10px; "/>
            <span class="staff-name-pos" style="float:left">
                <strong>Elvira</strong><br />
                Accountants
            </span>
            <span class="tt" title="4.5 Stars" style="float:right;">
                <!--FEATURED REVIEW&nbsp;&nbsp;-->
                <span class="gold stars stars-small">
                <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR_HALF_FULL ;?>
                </span>
                53 reviews
            </span>
        <div class="clearfix"></div>
        <br />
            <div class="meet-the-team-desc">
                <strong>About Elvira</strong>
                 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra mi sit amet metus semper, ut sodales nunc molestie. 

 <a href="#" class="darkbronze block mt15">View full profile</a>
            </div>
        </div>
        <div class="clearfix mt20"></div>
        <br /><br />
         <div class="col-md-4">
            <img src="http://placehold.it/215x215" style="margin-bottom:10px; "/>
            <span class="staff-name-pos" style="float:left">
                <strong>Elvira</strong><br />
                Accountants
            </span>
            <span class="tt" title="4.5 Stars" style="float:right;">
                <!--FEATURED REVIEW&nbsp;&nbsp;-->
                <span class="gold stars stars-small">
                <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR_HALF_FULL ;?>
                </span>
                53 reviews
            </span>
        <div class="clearfix"></div>
        <br />
            <div class="meet-the-team-desc">
                <strong>About Elvira</strong>
                 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra mi sit amet metus semper, ut sodales nunc molestie. 
<a href="#" class="darkbronze block mt15">View full profile</a>
            </div>
        </div>
        <div class="col-md-4">
            <img src="http://placehold.it/215x215" style="margin-bottom:10px; "/>
            <span class="staff-name-pos" style="float:left">
                <strong>Elvira</strong><br />
                Accountants
            </span>
            <span class="tt" title="4.5 Stars" style="float:right;">
                <!--FEATURED REVIEW&nbsp;&nbsp;-->
                <span class="gold stars stars-small">
                <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR_HALF_FULL ;?>
                </span>
                53 reviews
            </span>
        <div class="clearfix"></div>
            <div class="meet-the-team-desc">
                <strong>About Elvira</strong>
                 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra mi sit amet metus semper, ut sodales nunc molestie. 
<a href="#" class="darkbronze block mt15">View full profile</a>
            </div>
        </div>
        <div class="col-md-4">
            <img src="http://placehold.it/215x215" style="margin-bottom:10px; "/>
            <span class="staff-name-pos" style="float:left">
                <strong>Elvira</strong><br />
                Accountants
            </span>
            <span class="tt" title="4.5 Stars" style="float:right;">
                <!--FEATURED REVIEW&nbsp;&nbsp;-->
                <span class="gold stars stars-small">
                <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR ;?>
                    <?= Icon::STAR_HALF_FULL ;?>
                </span>
                53 reviews
            </span>
        <div class="clearfix"></div>
        <br />
            <div class="meet-the-team-desc">
                <strong>About Elvira</strong>
                 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra mi sit amet metus semper, ut sodales nunc molestie. 
<a href="#" class="darkbronze block mt15">View full profile</a>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
 * 
 */
?>

<div id="meet-the-team" class="tab-pane fade">
    This firm has multiple branches. <br />
Please choose specific branch in right hand side to see the specific team
</div>