<!-- TAB 3 -->
<div id="review-stats" class="tab-pane fade">

    <h4>Review Statistics for Foxtons</h4>
    
    <h5>Valuation and Fee Performance</h5>
    <table class="pc100">
        <tbody>
            <tr>
                <td class="pr20"><span class="statistic">71 %</span> customers were satisfied with agent's fees</td>
                <td><span class="statistic">87 %</span> accuracy of agent's valuations</td>
            </tr>
        </tbody>
    </table>
    
    <hr>
    
    <h5>Sales and lettings value statistics</h5>
    <table class="pc100">
        <thead>
        <tr class="">
            <th>Price range of properties sold by the agent</th>
            <th>Price range of properties rented by the agent</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td colspan="2">&nbsp;</td>
        </tr>
        <tr>
            <td class="pr20">Minimum:<span class="pull-right app">83000</span></td>
            <td class="pr20">Minimum:<span class="pull-right app">275</span></td>
        </tr>
        <tr>
            <td>Maximum:<span class="pull-right disapp">2370000</span></td>
            <td>Maximum:<span class="pull-right disapp">12013</span></td>
        </tr>
        </tbody>
    </table>
    
   <hr />

    <div class="clear">
        <div class="pull-left half">
            <h5>Review Summary</h5>
            <br class="clear">&nbsp;<br>
            <table class="pc100">
                <tbody>
                <tr>
                    <td>Total Reviews:<span class="pull-right"><strong>764</strong></span></td>
                </tr>
                <tr>
                    <td>Total Ratings:<span class="pull-right"><strong>770</strong></span></td>
                </tr>
                <tr>
                    <td>First Review:<span class="pull-right"><strong>24/04/2007</strong></span></td>
                </tr>
                <tr>
                    <td>Latest Review:<span class="pull-right"><strong>30/04/2015</strong></span></td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="pull-left half">
                            <span class="block">
                            Overall Review Performance
                            </span>
            <br class="clear">&nbsp;<br>

            <table class="pc100">
                <tbody>
                <tr>
                    <td>Recommend:<span class="pull-right app">518</span></td>
                </tr>
                <tr>
                    <td>Disapprove:<span class="pull-right disapp">252</span></td>
                </tr>
                <tr>
                    <td>Satisfaction:<span class="pull-right statistic">68 %</span></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <br class="clear">&nbsp;<br>
    <hr>
                    <span class="block">
                    Individual Services Review Performance
                    </span>
    <br class="clear">&nbsp;<br>
    <table class="table table-condensed table-striped table-hover">
        <thead>
        <tr class="">
            <th>From Landlords</th>
            <th>From Tenants</th>
            <th>From Vendors</th>
            <th>From Buyers</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td colspan="4">&nbsp;</td>
        </tr>
        <tr>
            <td>Recommend:<span class="pull-right app">45</span></td>
            <td>Recommend:<span class="pull-right app">166</span></td>
            <td>Recommend:<span class="pull-right app">190</span></td>
            <td>Recommend:<span class="pull-right app">78</span></td>
        </tr>
        <tr>
            <td>Disapprove:<span class="pull-right disapp">38</span></td>
            <td>Disapprove:<span class="pull-right disapp">137</span></td>
            <td>Disapprove:<span class="pull-right disapp">14</span></td>
            <td>Disapprove:<span class="pull-right disapp">5</span></td>
        </tr>
        <tr>
            <td>Satisfaction:<span class="pull-right statistic">55 %</span></td>
            <td>Satisfaction:<span class="pull-right statistic">55 %</span></td>
            <td>Satisfaction:<span class="pull-right statistic">94 %</span></td>
            <td>Satisfaction:<span class="pull-right statistic">94 %</span></td>
        </tr>
        </tbody>
    </table>
    <br>&nbsp;<br>
    <table class="pc100">
        <thead>
        <tr class="">
            <th>Surveys</th>
            <th>Conveyancing</th>
            <th>Lettings (Prospect)</th>
            <th>Sales (Prospect)</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td colspan="4">&nbsp;</td>
        </tr>
        <tr>
            <td>Recommend:<span class="pull-right app">0</span></td>
            <td>Recommend:<span class="pull-right app">0</span></td>
            <td>Recommend:<span class="pull-right app">21</span></td>
            <td>Recommend:<span class="pull-right app">13</span></td>
        </tr>
        <tr>
            <td>Disapprove:<span class="pull-right disapp">0</span></td>
            <td>Disapprove:<span class="pull-right disapp">1</span></td>
            <td>Disapprove:<span class="pull-right disapp">23</span></td>
            <td>Disapprove:<span class="pull-right disapp">30</span></td>
        </tr>
        <tr>
            <td>Satisfaction:<span class="pull-right statistic">-</span></td>
            <td>Satisfaction:<span class="pull-right statistic">0 %</span></td>
            <td>Satisfaction:<span class="pull-right statistic">48 %</span></td>
            <td>Satisfaction:<span class="pull-right statistic">31 %</span></td>
        </tr>
        </tbody>
    </table>

    <br>&nbsp;<br>
    <table class="pc100">
        <thead>
        <tr class="">
            <th>They manage our building</th>
            <th>They are our factor</th>
            <th>They manage our estate</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td colspan="3">&nbsp;</td>
        </tr>
        <tr>
            <td class="third">Recommend:<span class="pull-right app">0</span></td>
            <td class="third">Recommend:<span class="pull-right app">0</span></td>
            <td class="third">Recommend:<span class="pull-right app">0</span></td>
        </tr>
        <tr>
            <td>Disapprove:<span class="pull-right disapp">2</span></td>
            <td>Disapprove:<span class="pull-right disapp">0</span></td>
            <td>Disapprove:<span class="pull-right disapp">0</span></td>
        </tr>
        <tr>
            <td>Satisfaction:<span class="pull-right statistic">0 %</span></td>
            <td>Satisfaction:<span class="pull-right statistic">-</span></td>
            <td>Satisfaction:<span class="pull-right statistic">- </span></td>
        </tr>
        </tbody>
    </table>


</div>