<?php
MF_View_Helper_Breadcrumb::getInstance()->addLink('#', $this->translate('Login'), true);
echo MF_View_Helper_Breadcrumb::getInstance()->getBreadcrumbs();
?>



<div class="container">
    <div class="container pagecontainer offset-0">
        <div class="login-fullwidith  custom-login-container">

            <!-- Login Wrap  -->
            <div class="login-wrap text-center">
                <h1><?php echo $this->translate('Log in') ?></h1>
                <br /> 
                <div class="pagecontainer2 container">
                <?= $this->translate('Please log in to edit your company/branch details. If you forgot or lost your password, use forgot password button. In case of any problems please'); ?> <a class="underline" href="<?= $this->url(array(),'domain-contact'); ?>"><?= $this->translate('contact us'); ?></a>
                </div>
                <br />
                <form class="form-horizontal" action="<?php echo $this->loginForm->getAction() ?>" method="<?php echo $this->loginForm->getMethod() ?>" enctype="<?php echo $this->loginForm->getEnctype() ?>"> 

                    <?php if ($this->messages()->count()): ?>
                        <div class="alert alert-error">
                            <?php echo $this->messages()->render() ?>
                        </div>
                    <?php endif; ?>
                    <div class="login-c1">
                        <div class="cpadding20">
                            <?php echo $this->loginForm->username->setAttrib('class', 'logpadding form-control'); ?>
                            <?php echo $this->loginForm->password->setAttrib('class', 'logpadding form-control'); ?>

                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="login-c2">
                        <div class="logmargfix">
                            <div class="chpadding50">
                                <div class="alignbottom">
                                    <?php echo $this->loginForm->submit->setAttrib('class', 'btn-search4'); ?>						
                                </div>
                                <div class="alignbottom2">
                                    <?php echo $this->loginForm->remember ?>
                                </div>
                            </div>
                        </div>
                    </div>
                        <div class="clearfix"></div>
                </form>
                <div class="login-c3">
                    <!--<div class="left"><a href="#" class="whitelink"><span></span>Website</a></div>-->
                    <div class="right">

                        <a class="forgot_password whitelink" href="<?php echo $this->url(array('subject' => 'password'), 'domain-i18n:user-update') ?>"><?php echo $this->translate('Forgot password?') ?></a>
                    </div>
                </div>			
            </div>
            <!-- End of Login Wrap  -->

            <div class="clearfix"></div>
        </div>	
        <div class="clearfix"></div>
    </div>
</div>