<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('advertisment_article', 'advertisment_article_category_id_advertisment_category_id', array(
             'name' => 'advertisment_article_category_id_advertisment_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'advertisment_category',
             ));
        $this->createForeignKey('advertisment_article_translation', 'advertisment_article_translation_id_advertisment_article_id', array(
             'name' => 'advertisment_article_translation_id_advertisment_article_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'advertisment_article',
             ));
        $this->createForeignKey('advertisment_article_translation', 'advertisment_article_translation_id_advertisment_article_id_1', array(
             'name' => 'advertisment_article_translation_id_advertisment_article_id_1',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'advertisment_article',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('advertisment_category_translation', 'advertisment_category_translation_id_advertisment_article_id', array(
             'name' => 'advertisment_category_translation_id_advertisment_article_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'advertisment_article',
             ));
        $this->createForeignKey('advertisment_category_translation', 'advertisment_category_translation_id_advertisment_category_id', array(
             'name' => 'advertisment_category_translation_id_advertisment_category_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'advertisment_category',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('advertisment_article', 'advertisment_article_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->addIndex('advertisment_article_translation', 'advertisment_article_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('advertisment_category_translation', 'advertisment_category_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('advertisment_article', 'advertisment_article_category_id_advertisment_category_id');
        $this->dropForeignKey('advertisment_article_translation', 'advertisment_article_translation_id_advertisment_article_id');
        $this->dropForeignKey('advertisment_article_translation', 'advertisment_article_translation_id_advertisment_article_id_1');
        $this->dropForeignKey('advertisment_category_translation', 'advertisment_category_translation_id_advertisment_article_id');
        $this->dropForeignKey('advertisment_category_translation', 'advertisment_category_translation_id_advertisment_category_id');
        $this->removeIndex('advertisment_article', 'advertisment_article_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->removeIndex('advertisment_article_translation', 'advertisment_article_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('advertisment_category_translation', 'advertisment_category_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}