<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('advertisment_serwis1_advertisment', 'advertisment_serwis1_advertisment_author_id_user_user_id');
        $this->dropForeignKey('advertisment_serwis1_advertisment', 'advertisment_serwis1_advertisment_last_editor_id_user_user_id');
        $this->dropForeignKey('advertisment_serwis1_advertisment', 'advertisment_serwis1_advertisment_photo_root_id_media_photo_id');
        $this->dropForeignKey('advertisment_serwis1_advertisment', 'advertisment_serwis1_advertisment_metatag_id_default_metatag_id');
        $this->dropForeignKey('advertisment_serwis2_advertisment', 'advertisment_serwis2_advertisment_author_id_user_user_id');
        $this->dropForeignKey('advertisment_serwis2_advertisment', 'advertisment_serwis2_advertisment_last_editor_id_user_user_id');
        $this->dropForeignKey('advertisment_serwis2_advertisment', 'advertisment_serwis2_advertisment_photo_root_id_media_photo_id');
        $this->dropForeignKey('advertisment_serwis2_advertisment', 'advertisment_serwis2_advertisment_metatag_id_default_metatag_id');
        $this->dropForeignKey('advertisment_serwis3_advertisment', 'advertisment_serwis3_advertisment_author_id_user_user_id');
        $this->dropForeignKey('advertisment_serwis3_advertisment', 'advertisment_serwis3_advertisment_last_editor_id_user_user_id');
        $this->dropForeignKey('advertisment_serwis3_advertisment', 'advertisment_serwis3_advertisment_photo_root_id_media_photo_id');
        $this->dropForeignKey('advertisment_serwis3_advertisment', 'advertisment_serwis3_advertisment_metatag_id_default_metatag_id');
    }

    public function down()
    {
        $this->createForeignKey('advertisment_serwis1_advertisment', 'advertisment_serwis1_advertisment_author_id_user_user_id', array(
             'name' => 'advertisment_serwis1_advertisment_author_id_user_user_id',
             'local' => 'author_id',
             'foreign' => 'id',
             'foreignTable' => 'user_user',
             ));
        $this->createForeignKey('advertisment_serwis1_advertisment', 'advertisment_serwis1_advertisment_last_editor_id_user_user_id', array(
             'name' => 'advertisment_serwis1_advertisment_last_editor_id_user_user_id',
             'local' => 'last_editor_id',
             'foreign' => 'id',
             'foreignTable' => 'user_user',
             ));
        $this->createForeignKey('advertisment_serwis1_advertisment', 'advertisment_serwis1_advertisment_photo_root_id_media_photo_id', array(
             'name' => 'advertisment_serwis1_advertisment_photo_root_id_media_photo_id',
             'local' => 'photo_root_id',
             'foreign' => 'id',
             'foreignTable' => 'media_photo',
             ));
        $this->createForeignKey('advertisment_serwis1_advertisment', 'advertisment_serwis1_advertisment_metatag_id_default_metatag_id', array(
             'name' => 'advertisment_serwis1_advertisment_metatag_id_default_metatag_id',
             'local' => 'metatag_id',
             'foreign' => 'id',
             'foreignTable' => 'default_metatag',
             ));
        $this->createForeignKey('advertisment_serwis2_advertisment', 'advertisment_serwis2_advertisment_author_id_user_user_id', array(
             'name' => 'advertisment_serwis2_advertisment_author_id_user_user_id',
             'local' => 'author_id',
             'foreign' => 'id',
             'foreignTable' => 'user_user',
             ));
        $this->createForeignKey('advertisment_serwis2_advertisment', 'advertisment_serwis2_advertisment_last_editor_id_user_user_id', array(
             'name' => 'advertisment_serwis2_advertisment_last_editor_id_user_user_id',
             'local' => 'last_editor_id',
             'foreign' => 'id',
             'foreignTable' => 'user_user',
             ));
        $this->createForeignKey('advertisment_serwis2_advertisment', 'advertisment_serwis2_advertisment_photo_root_id_media_photo_id', array(
             'name' => 'advertisment_serwis2_advertisment_photo_root_id_media_photo_id',
             'local' => 'photo_root_id',
             'foreign' => 'id',
             'foreignTable' => 'media_photo',
             ));
        $this->createForeignKey('advertisment_serwis2_advertisment', 'advertisment_serwis2_advertisment_metatag_id_default_metatag_id', array(
             'name' => 'advertisment_serwis2_advertisment_metatag_id_default_metatag_id',
             'local' => 'metatag_id',
             'foreign' => 'id',
             'foreignTable' => 'default_metatag',
             ));
        $this->createForeignKey('advertisment_serwis3_advertisment', 'advertisment_serwis3_advertisment_author_id_user_user_id', array(
             'name' => 'advertisment_serwis3_advertisment_author_id_user_user_id',
             'local' => 'author_id',
             'foreign' => 'id',
             'foreignTable' => 'user_user',
             ));
        $this->createForeignKey('advertisment_serwis3_advertisment', 'advertisment_serwis3_advertisment_last_editor_id_user_user_id', array(
             'name' => 'advertisment_serwis3_advertisment_last_editor_id_user_user_id',
             'local' => 'last_editor_id',
             'foreign' => 'id',
             'foreignTable' => 'user_user',
             ));
        $this->createForeignKey('advertisment_serwis3_advertisment', 'advertisment_serwis3_advertisment_photo_root_id_media_photo_id', array(
             'name' => 'advertisment_serwis3_advertisment_photo_root_id_media_photo_id',
             'local' => 'photo_root_id',
             'foreign' => 'id',
             'foreignTable' => 'media_photo',
             ));
        $this->createForeignKey('advertisment_serwis3_advertisment', 'advertisment_serwis3_advertisment_metatag_id_default_metatag_id', array(
             'name' => 'advertisment_serwis3_advertisment_metatag_id_default_metatag_id',
             'local' => 'metatag_id',
             'foreign' => 'id',
             'foreignTable' => 'default_metatag',
             ));
    }
}